### ISSUE TITLE
conversation+discovery java code is not working

### ISSUE THREAD

**Issue by mjpradeep** [watson-developer-cloud/java-sdk#1000]
I am trying to run the sample java Watson conversation with discovery service in my IBM account. I have created the java app and added the service details in environment variables and tried to deploy the code but getting below error. please let me know what is the cause for this issue.

```
Preparing to start the job... Cloning the 'master' branch from repo 'https://git.eu-gb.bluemix.net/anil.narayanaswamy002/tnchatbot.git' Repository successfully cloned Download https://plugins.gradle.org/m2/com/moowork/gradle/gradle-node-plugin/0.12/gradle-node-plugin-0.12.pom Download https://plugins.gradle.org/m2/com/moowork/gradle/gradle-gulp-plugin/0.12/gradle-gulp-plugin-0.12.pom
```

FAILURE: Build failed with an exception.

What went wrong: A problem occurred configuring root project 'conversation-with-discovery'.
```
Could not resolve all dependencies for configuration ':classpath'. Could not resolve org.codehaus.groovy:groovy-backports-compat23:2.3.5. Required by: com.ibm.watson.wea.app:conversation-with-discovery:0.5.0-SNAPSHOT Could not GET 'https://plugins.gradle.org/m2/org/codehaus/groovy/groovy-backports-compat23/2.3.5/groovy-backports-compat23-2.3.5.pom'. peer not authenticated

Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.217 secs

Finished: FAILED
```

**Comment by germanattanasio** [comment]
Hi @mjpradeep,

It looks like you are trying to use an application(`https://git.eu-gb.bluemix.net/anil.narayanaswamy002/tnchatbot.git`) that uses this SDK and it's based on https://github.com/watson-developer-cloud/assistant-with-discovery

That application was archived and we don't support it anymore.

I'm closing this since this is not a problem with the SDK
