### ISSUE TITLE
[speech-to-text] EOFException during audio file processing

### ISSUE THREAD

**Issue by milenkara** [watson-developer-cloud/java-sdk#1004]
I am developing application that utilizes IBM speech to text feature. For that purpose I am using Java API. For some files `BaseRecognizeCallback` interface is called with `onError` method, with `java.io.EOFException` with message set to `null`. This happens when I call speech to text with some larger files.
 
- [x] Steps to reproduce:
In order to reproduce this issue, I used your example project, `RecognizeUsingWebSocketsExample` class and I commented out `interimResults` (since I don't need it) and run the example with my wav file, given on the link https://drive.google.com/drive/u/0/folders/1wqnn_svof8FrR4jmygQKBo131vw00fr6?ogsrc=32
- [x] Expected behavior
IBM should return valid `SpeechRecognitionResults`
- [x] Actual behavior
`onError` method is called with `java.io.EOFException` with message set to `null`.
- [x] JDK version
10.0.2
- [x] java-sdk version
6.9.1

**Comment by lpatino10** [comment]
Hey @milenkara, thanks for your submission. I was able to successfully replicate your issue and am looking at writing a fix for it. I'll update this when I figure it out.

**Comment by lpatino10** [comment]
@milenkara just wanted to let you know that the fix for this issue is part of the latest release. Thanks again for your submission!
