### ISSUE TITLE
[speech-to-text] Interim results set to true but seeing final results

### ISSUE THREAD

**Issue by VidyasagarMSC** [watson-developer-cloud/java-sdk#1005]
I have set the .interimResults(true) for Speech to Text new RecognizeOptions.Builder()
but still seeing the final results than interim results

When reporting a bug, please be sure to include the following:

I have used the examples code and set the interimResults to true. But when I check the response I always see this

{
      "result_index": 0,
      "results": [
        {
          "alternatives": [
            {
              "confidence": 0.728,
              "transcript": "hi what should I call you "
            }
          ],
          "final": true
        }
      ]
    }

Just figured out that the getRecognizeOptions is never setting the interimResults. getRecognizeOptions output

 {
      "content-type": "audio/ogg;codec=opus",
      "inactivityTimeout": 2000,
      "model": "en-US_BroadbandModel"
    }

After looking into the code, I think maybe because https://github.com/watson-developer-cloud/java-sdk/blob/master/speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/RecognizeOptions.java#L441 is missing `interimResults = builder.interimResults`

**Comment by jeffpk62** [comment]
@VidyasagarMSC Just a couple of quick comments:

- Interim results are available _only_ with the Speech to Text WebSocket interface.  So if your calls are to the HTTP speech recognition methods, you should not be able to get interim results.
- When you get interim results with the WebSocket interface, you also get final results.  So once you enable interim results, you'll get both interim and final transcripts in the response.

I hope these help.

**Comment by lpatino10** [comment]
Good catch @VidyasagarMSC. Both points @jeffpk62 made are true, but it should still be there. I'll add it and release a fix as soon as possible.

**Comment by lpatino10** [comment]
@VidyasagarMSC just wanted to let you know that the fix for this issue is part of the latest release. Thanks again for your submission!
