### ISSUE TITLE
[Speech-To-Text] Bad_record_mac when analyzing big audio file

### ISSUE THREAD

**Issue by grale88** [watson-developer-cloud/java-sdk#1007]
I am developing java application that uses speech to text analysis. When I run a big file (~60Mb) on local machine, everything goes fine. When I perform the same analysis on testing environment I get "bad_record_mac" fatal error in "onError" callback. When we run some smaller file (couple of Mb) on test environment everything is fine. I know this is insufficient information for now but I'm wondering if you came across this kind of issue in the past?

- [10.0.2 ] JDK version
- [6.9.2 ] java-sdk version

**Comment by grale88** [comment]
Just to leave a comment that upgrade of OS from Ubuntu 16.04 to 18.04 resolved this problem.

**Comment by germanattanasio** [comment]
I'm glad that you were able to solve the issue @grale88. I guess it was related to the libraries to manipulate the audio. I'm going to close the issue but it will be there for future users running into the same issue
