### ISSUE TITLE
How to update Variable value in IBM Watson Assistant v1 Dialognode respone

### ISSUE THREAD

**Issue by yashpatel001** [watson-developer-cloud/java-sdk#1008]
{
  "output": {
    "text": {
      "values": [
        "$(data)good morning"
      ],
      "selection_policy": "sequential"
    },
    "txcom": 1
  }
}

How to update data register value in Dialognode response using Watson Assistant v1 API using JAVA

**Comment by germanattanasio** [comment]
@yashpatel001 did you look at the examples in the example folder? There should be one related to this and how to send the context back in subsequent messages
