### ISSUE TITLE
Better error message for invalid urls

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/java-sdk#1011]
When attempting to set a url of "{https://gateway.watsonplatform.net/natural-language-understanding/api}" the SDK throws a null pointer exception instead of returning a more useful error message.

A small fix would be to catch null pointer exceptions due to invalid urls and treat them similarly to valid but unreachable urls.

Another, somewhat larger change would be check for and remove surrounding `{}` from url and credential strings, since the `"{url}"` and `"{apikey}"` documentation strings are sometimes misunderstood to include the curly braces.

**Comment by jsstylos** [comment]
See https://stackoverflow.com/questions/53462871/ibm-watson-natural-language-understanding-java-null-pointer-exception/53487466

**Comment by lpatino10** [comment]
Closing as this was fixed in [v6.11.2](https://github.com/watson-developer-cloud/java-sdk/wiki/Changelog#version-6112)
