### ISSUE TITLE
Use Java 8 CompletableFuture or Reactive Streams API

### ISSUE THREAD

**Issue by msogrin** [watson-developer-cloud/java-sdk#1013]
https://github.com/watson-developer-cloud/java-sdk/issues/255 has added reactive support by utilizing a `CompletableFuture` class from `jersey-jsr166e`.

However, there's a standard [java.util.concurrent.CompletableFuture](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html) class in Java 8, which is the better match from compatibility perspective.

There's also [Reactive Streams API](https://github.com/reactive-streams/reactive-streams-jvm). It has multiple popular implementations such as RxJava and Project Reactor in Spring. This API is also 1:1 equivalent to [java.util.concurrent.Flow](https://docs.oracle.com/javase/9/docs/api/java/util/concurrent/Flow.html) in Java 9.

With these new standards available, Watson SDK's support for "reactive" is quite outdated and could mislead new adopters, due to using the "right" names but incompatible classes.

**Comment by lpatino10** [comment]
Hey @msogrin, thanks for bringing this up. I've fallen behind on these standards a bit honestly so it's good to know that this might be worth looking into if it's confusing.

I'll do some research and update here, so I'm going to go ahead and leave this open in the meantime.
