### ISSUE TITLE
[speech-to-text] websockets : java.io.EOFException when using Header "Transfer-Encoding chunked"

### ISSUE THREAD

**Issue by Cidkinneas** [watson-developer-cloud/java-sdk#1017]
Hi,

When using the SpeechToText with header "Transfer-Encoding chunked" okio return an java.io.EOFException.

When I ommit it, the response is ok (I receive transcription results)

Full Trace : 
```
java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.java:61)
        at okio.RealBufferedSource.readByte(RealBufferedSource.java:74)
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:213)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

Source Code:

            Map<String, String> mapHeaders = new HashMap<>();
            mapHeaders.put("Transfer-Encoding", "chunked");

            SpeechToText speechToText = new SpeechToText(options); // Options builts with IamOptions
            speechToText.setEndPoint("{url}");
            speechToText.setDefaultHeaders(mapHeaders);

            RecognizeOptions recognizeOptions = new RecognizeOptions.Builder()
                    .audio(file)
                    .contentType(HttpMediaType.AUDIO_RAW + "; rate="+ 16000)
                    .inactivityTimeout(30)
                    .model("fr-FR_BroadbandModel")
                    .interimResults(true)
                    .build();

            BaseRecognizeCallback baseRecognizeCallback =
                    new BaseRecognizeCallback() {

                        @Override
                        public void onInactivityTimeout(RuntimeException runtimeException) {
                            Log.e("MediaRecorder", "Recognize InactivityTimeout Error : ", runtimeException);
                        }

                        @Override
                        public void onTranscription
                                (SpeechRecognitionResults speechRecognitionResults) {
                            System.out.println(speechRecognitionResults);
                        }

                        @Override
                        public void onError(Exception e) {
                            Log.e("MediaRecorder", "Recognize Error : ", e);
                        }

                        @Override
                        public void onDisconnected() {
                            Log.i("SpeechToTextProcessor", "Disconnected : ");
                        }

                    };

            WebSocket socket = speechToText.recognizeUsingWebSocket(recognizeOptions,
                    baseRecognizeCallback);
`

**Comment by lpatino10** [comment]
Hey @Cidkinneas. The `Transfer-Encoding` header isn't supported in the WebSocket version of `recognize` because the `WebSocket` implementation already sends data piece-by-piece instead of all at once.

It'll work fine in the normal `recognize()` method, but if you omit that header in your code above, you should still get the results you're looking for.
