### ISSUE TITLE
Custom TLS configuration cannot be disabled or modified

### ISSUE THREAD

**Issue by zlogic** [watson-developer-cloud/java-sdk#1019]
`HttpClientSingleton#setupTLSProtocol` configures TLS/SSL when creating an `HttpClientSingleton` instance. It's not possible to disable this (and just use the default SSL context/socket factory) or to provide a custom TLS/SSL configuration.

**Comment by lpatino10** [comment]
Hey @zlogic. You're correct that currently there's not much configuration available in this area: it's either use what we're setting or disable SSL verification altogether.

Would you be able to explain your use case a bit to understand your desire to configure this? "Configurability" is always a nice option, but we like to limit that ability in the SDKs apart from crucial configuration options. A little more insight will help us weigh this decision.

Thanks!

**Comment by zlogic** [comment]
Hi @lpatino10, I've had issues with running the Watson Java SDK in a Java container with a custom security policy. This policy has a whitelist of System Properties which can be read or written.

The `HttpClientSingleton#setupTLSProtocol` method was throwing a security exception (caused by  #1020) and made it impossible to initialize an `HttpClientSingleton` instance.

So one way of fixing this could be to have an option to avoid calling `HttpClientSingleton#setupTLSProtocol` (or to call a custom "TLS Configuration" method).
If #1020 is fixed, then I don't think this feature is necessary.
