### ISSUE TITLE
Unnecessary changing the com.ibm.jsse2.overrideDefaultTLS system property

### ISSUE THREAD

**Issue by zlogic** [watson-developer-cloud/java-sdk#1020]
The `HttpClientSingleton#setupTLSProtocol` method sets the `com.ibm.jsse2.overrideDefaultTLS` system property to `true`.

However this method only modifies the SSL configuration for a `HttpClientSingleton` instance, and the global SSL configuration remains unaffected.

1. This may result in unexpected behavior if the user specifically launched the JVM with a `-Dcom.ibm.jsse2.overrideDefaultTLS=false` argument.
2. In addition, if other classes read the `com.ibm.jsse2.overrideDefaultTLS` property, they may wrongly assume that the default SSL context is an IBM-specific configuration.
3. Any `SSLSocketFactory` instances created before the `HttpClientSingleton#getInstance` method is called for the first time will be using the default SSL configuration. Changing system-wide configuration `overrideDefaultTLS` should be done while the application is initialized and not after it has been running for some time.

**Comment by lpatino10** [comment]
Hey @zlogic, I appreciate the input. We had an issue a while back with some handshake exception causing issues in Oracle JDK 7 and this seemed to fix it, but it's very possible that it was a misguided solution.

I'll do some more research and take another look at it.
