### ISSUE TITLE
[Assistant V2] Truncated output in MessageResponse in Java SDK

### ISSUE THREAD

**Issue by vperrinfr** [watson-developer-cloud/java-sdk#1021]
I have in a dialog node with a custom JSON output with that content:
```json
{
  "output": {
    "text": {
      "values": [
        "Lorem Ipsum"
      ],
      "selection_policy": "sequential"
    },
    "urls": {
      "values": [
        "URL_ECP_001"
      ]
    },
    "images": {
      "values": [
        "IMG_ECP_SINISTRE_001",
        "IMG_ECP_SINISTRE_002"
      ]
    },
    "buttons": {
      "details": [
        {
          "type": "SIMPLE",
          "label": "Oui"
        },
        {
          "type": "SIMPLE",
          "label": "Non"
        }
      ]
    }
  }
}
```

And, I want to retrieve the dialog node response of Watson Assistant.

- Expected behavior
I want to retrieve the content of the output field with all the content.
in Java SDK Assistant V1, it works fine.

I have also tested with Node.Js Assistant V2 and I have that result:
```json
{
  "output": {
    "generic": [{
      "response_type": "text",
      "text": "Lorem Ipsum"
    }],
    "intents": [{
      "intent": "test",
      "confidence": 0.9063668251037598
    }],
    "user_defined": {
      "urls": {
        "values": [
          "URL_ECP_001"
        ]
      },
      "images": {
        "values": [
          "IMG_ECP_SINISTRE_001",
          "IMG_ECP_SINISTRE_002"
        ]
      },
      "buttons": {
        "details": [
          {
            "type": "SIMPLE",
            "label": "Oui"
          },
          {
            "type": "SIMPLE",
            "label": "Non"
          }
        ]
      }
    }
  }
}
```

- Actual behavior

But in fact, with Java SDK Assistant V2, I have that result:

```json
{
  "output": {
    "generic": [
      {
        "response_type": "text",
        "text": "Lorem Ipsum"
      }
    ],
    "intents": [
      {
        "intent": "test",
        "confidence": 1.0
      }
    ],
    "entities": []
  }
}
```
- java-sdk version: 6.11.0

Thanks a lot

**Comment by lpatino10** [comment]
@vperrinfr thanks for submitting this. I'll take a look at reproducing this soon. Just to check before though, are you using the same workspace for the Node and Java calls?

**Comment by vperrinfr** [comment]
Yes, I can share the four files (2 in Node, 2 in Java) I have written to test. I can even give you my skill json if you want.

**Comment by lpatino10** [comment]
@vperrinfr that would be very helpful!

**Comment by lpatino10** [comment]
@vperrinfr I just opened a PR to fix this that I've linked to this issue. The PR explains how to grab the keys that were previously missing.

Once that's merged, just be on the lookout for a patch release to resolve this problem.
