### ISSUE TITLE
v7.0.0 goals

### ISSUE THREAD

**Issue by lpatino10** [watson-developer-cloud/java-sdk#1038]
Hey everyone,

Soon (within the next month or so), we plan to release **v7.0.0** of the Java SDK. We wanted to create this issue to get feedback on features/changes the community might want to see with this release. If you see suggestions from others or in the list we already have that you agree with, please give a thumbs-up to help drive development for those items.

Here's what we're already planning for this release:
- Moving the "core" of the SDK to a separate repo. This repo will just contain code for the individual Watson services.
- Switching repository managers to allow for quicker, automated version releases
- Removing the Conversation service
- Removing other deprecated functionality, either service-specific or things like old token authentication
- Replacing `execute()` and `enqueue()` with their `WithDetails()` counterparts. Basically, we'll always return the wrapped response with the model and additional HTTP information
- Replacing the `rx()` and `rxWithDetails()` methods with one that leverages [RxJava](https://github.com/ReactiveX/RxJava)

We look forward to your feedback!

**Comment by germanattanasio** [comment]
Remove the code to parse the error which includes alchemy stuff

**Comment by lpatino10** [comment]
Closing as `v7.0.0` is in the process of releasing now!
