### ISSUE TITLE
[assistant] customer id parameter when sending message

### ISSUE THREAD

**Issue by camrschuette** [watson-developer-cloud/java-sdk#1048]
When sending a message through either version of the assistant service, having a parameter available to set that header in the request would be useful instead of using the `addHeader` function on the `ServiceCall` class.

For example: the `Assistant` class in the v2 package, the `message` function could set both the analytics header and optionally the `X-Watson-Metadata` header with the customer id being set.

**Comment by lpatino10** [comment]
Hey @camrschuette, thanks for the feedback. Just for my understanding though, would you be able to give some sort of pseudocode example or more concrete explanation as to how your request would be different? I'd just like to get an idea of how useful this could be.
