### ISSUE TITLE
Cannot use getResult on Voices [TextToSpeech]

### ISSUE THREAD

**Issue by akyong** [watson-developer-cloud/java-sdk#1051]
```java
TextToSpeech service = new TextToSpeech();
                IamOptions options = new IamOptions.Builder()
                        .apiKey(apikey)
                        .build();
                service.setIamCredentials(options);
                Voices voices = service.listVoices().execute().getResult(); //cannot call `getResult`
                System.out.println(voices);
```

**Comment by lpatino10** [comment]
Is this like like this in your code or just a typo?
```java
service.listVoices().execute().ge()tResult();
```
Otherwise, have you upgraded to `v7.0.0` where this is introduced?

**Comment by lpatino10** [comment]
Sorry @akyong, it seems like the installation instructions didn't get fully updated in the README. I'm fixing that up now.

**Comment by akyong** [comment]
sorry, you are right, i must upgrade it to v7. thank you

**Comment by lpatino10** [comment]
@akyong it looks like there were some problems with the release entirely actually 😞  I would stick to `6.14.0` for now until things get resolved.

**Comment by lpatino10** [comment]
@akyong Things are resolved for the most part now. If you'd like to use `v7.0.0`, just be sure to follow the new installation instructions since they're a little different: https://github.com/watson-developer-cloud/java-sdk#installation

**Comment by akyong** [comment]
@lpatino10  thank you 👍
