### ISSUE TITLE
C&C - IBM Cloud Java API Doc does not match source or SDK JAR

### ISSUE THREAD

**Issue by jchblsc** [watson-developer-cloud/java-sdk#1054]
Specifically for C&C, the Java API doc on IBM Cloud references the primary class as CompareAndCompy whereas the actual implementation is CompareComply - as reflected in the source on this GitHub site and in the SDK JAR.

**Comment by lpatino10** [comment]
Hi @jchblsc, thanks for pointing this out to us! I'll let the right people know to get that changed and clear up any confusion.

**Comment by lpatino10** [comment]
@jchblsc the change has been made but there's a bit of a process to get docs changed. Whenever the next updates get released though, it should be cleared up. I'm going to go ahead and close this issue since the fix is in the pipeline, but thanks again for bringing this to our attention!
