### ISSUE TITLE
DISCOVERY - IAM Endpoint not using custom headers when performing query

### ISSUE THREAD

**Issue by viveknairibm** [watson-developer-cloud/java-sdk#1060]
The problem happens when trying to connect and perform our first query against the Production collection, which requires IAM to authenticate. While we had adjusted the base URLs for connectivity to pass through the corporate Data Power, we found that there is an additional IAM-specific endpoint that we need to configure to go through DataPower. 

While changing the code is a quick change, our testing shows that the necessary Headers (set using discovery.setHeaders) appear not to be set when this IAM endpoint is used. We need these headers for authentication to the corporate DataPower. 
Is this a defect? 

- Does IBM have a way to force the headers to be set/used with the IAM Auth Endpoint. ?

slack - https://ibm-watson.slack.com/archives/C56GJSW7K/p1556657197082700

**Comment by lpatino10** [comment]
Hi @viveknairibm, thanks for bringing this up. Currently, there's no built-in way to edit headers being sent to the IAM endpoint through the SDK. There might be a workaround using the underlying HTTP library, but it's not something we have readily available.

We'll discuss this and see what we can do to support this if necessary.

**Comment by lpatino10** [comment]
@viveknairibm while we discuss, someone did come up with a workaround.

You can authenticate with IAM by using username/password auth with the following format:
```
username: apikey
password: {IAM API key}
```
If you do this, headers that are set with `discovery.setHeaders()` will also be set for authentication. I think this should work for now.

**Comment by lpatino10** [comment]
@viveknairibm just wanted to let you know that this feature of being able to send headers specifically for the IAM request will be added in the `8.x.x` release!

**Comment by lpatino10** [comment]
Closing as this is included in the latest release (v8.0.0)
