### ISSUE TITLE
WA API V2 Java SDK - Add setters for DialogRuntimeResponseGeneric class 

### ISSUE THREAD

**Issue by jassingh01** [watson-developer-cloud/java-sdk#1064]
The use case I am working on needs the Service Orch Engine (SOE) do some "on the fly" modifications to the text under `MessageResponse object -> MessageOutput object -> DialogRuntimeResponseGeneric object` coming as an output from WA before it is sent to VGW for play back.

This is needed as our use case has a security requirement to limit exposure to user's PII data as much as possible.  So, WA is being implemented in such a way that, while it asks the user to provide their PII information, it will not handle the actual PII itself.  The WA just drives the conversation (for example, ask the user of their PII data and then repeats it for the user confirmation) and use `Place holders` for the PII field.

The SOE, under the covers, is tasked with substituting the actual PII value once we get the `place holder` for the corresponding PII field from the WA ... then it sends the modified `MessageResponse` object to the voice agent for playback.

When using WA v1 ... we can use the `DialogRuntimeResponseGeneric` class's setter methods to modify the text object and then send the modified `MessageResponse` object to VA.

However, there is no way to handle this scenario in v2 as `MessageResponse -> DialogRuntimeResponseGeneric` class no longer has any setter methods.

**Comment by jassingh01** [comment]
As a pictorial illustration ... what we are trying to do is:

WA's output JSON with [PLACEHOLDER] ===> SOE to replace the place holder with actual data ===> input JSON to Voice gateway.

The setter method we are curently using for our use case (/assistant/src/main/java/com/ibm/watson/assistant/v1/model/DialogRuntimeResponseGeneric.java) :

`  /**
   * Sets the text.
   *
   * @param text the new text
   */
  public void setText(final String text) {
    this.text = text;
  }
`

**Comment by lpatino10** [comment]
Hi @jassingh01. We're sorry for the inconvenience.

We generate the SDKs, and as part of that, models are categorized in terms of whether they're sent to the service or returned. Ones that aren't ever sent to the service don't get setters. Apparently, this categorization has changed from Assistant v1 -> v2, hence the lack of setters.

So, what you're seeing is expected, but your use case is something we didn't think of. We're going to talk it over to see if this is something we want to change in a future release. In the meantime, if you're just using the `message` endpoint, you should be able to use the v1 API to keep the ability to modify that model.

I'll report back with any updates here.

**Comment by jassingh01** [comment]
@lpatino10 Thank you for your prompt reply and looking forward to your updates.

**Comment by lpatino10** [comment]
Closing as this was fixed in #1065
