### ISSUE TITLE
Set Proxy Username and Password

### ISSUE THREAD

**Issue by marloncarvalho** [watson-developer-cloud/java-sdk#1071]
Many applications may need to configure a proxy to access external services. The Java SDK supports defining a proxy through the class HttpConfigOptions however it doesn't allow us to define a username and password to access this proxy. Often, it's not possible to change proxy policies in the companies, so the alternatives listed in issue #384 are not feasible. 

One simple solution to this problem is to just allow defining an okhttp3.Authenticator in HttpConfigOptions and handle this new configuration in HttpClientSingleton.configureClient().

**Comment by germanattanasio** [comment]
@marloncarvalho I think the README has instructions on how to do this

**Comment by marloncarvalho** [comment]
Thanks, @germanattanasio! It shows how to set a Proxy using HttpConfigOptions and points to a StackOverflow question showing how to configure an Authenticator using OkHttpBuilder directly. However, in my case, I think it doesn't solve the problem. 

The class HttpClientSingleton holds an OkHttpClient instance, with common configurations, that is shared throughout the whole SDK. I cannot see a way to replace this OkHttpClient with a new one that contains Authentication configuration as proposed in the StackOverflow question. 

Every service that needs an OkHttpClient instance to make a call, for example, the class IamTokenManager, calls HttpClientSingleton.createHttpClient() that uses the pre-configured OkHttpClient.

**Comment by lpatino10** [comment]
Hi @marloncarvalho. I had to look through the code a bit but what you're saying makes sense. Basically, we offer the ability to configure the proxy, but adding authentication to that isn't possible.

I think your simple solution makes sense, but I'll take a look at the core code and investigate how best to fix this. I'll keep you updated in the issue about a patch.

**Comment by marloncarvalho** [comment]
Hi @lpatino10. Thanks! If you guys are too busy, I can make this change and send a Pull Request. Just point out what's the best solution to this problem.

**Comment by lpatino10** [comment]
Issue moved to [watson-developer-cloud/java-sdk-core #1](https://github.com/watson-developer-cloud/java-sdk-core/issues/1) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lpatino10** [comment]
@marloncarvalho that would be great! I just closed this to move it to the correct repo here: https://github.com/IBM/java-sdk-core/issues/44

**Comment by sarahbacha** [comment]
We are trying the proxy with a discovery instance
```
Authenticator proxyAuthenticator = new Authenticator() {
		@Override
		public Request authenticate(Route route, Response response) throws IOException {
			String credential = Credentials.basic(proxyUsername, proxyPassword);
			return response.request().newBuilder().header("Proxy-Authorization", credential).build();
		}
	};
```
```
HttpConfigOptions configOptions = new HttpConfigOptions.Builder().disableSslVerification(true).proxy(proxy)
				.proxyAuthenticator(proxyAuthenticator).loggingLevel(HttpConfigOptions.LoggingLevel.HEADERS).build();
```

And getting the following error:
**type definition error: [simple type, class com.ibm.cloud.sdk.core.http.Headers]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class com.ibm.cloud.sdk.core.http.Headers and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.ibm.cloud.core.service.exception.ServiceResponseException[\"Headers\"])**
