### ISSUE TITLE
java.lang.NoSuchMethodError: com.ibm.watson.discovery.v1.Discovery.getServiceUrl()

### ISSUE THREAD

**Issue by skltree** [watson-developer-cloud/java-sdk#1090]
I am using very simple code : 

import com.ibm.cloud.sdk.core.security.IamAuthenticator;
import com.ibm.watson.discovery.v1.Discovery;
public class DiscoveryTest {

	public static void main(String[] args) {
		IamAuthenticator authenticator = new IamAuthenticator("<KEY>");
		Discovery discovery = new Discovery("2018-08-01",authenticator);
		
		discovery.setEndPoint("https://gateway.watsonplatform.net/discovery/api/");
		System.out.println(discovery.getName());
	}
}
POM :
<dependency>   
  			<groupId>com.ibm.watson</groupId>
  			<artifactId>ibm-watson</artifactId>
  			<version>8.0.0</version>
		</dependency>
		  <dependency>
			<groupId>com.ibm.cloud</groupId>
			<artifactId>sdk-core</artifactId>
			<version>7.0.0-rc1</version>
		</dependency> 

Error : 
Exception in thread "main" java.lang.NoSuchMethodError: com.ibm.watson.discovery.v1.Discovery.getServiceUrl()Ljava/lang/String;
	at com.ibm.watson.discovery.v1.Discovery.<init>(Discovery.java:158)
	at com.ibm.tsc.dashbrd.DiscoveryTest.main(DiscoveryTest.java:12)

Why there is no method called getServiceUrl() in Discovery or super class ?

**Comment by lpatino10** [comment]
If you're using the SDK you don't need to manually pull in the core package as well. The SDK library already contains the `sdk-core` version that it needs, so removing the `com.ibm.cloud:sdk-core` dependency from your POM should solve the problem.

Right now you're pulling in a release candidate version of the core which doesn't have the `getServiceUrl()` method, so it's conflicting.

**Comment by skltree** [comment]
Hello, Thanks for replying .
I am using  com.ibm.cloud.sdk.core.security.IamAuthenticator;
I can only find IamAuthenticator in core sdk how to get rid of this error if I remove core sdk POM dependency ?

**Comment by lpatino10** [comment]
See https://github.com/watson-developer-cloud/java-sdk/issues/1091#issuecomment-541409604.

You should already have access to that class through the transitive dependency.
