### ISSUE TITLE
java.lang.NoSuchMethodError: com.ibm.watson.discovery.v1.Discovery.getServiceUrl()

### ISSUE THREAD

**Issue by skltree** [watson-developer-cloud/java-sdk#1091]
I am using very simple code :
`
import com.ibm.cloud.sdk.core.security.IamAuthenticator;
import com.ibm.watson.discovery.v1.Discovery;
public class DiscoveryTest {

public static void main(String[] args) {
    IamAuthenticator authenticator = new IamAuthenticator("<KEY>");
    Discovery discovery = new Discovery("2018-08-01",authenticator);

    discovery.setEndPoint("https://gateway.watsonplatform.net/discovery/api/");
    System.out.println(discovery.getName());
}

}

`

POM :

com.ibm.watson
ibm-watson
8.0.0

com.ibm.cloud
sdk-core
7.0.0-rc1

Error :

Exception in thread "main" java.lang.NoSuchMethodError: com.ibm.watson.discovery.v1.Discovery.getServiceUrl()Ljava/lang/String;
at com.ibm.watson.discovery.v1.Discovery.(Discovery.java:158)
at com.ibm.tsc.dashbrd.DiscoveryTest.main(DiscoveryTest.java:12)

Why there is no method called getServiceUrl() in Discovery or super class ?

**I am not able to remove core SDK dependency  in POM because i am using IamAuthenticator.
IamAuthenticator is not in watson package however it's in core SDK.**

Please suggest compatible JAR version.

**Comment by lpatino10** [comment]
I know you closed this but I'll go ahead and answer for anyone who might come across this in the future.

You do not need to manually specify a version of the `com.ibm.watson:sdk-core` package to use this SDK. The SDK already specifies a compatible version in its dependencies.
