### ISSUE TITLE
MicrophoneWithWebSocketsExample.java ,ERROR "could not detect endianness after looking at the tail .."

### ISSUE THREAD

**Issue by mahsankhaan** [watson-developer-cloud/java-sdk#1092]
Any idea what's wrong in this?
<img width="1055" alt="Screenshot 2019-10-14 at 2 10 07 AM" src="https://user-images.githubusercontent.com/56512649/66722572-cdc73d80-ee28-11e9-8379-0653fd7471a6.png">

**Comment by lpatino10** [comment]
Hmm I haven't seen that error before, but I'd be happy to take a look. Would you be able to paste the full code snippet for me to walk through?

(Also, be sure not to share any sensitive credentials 🙃)

**Comment by germanattanasio** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
