### ISSUE TITLE
Make builder initializers public

### ISSUE THREAD

**Issue by JaPaBu** [watson-developer-cloud/java-sdk#1093]
I am trying to set the previousSibling field of a DialogNode but there is no setter.

When creating a builder you are forced to initialize every field by yourself. This is bad since new fields can be added by the SDK.

Why not make this builder public for example?

https://github.com/watson-developer-cloud/java-sdk/blob/a7852f941e78798d277b450ba3ff6e753ac982d9/assistant/src/main/java/com/ibm/watson/assistant/v1/model/DialogNode.java#L162

**Comment by lpatino10** [comment]
Hey @JaPaBu, would you be able to elaborate on this a bit? I'm not sure I totally understand.

When you're trying to set the `previousSibling` field, you can create a new builder and set that:

```java
DialogNode dialogNode = new DialogNode.Builder()
  .previousSibling("previous_one")
  .build();
```

I'm also not sure what you mean by:

>This is bad since new fields can be added by the SDK.

**Comment by JaPaBu** [comment]
Of course @lpatino10 .

I use the SDK to manipulate the dialog of my assistant. When removing a dialog node for example you need to reconnect the dialog or else the API throws an error. This is done by either setting the previousSibling field of the now unconnected node with reflections or by specifying every field again to get a copy of the now unconnected node with just a modified previousSibling.

```java
DialogNode dialogNode = new DialogNode.Builder()  
  .previousSibling("previous_one")
  .dialogNode(oldNode.dialogNode())
  .output(oldNode.output())
  .metadata(oldNode.metadata())
  ...
  .build();
```

It would be nice if i could use

```java
DialogNode dialogNode = new DialogNode.Builder(oldNode)
  .previousSibling("previous_one")
  .build();
```

> This is bad since new fields can be added by the SDK.

If the API was to add a new field to dialogNodes a new line would have to be inserted:

```java
.newField(oldNode.newField())
```

which can be easily forgotten and possibly create very hard to debug problems.

**Comment by JaPaBu** [comment]
You are right i must have overlooked that method.

Sorry for the inconvenience.

**Comment by lpatino10** [comment]
No worries! Glad I could help.
