### ISSUE TITLE
Jar with dependencies contains unnecessary and potentially harmful dependencies

### ISSUE THREAD

**Issue by smccants** [watson-developer-cloud/java-sdk#1095]
**Overview**
I'm trying to use the ibm-watson-8.0.0-jar-with-dependencies.jar in my application and cannot because it contains unnecessary class files that conflict with classes included in my application.

**Expected behavior**
Be able to add the jar file to my application and successfully compile.

**Actual behavior**

```
:app:transformClassesWithDexBuilderForDebug
 AGPBI: {"kind":"error","text":"Program type already present: edu.umd.cs.findbugs.annotations.CreatesObligation","sources":[{}],"tool":"D8"}
 :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
 
 FAILURE: Build failed with an exception.
 
 * What went wrong:
 Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
 .....
   Program type already present: edu.umd.cs.findbugs.annotations.CreatesObligation
   Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
```

**How to reproduce**
Build an application that includes FindBugs and then include the java-sdk jar file.  The two FindBugs classes will conflict with each other,

**SDK Version**
8.0.0

**Additional information:**
- OS: Android 7.x+, built under KUbuntu 14.04 LTS
- Which version of `Java` are you using? 1.8

**Additional context**
I think the problem is a variety of "dependencies" are included in the jar file that are unnecessary and potentially harmful.  I had to remove the following from the jar in order to get my application to compile:
- Findbugs
- javax.annotations
- net/jcip/annotations

I also think (but I'm not sure) the following could be removed:
- org.checkerframework
- org.codehaus
- org.hamcrest
- org.mockito
- org.objenesis
- org.reactivestreams

**Comment by smccants** [comment]
Switching from using the jar file to the gradle include

    implementation 'com.ibm.watson:ibm-watson:8.0.0'

Results in the same problem:

```
:app:transformClassesWithDexBuilderForDebug
AGPBI: {"kind":"error","text":"Program type already present: edu.umd.cs.findbugs.annotations.CreatesObligation","sources":[{}],"tool":"D8"}
:app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: .....
  Program type already present: edu.umd.cs.findbugs.annotations.CreatesObligation
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
```

**Comment by smccants** [comment]
Possible interest - #93

**Comment by smccants** [comment]
Tried with just the components I need from Gradle:

    implementation 'com.ibm.watson:speech-to-text:8.0.0'
    implementation 'com.ibm.watson:text-to-speech:8.0.0'

Resulted in the same compile error as the two above.

**Comment by lpatino10** [comment]
This might be of interest to you for dealing with the duplicate dependencies issue: https://github.com/watson-developer-cloud/java-sdk/issues/1061#issuecomment-492785271

Otherwise, I haven't run into this issue before, but I can verify. I know off the top of my head though looking at your dependency list that there are some that are definitely used in the project and required. I can go through and remove anything that seems extraneous.

**Comment by smccants** [comment]
@lpatino10 I looked at the comment you referenced and it seems to be just a different way to exclude dependencies I don't want, but I'm confused.  Why would those dependencies be included in the first place?  Shouldn't you include the minimum set of dependencies necessary to use the product?

**Comment by smccants** [comment]
I tried taking a different approach.  Using the dependency tree here (https://javalibs.com/artifact/com.ibm.watson/ibm-watson) and trial and error, I came up with a minimum set of jar files we seem to need for our text-to-speech and speech-to-text usages.  Those mimimum jars are:

    implementation files('libs/speech/ibm-watson-common-8.0.0.jar')
    implementation files('libs/speech/ibm-watson-sdk-core-7.0.0.jar')
    implementation files('libs/speech/ibm-watson-speech-to-text-8.0.0.jar')
    implementation files('libs/speech/ibm-watson-text-to-speech-8.0.0.jar')
    implementation files('libs/speech/ibm-watson-android-sdk-0.5.1.aar')
    implementation files('libs/speech/okhttp-3.14.4.jar')
    implementation files('libs/speech/okhttp-urlconnection-3.12.1.jar')
    implementation files('libs/speech/okio-1.17.4.jar')
    implementation files('libs/speech/commons-lang3-3.9.jar')
    implementation files('libs/speech/gson-2.8.5.jar')

So that is excluding a lot more than what we discussed before, but that isn't surprising to me.  Is there a better way to do this?  I'm still confused why FindBugs, Mockito and other obviously not-for-production-deployment code is included.

**Comment by lpatino10** [comment]
Thanks for continuing to look @smccants. Also, that tool you linked is pretty cool.

I've been reviewing dependencies and we have FindBugs and Mockito in the core SDK package. We don't seem to be using FindBugs at all, so I can go ahead and remove that, and Mockito wasn't tagged as a test dependency only, hence why it shows up in release JARs.

Other dependencies you mentioned we either do need or are nested dependencies, but I'll double-check before releasing a patch. Those changes should cut down some unnecessary libraries.

**Comment by smccants** [comment]
@lpatino10 Thanks for looking into it.  My guess is that marking Mockito as a test library will also remove objensis and hamcrest, as that link shows Mockito pulling them in.  We could likely move to whatever version you next release with those changes. 

I'm not sure what to do about javax.annotations as we load javax.annotations for our own purposes and that seems to trip up Android's build process.

In the meantime (that is before you're next release), we are going to try the limited set of Jars I listed earlier.  That seems to meet our needs.

Thanks again.

**Comment by smccants** [comment]
Ended up going with the exclude route as a work around and that is easier and meets our needs:

    implementation ('com.ibm.watson:ibm-watson:8.0.0', {
        exclude group: 'com.google.code.findbugs' // We already have findbugs
        exclude group: 'org.mockito' // Mockito isn't needed either
    })

**Comment by lpatino10** [comment]
Glad you have a workaround for now! I have a PR open to the core of the SDK so just be on the lookout for a patch release of this SDK.
