### ISSUE TITLE
Can not login at IBM with Java SDK

### ISSUE THREAD

**Issue by cunhazera** [watson-developer-cloud/java-sdk#1098]
I'm using the last version of this project and trying to use Basic Authentication with user and password, but It always responds 401.

This is the code I'm actually running:
``` java
        String user = "user-test"; // The username I'm using here is the same that I use to login at https://cloud.ibm.com (which is an email)
        String pass = "pass-test";
        Authenticator authenticator = new BasicAuthenticator(user, pass);
        Assistant service = new Assistant("2019-04-30", authenticator);
        service.setEndPoint("https://gateway.watsonplatform.net/discovery/api/");
        MessageOptions message = new MessageOptions.Builder().workspaceId("work").build();
        service.message(message).execute();
```

**SDK Version**
8.0.1

Java version: 11

**Comment by lpatino10** [comment]
Hey @cunhazera.

The username and password you should be supplying are the credentials given to you when you create a service instance on IBM Cloud. If you're trying to use Watson Assistant, that would mean going here and selecting your price tier: https://cloud.ibm.com/catalog/services/watson-assistant. We have a free option to get up and running.

If you want to try other Watson services that are supported by this SDK, you can see your options here: https://cloud.ibm.com/catalog?category=ai

Once you select your tier, you should be directed to a dashboard page with information about your service instance. There, you'll see the credentials which can be used for authentication. This section of the README explains how to use the credentials you get in your code to get everything up and running: https://github.com/watson-developer-cloud/java-sdk#supplying-credentials

**Comment by cunhazera** [comment]
We're already using watson, but we're creating everything throught Cloud Funtry.
We have to migrate the authentication method to the IBM API.
So I'm the scenario that I have to retrieve my data with no API Key, nor token, only the user and pass in a first moment.

**Comment by lpatino10** [comment]
I don't have much experience using Cloud Foundry, but if you have a Watson instance of some service, it should have associated credentials. Your regular IBM login will not work when trying to access a Watson API.

Can you find your instance(s) somewhere on your IBM Cloud dashboard? They should be somewhere in your resources list: https://cloud.ibm.com/resources

**Comment by cunhazera** [comment]
Ok, I got it. For each instance that I created a group of credentials is generated, right?

How do I create an instance with the IBM SDK? Forgive me, but I don't which SDK to use for this case.

**Comment by germanattanasio** [comment]
@cunhazera You can't create service instances with the SDK.

if you go to https://cloud.ibm.com/resources you will see your Watson service instances. Click on any of them and you will see the credentials.

**Comment by lpatino10** [comment]
What German said ☝️ 

I would go through the UI to create your instance. Once you get those credentials, you can do everything else through the SDK.

**Comment by cunhazera** [comment]
@germanattanasio and @lpatino10 thanks for the response.
Maybe *service* was not the word. I'm actually creating `instances` with Cloud Foundry:

``` java
        CreateServiceInstanceRequest request = CreateServiceInstanceRequest.builder()
                .serviceName(CONVERSATION_SERVICE)
                .planName(PLAN_STANDARD)
                .serviceInstanceName(INSTANCE_NAME)
                .build();

        RuntimeConfiguration provider = // provider here
        CloudFoundryOperations cfops = // CF operations here
        cfops.services().createInstance(request).block();
        cfops.services()
                .createServiceKey(CreateServiceKeyRequest.builder()
                        .serviceInstanceName(request.getServiceInstanceName())
                        .serviceKeyName(KEY_NAME)
                        .build())
                .block();
```

When our clients create a new Watson Bot a instance is created, so we have a deadline to migrate from CF to IBM APIs.

**Comment by lpatino10** [comment]
Unfortunately, we stopped supporting Cloud Foundry-based authentication for service instances on October 30th in favor of IAM. See [here](https://medium.com/ibm-watson/identity-and-access-management-updates-for-watson-services-12b6344b9cf) for more info.

[Here](https://cloud.ibm.com/docs/iam?topic=iam-iamoverview) is a page explaining a bit more about IBM Cloud IAM. There are some links to API references at the bottom of the page to do things programmatically like you were with Cloud Foundry before, but I wasn't able to find any SDKs to make things a bit easier. If at all possible, I think it would be easiest to go through the UI on IBM Cloud to create your instances and get credentials.

**Comment by cunhazera** [comment]
Ok, I got it.

I'm trying to use the `BasicAuthenticator`, which user & pass should I use to get my credentials?

**Comment by cunhazera** [comment]
I'll leave the gist that German wrote, might be helpful in the future for somebody else.
https://gist.github.com/germanattanasio/478fd6a6c24c5c8fddb74f3cf3e7dff6#file-readme-md

@lpatino10 @germanattanasio thank you guys.

**Comment by lpatino10** [comment]
Awesome, thanks for the detailed rundown @germanattanasio!
