### ISSUE TITLE
cannot override user defined context from client

### ISSUE THREAD

**Issue by yusufcakmakk** [watson-developer-cloud/java-sdk#1104]
**Overview**
User defined context value cannot be overridden by client.

**Expected behavior**
When I set user defined context variable to null or remove, it shouldn't be in watson responce context.

**Actual behavior**
When I set user defined context variable to null or remove, it comes with same value like no change.

**How to reproduce**
```java
String assistantId = "";
String apiKey = "";
Authenticator authenticator = new IamAuthenticator(apiKey);
Assistant service = new Assistant("2019-02-28", authenticator);

MessageInputOptions inputOptions = new MessageInputOptions.Builder().returnContext(true).debug(true).build();

String[] messages = { "faturam gelmedi", "ocak" };
// Create session.
CreateSessionOptions createSessionOptions = new CreateSessionOptions.Builder(assistantId).build();
SessionResponse session = service.createSession(createSessionOptions).execute().getResult();
String sessionId = session.getSessionId();

Map<String, Object> userDefinedContext = new HashMap<>();
MessageContextSkills skillsContext = new MessageContextSkills();
MessageContextSkill mainSkillContext = new MessageContextSkill.Builder().userDefined(userDefinedContext)
		.build();
skillsContext.put("main skill", mainSkillContext);
MessageContext context = new MessageContext.Builder().skills(skillsContext).build();

context.skills().get("main skill").userDefined().put("yusuf", "cakmak");

int i = 0;
for (String msg : messages) {
	MessageInput input = new MessageInput.Builder().messageType("text").text(msg)
			.options(inputOptions).build();

	if(i > 0) {
		context.skills().get("main skill").userDefined().put("yusuf", null);
	}
	
	MessageOptions messageOptions = new MessageOptions.Builder(assistantId, sessionId)
			.context(context)
			.input(input)
			.build();

	MessageResponse response = service.message(messageOptions).execute().getResult();

	// Print the output from dialog, if any. Assumes a single text response.
	List<RuntimeResponseGeneric> responseGeneric = response.getOutput().getGeneric();
	if (responseGeneric.size() > 0) {
		if (responseGeneric.get(0).responseType().equals("text")) {
			System.out.println(responseGeneric.get(0).text());
		}
	}
	context = response.getContext();
	i++;
}
```

// We're done, so we delete the session.
DeleteSessionOptions deleteSessionOptions = new DeleteSessionOptions.Builder(assistantId, sessionId).build();
service.deleteSession(deleteSessionOptions).execute();`

**Screenshots**
In first iteration I put key "yusuf" and send MessageOptions as below:
![img_iteration_1](https://user-images.githubusercontent.com/3153146/73827217-31c6a500-4810-11ea-85ff-a875610b35dc.png)
and watson returns context as below:
![img_msg_response_context_iteration_1](https://user-images.githubusercontent.com/3153146/73827296-56228180-4810-11ea-88d2-77d358ba211a.png)
In second iteration I delete the key which I put it and MessageOptions as below:
![img_iteration_2_removed_context](https://user-images.githubusercontent.com/3153146/73827378-7e11e500-4810-11ea-8a7c-81ea711ee1a9.png)
But watson response returns context as below:
![img_msg_response_context_iteration_2](https://user-images.githubusercontent.com/3153146/73827410-8d912e00-4810-11ea-9c7d-9182504b6d6d.png)

**SDK Version**
<groupId>com.ibm.watson</groupId>
<artifactId>ibm-watson</artifactId>
<version>8.2.1</version>

**Additional information:**
- OS: Windows 10
- Which version of `Java` are you using?: 1.8

**Additional context**

**Comment by germanattanasio** [comment]
@yusufcakmakk you can't delete a key by just removing it from the context. You need to set the value to something like `false` or `0`. When you set you set it to `null` I think it's not added to the json you sent to the service.

Try setting it to something you know is not a valid value

**Comment by yusufcakmakk** [comment]
@germanattanasio We could do this in v1. As a result we couldn't delete any key from context. We can just replace its value, right?

**Comment by germanattanasio** [comment]
Yes It looks like you can remove the key anymore
