### ISSUE TITLE
The jar file is missing

### ISSUE THREAD

**Issue by AnwarBari** [watson-developer-cloud/java-sdk#1105]
JAR
Download the jar with dependencies here.
The link is broken!

**Comment by germanattanasio** [comment]
Fixed in https://github.com/watson-developer-cloud/java-sdk/commit/aa4d1a5d427e2b5e84d3316aa8e4e7eb2366eccc

**Comment by germanattanasio** [comment]
@all-contributors please add @germanattanasio for code, tests, and documentation

**Comment by germanattanasio** [comment]
@all-contributors please add @germanattanasio for code, tests, and documentation
