### ISSUE TITLE
speech_to_text: "%HESITATION"  && **** placeholder in response

### ISSUE THREAD

**Issue by premchand-algo** [watson-developer-cloud/java-sdk#1126]
In the speech_to_text we are getting these placeholder %HESITATION && ****

**Speech Response: 1.**
[
{
  "result_index": 35,
  "results": [
    {
      "alternatives": [
        {
          "confidence": 0.78,
          "transcript": "you can check that it's **** like that "
        }
      ],
      "final": true
    }
  ]
}

**Speech Response: 2.**
{
  "result_index": 10,
  "results": [
    {
      "alternatives": [
        {
          "confidence": 0.5,
          "transcript": "%HESITATION new plan the start go on is there any Venice dot com "
        }
      ],
      "final": true
    }
  ]
}

**Comment by germanattanasio** [comment]
Hi @premchand-algo, 

HESITATION and *** are part of the response, see: [Understanding recognition results](https://cloud.ibm.com/docs/speech-to-text?topic=speech-to-text-basic-response)
