### ISSUE TITLE
Latest release v8.5.0 contains Okio package vulnerable to CWE-327

### ISSUE THREAD

**Issue by juliankamil** [watson-developer-cloud/java-sdk#1127]
**Overview**
The latest Watson APIs Java SDK release v8.5.0 is reported by HCL AppScan to use an implementation of Okio package that is vulnerable to high-risk weaknesses described in **CWE-327: Use of a Broken or Risky Cryptographic Algorithm** (https://cwe.mitre.org/data/definitions/327.html).

**Expected behavior**
Release not to include the vulnerable Okio package implementation

**Actual behavior**
HCL AppScan reports CWE-327 as affecting the release

**How to reproduce**
Scan the code for vulnerabilities with HCL AppScan (https://www.hcltechsw.com/products/appscan) or similar tools to generate a vulnerability report

**Screenshots**
![2a212380-dd92-11ea-9fe7-72ec9951ab7b](https://user-images.githubusercontent.com/53741/90247521-c4ba4a80-de04-11ea-8db2-88095aa06295.png)
![ea0d7100-dd90-11ea-9741-68a0eec3f7e6](https://user-images.githubusercontent.com/53741/90247530-c84dd180-de04-11ea-8667-79cf1da73088.png)

**SDK Version**
v8.5.0

**Additional information:**
- OS: Ubuntu Linux
- IBM JDK 1.8.0_251

**Additional context**
None

**Comment by Jennifer-Hadley** [comment]
Hi stale bot. This is still an issue, unfortunately the development team does not know who to contact to get appropriate support.

**Comment by mediumTaj** [comment]
@kevinkowa can you look at this for the major release?

**Comment by kevinkowa** [comment]
Alright!

**Comment by mediumTaj** [comment]
hmm strange that our appscan reports didnt pick this up. we should look into this as well cc @Mikemosca

**Comment by mediumTaj** [comment]
We didn't catch this with our appscan since we don't scan the Core repo. We need to add the core repo to our scans.

Also opened up an issue in the core to address
https://github.com/IBM/java-sdk-core/issues/97

**Comment by mediumTaj** [comment]
Talking to @jorge-ibm we should move to the latest version of the java sdk core for the major release. 
> we're now on okhttp3 v4.9 which uses okio v2.7 https://square.github.io/okhttp/changelog/#version-480

@kevinkowa

**Comment by kevinkowa** [comment]
Fixed in the latest release
