### ISSUE TITLE
URL in DialogService.java still references -beta but credentials no longer use that -- get 403 Forbidden

### ISSUE THREAD

**Issue by wnm3** [watson-developer-cloud/java-sdk#113]
Trying a simple example as shown in the README.md for Java to list the dialog id's I get a 403 Access Forbidden error because my credentials use a different URL than is hard coded in DialogService.java on line 110.  By adding service.setEndPoint to the URL in my credentials I was able to get this fixed, but I believe a new jar file should be produced with the correct URL, and/or the examples shown should include the setEndPoint to ensure people setting their credentials in their code will have the correct one to match their username and password.

**Comment by germanattanasio** [comment]
Thanks for the feedback.
The examples that you were trying to use work if you use the code in `master`.
You can navigate the tags: https://github.com/watson-developer-cloud/java-sdk/tags to see the examples for previous releases like `java-wrapper-1.0.1`.

**Comment by germanattanasio** [comment]
fixed with the latest release
