### ISSUE TITLE
Proxy username password

### ISSUE THREAD

**Issue by sarahbacha** [watson-developer-cloud/java-sdk#1131]
We are trying the proxy with a discovery service on cloudpack
```
Authenticator proxyAuthenticator = new Authenticator() {
		@Override
		public Request authenticate(Route route, Response response) throws IOException {
			String credential = Credentials.basic(proxyUsername, proxyPassword);
			return response.request().newBuilder().header("Proxy-Authorization", credential).build();
		}
	};
```
```
HttpConfigOptions configOptions = new HttpConfigOptions.Builder()
                                  .disableSslVerification(true)
                                 .proxy(proxy)
				.proxyAuthenticator(proxyAuthenticator)
                                 .loggingLevel(HttpConfigOptions.LoggingLevel.HEADERS)
                                 .build();
```

```
authenticator = new BearerTokenAuthenticator(discoveryBearerToken);
service = new Discovery(discoveryVersionDate, authenticator);
service.configureClient(configOptions);
```

And getting the following error:
**type definition error: [simple type, class com.ibm.cloud.sdk.core.http.Headers]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class com.ibm.cloud.sdk.core.http.Headers and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.ibm.cloud.core.service.exception.ServiceResponseException[\"Headers\"])**

**_Using it with the Tone Analyzer works with **_@Autowire_**  but we could not do the same with Discovery since Bearer Token is not working we had to manually initialize the service instance_**

**Comment by hlewis910** [comment]
i am having a similar issue as above.

**Comment by sarahbacha** [comment]
Using it with the Tone Analyzer works with **_@Autowire_**  but we could not do the same with Discovery since Bearer Token is not working we had to manually initialize the service instance

**Comment by kevinkowa** [comment]
Hi @sarahbacha, can you provide more information (sdk version, etc)?

**Comment by sarahbacha** [comment]
Hello @kevinkowa  
		<dependency>
			<groupId>com.ibm.watson</groupId>
			<artifactId>discovery</artifactId>
			<version>8.6.1</version>
		</dependency>
and as well we tried it 8.6.0
As for discovery we are using V1

**Comment by padamstx** [comment]
Hi @sarahbacha , could you please include the stacktrace that you see when the error occurs?   The Java core library doesn't use jackson for serialization/deserialization so I'm a little curious how jackson is involved here.  I suspect that you are using it within your application.   Anyhow, a stacktrace and any other details you can offer with respect to the point at which the error is occurring would help in diagnosis.
Thanks!

**Comment by sarahbacha** [comment]
hello @padamstx  I just emailed you the details, thank you!

**Comment by padamstx** [comment]
Hi Sarah, I've been working with Kevin for a bit on this issue and I noticed this in the error message that you posted in your initial problem report:
```
through reference chain: com.ibm.cloud.core.service.exception.ServiceResponseException["Headers"]
```
This leads me to believe that there was an attempt to serialize an instance of ServiceResponseException.   The only way that would occur (I think) is if your server side code invoked an operation in the Java SDK that resulted in an exception being thrown (all exceptions thrown by the java core are subclasses of ServiceResponseException), and then simply returned that exception as the response back to the springboot framework.    I don't think that would really ever work, to be honest.  Probably a better approach would be for you to catch any exceptions that occur when you call SDK operations, then use that exception to construct a suitable error response that can then be sent back to the original client.

**Comment by kevinkowa** [comment]
Hi @sarahbacha, 

What HTTP version are you using?  1.0 is not allowed. 
Also, What cluster/region is this?

**Comment by sarahbacha** [comment]
okhttp3
us-south

**Comment by kevinkowa** [comment]
Hi @sarahbacha, 

I noticed that in your code you use proxyAuthenticator for Discovery but not for Tone Analyzer.
The problem from my point of view looks like it's related to your proxy. We have no logs that indicate that you received a 505 status code. 
Also, that's the okhttp library version, not the actual http version.

You said that Tone Analyzer works, one thing to try out is to get rid of the proxyAuthenticator on Discovery to mimic the code of the Tone Analyzer and check if that still give the same status code

**Comment by sarahbacha** [comment]
It seems that was the issue!
Thank you!
