### ISSUE TITLE
[Speech To Text] Interim results set to true but doesn't work

### ISSUE THREAD

**Issue by JxSun** [watson-developer-cloud/java-sdk#1133]
**Overview**
Set the `interimResults` field of `RecognizerOptions.Builder` to true but still can't receive non-final results. Just similar to https://github.com/watson-developer-cloud/java-sdk/issues/1005.

**Expected behavior**
When `interimResults` is true, the client app should be able to continuously receive non-final results while users are speaking.

**Actual behavior**
The Java SDK won't give non-final results. The only way to receive (final) results is to terminate the audio stream.

**How to reproduce**
It can be 100% reproduced by following the sample code of https://github.com/watson-developer-cloud/java-sdk/blob/master/examples/src/main/java/com/ibm/watson/speech_to_text/v1/MicrophoneWithWebSocketsExample.java#L56

**SDK Version**
Java SDK 8.6.1

**Comment by JxSun** [comment]
Here's my PR: https://github.com/watson-developer-cloud/java-sdk/pull/1134

**Comment by kevinkowa** [comment]
Thank you @JxSun! We merged your PR!

**Comment by mediumTaj** [comment]
So one of the issues here is that the async recognize operations does not support those properties while the websockets do. Both operations share the same options model. For the major release we should look into splitting the options model into `RecognizeOptions` and `RecognizeWithWebsocketOptions` with the latter containing the missing properties.

@kevinkowa
