### ISSUE TITLE
Please provide a way to get an assigned client id other than calling converse

### ISSUE THREAD

**Issue by wnm3** [watson-developer-cloud/java-sdk#114]
I realize we can assign a client id of our own, and we can have one assigned when we call converse if the parameter map doesn't contain one, however, the javadoc for updateProfile states it can be called without a clientId but the code tests for null and will complain. Ideally a different signature in Java with just the dialog id and namevalue list could assign and return a unique client id.

The reason this is needed is, we want to set up our profile before having the conversation begin so it can reference things like the client's name...

What javadoc claims:
Updates a dialog profile with a list of `NameValue` properties. If `clientId` is not specified a new clientId is generated. Profile variables are case sensitive.

What java does at line 412 in dialog service:
```
if (clientId == null)
    throw new IllegalArgumentException("clientId can not be null");
```
Alternatively, you could reintroduce the init chat API

**Comment by germanattanasio** [comment]
Thanks for reporting this. I've fixed the issue and it will be included in the v2.0.0 release tomorrow.
