### ISSUE TITLE
Please specify versions

### ISSUE THREAD

**Issue by tbrodbeck** [watson-developer-cloud/java-sdk#1141]
Hey I wanted to install this as recommended with `gradle assemble`
But I got a variety of errors like `Could not initialize class org.codehaus.groovy.runtime.InvokerHelper`

This is probably from a version conflict. (according to https://github.com/gradle/gradle/issues/12599 for example)

Can you maybe specify which version of Gradle and Java are supported and tested?

I have tried with Java 15, Gradle 6 (both latest) - then Java 1.8 and Gradle 5. But I could not find a working combination yet.

**Comment by kevinkowa** [comment]
Hey @tbrodbeck sorry for the late response, try using the version of `4.0.2` for gradle and `java 1.8`
