### ISSUE TITLE
[Watson-assistant] Context variables passed from client does not work

### ISSUE THREAD

**Issue by YamirL** [watson-developer-cloud/java-sdk#1154]
**Overview**
I have configured an watson skill that have a node which responds a greeting using the context variable "username". Response configured within node is "Hi $username! How can I help you?"

When I try it out from assistant's configurator, setting the value "Alice" for username context variable I have the result "Hi Alice! How can I help you?" what is ok.

I tried to do same from a Java application, however passed variable is not used by assistant. I followed example in documentation [Assistant v2](https://cloud.ibm.com/apidocs/assistant/assistant-v2?code=java#message) and [assistant-api-client-get-context](https://cloud.ibm.com/docs/assistant?topic=assistant-api-client-get-context).

**Expected behavior**
Watson assistant must take context variable defined from client application and replace its value where variable is used within node response.

**Actual behavior**
Apparently variable is not recognized, so its value is null. I'm having following response:

```{
  "output": {
    "generic": [
      {
        "response_type": "text",
        "text": "Hi ! How can I help you?"
      }
    ],
    "intents": [
      {
        "intent": "SayHi",
        "confidence": 1.0
      }
    ],
    "entities": []
  },
  "context": {
    "global": {
      "system": {
        "user_id": "my_user_id",
        "turn_count": 1
      },
      "session_id": "d72daecc-b688-49c9-b6cc-5b4138af66c0"
    },
    "skills": {
      "main skill": {
        "user_defined": {
          "username": "Alice"
        }
      },
      "dialog-dtmf47": {
        "system": {}
      }
    }
  }
}
```

**How to reproduce**

- Configure dialog node that responds using a user defined context variable within response message.
- Code snippet:
```java
Authenticator authenticator = new IamAuthenticator(API_KEY);
Assistant service = new Assistant(API_VERSION, authenticator);
service.setServiceUrl(ASSISTANT_URL);

MessageInputOptions inputOptions = new MessageInputOptions.Builder()
    .returnContext(true)
    .build();

MessageInput input = new MessageInput.Builder()
    .messageType("text")
    .text("Hello")
    .options(inputOptions)
    .build();

// create global context with user ID
MessageContextGlobalSystem system = new MessageContextGlobalSystem.Builder()
    .userId("my_user_id")
      .build();
 
MessageContextGlobal globalContext = new MessageContextGlobal.Builder()
    .system(system)
    .build();

Map<String, Object> userDefinedContext = new HashMap<>();
userDefinedContext.put("username", "Alice");

MessageContextSkill mainContextSkill =  new MessageContextSkill
    .Builder()
    .userDefined(userDefinedContext)
    .build();

Map<String, MessageContextSkill> skillsContext = new HashMap<>();
skillsContext.put("main skill", mainContextSkill);

MessageContext context = new MessageContext.Builder()
    .global(globalContext)
    .skills(skillsContext)
    .build();   

CreateSessionOptions sessionOptions = new CreateSessionOptions.Builder(ASSISTANT_ID).build();    
SessionResponse sessionResponse = service
    .createSession(sessionOptions)
    .execute()
    .getResult();

MessageOptions messageOptions = new MessageOptions.Builder()
    .assistantId(ASSISTANT_ID)
    .sessionId(sessionResponse.getSessionId())
    .input(input)
    .context(context)        
    .build();

MessageResponse response = service.message(messageOptions).execute().getResult();
System.out.println(response);
```

**Screenshots**

***_Configuration_***

![Config](https://user-images.githubusercontent.com/46688239/111088014-1047ea80-84f3-11eb-9081-6db374f2bf1b.png)

***_Results from watson cloud_***

![TryItOut](https://user-images.githubusercontent.com/46688239/111088009-07efaf80-84f3-11eb-9a0d-0b5acb7fe07e.png)

***_Results from java application_***

![JavaResult](https://user-images.githubusercontent.com/46688239/111088152-cc091a00-84f3-11eb-80a9-83c5235499a5.png)

**SDK Version**
9.0.2

**Additional information:**
- OS: Windows
- Java version: 1.8

**Comment by kevinkowa** [comment]
Hi @YamirL! This is working on my side, can you verify that you are using the correct assistant id?

**Comment by YamirL** [comment]
I verified assistant id and it is correct, however I found that skill version was incorrect. I updated to latest skill version and it works correctly.
