### ISSUE TITLE
Deserialization target class for discriminator value: search

### ISSUE THREAD

**Issue by kevinkowa** [watson-developer-cloud/java-sdk#1204]
**Overview**
Calling log functions that contain both v1 & v2 responses causes an error if it contains an output type not available in v1 such as search which is not available in v1. This creates an issue with the de-serialization of the object since that is not available in v1.

RuntimeResponseGenericRuntimeResponseTypeSearch is not available in Assistant v1.

Follow up for https://github.com/IBM/java-sdk-core/issues/167

**Comment by apaparazzi0329** [comment]
Closing due to age. If this is still an issue please feel free to reopen this issue and I will address it promptly
