### ISSUE TITLE
ibm.sdk-core bump for gson fix

### ISSUE THREAD

**Issue by abajzat** [watson-developer-cloud/java-sdk#1210]
Hi. Not really a bug, but rather a question/request.  We're encountering a `java.lang.NoClassDefFoundError: com/google/gson/internal/reflect/ReflectionAccessor` because of gson:2.8.9. I see this is a transitive dependency coming from java-sdk-core, and that it's been updated to `gson:2.9.0`. See this issue https://github.com/IBM/java-sdk-core/issues/168. 

Can we bump java-sdk-core to `9.15.5` ? We're currently not able to stick with `gson:2.8.9` because of other requirements to use `gson:2.9.0`. 

Thanks!

**Comment by manish-bansal** [comment]
Really need this one please release new version.

**Comment by apaparazzi0329** [comment]
Release 10.1 of the java-sdk comes with core version 9.17.3 so this issue should be resolved. Feel free to reopen this issue if the issue persists
