### ISSUE TITLE
Add new smart_formatting_version parameter to RecognizeOptions for Speech-to-text SDK 

### ISSUE THREAD

**Issue by manojsingh101** [watson-developer-cloud/java-sdk#1222]
A new parameter `smart_formatting_version` was added to Speech-to-text API. The Java SDK needs to be updated to expose this parameter in SDK in `RecognizeOptions`. 
[https://github.com/watson-developer-cloud/java-sdk/blob/master/speech-to-text/src/[…]va/com/ibm/watson/speech_to_text/v1/model/RecognizeOptions.java](https://github.com/watson-developer-cloud/java-sdk/blob/master/speech-to-text/src/main/java/com/ibm/watson/speech_to_text/v1/model/RecognizeOptions.java)

New parameter : **smart_formatting_version - Integer type**

This is an optional parameter to be used when specifying `smart_formatting=true/false`
https://github.com/watson-developer-cloud/java-sdk/blob/5918c8af77cf8d14e7f59ac7c3b798b14e75665b/speech-to-text/src/main/java/com/ibm/watson/speech_to_text/v1/model/RecognizeOptions.java#L199
https://github.com/watson-developer-cloud/java-sdk/blob/5918c8af77cf8d14e7f59ac7c3b798b14e75665b/speech-to-text/src/main/java/com/ibm/watson/speech_to_text/v1/model/RecognizeOptions.java#L481

Sample of CURL command using the new parameter: https://cloud.ibm.com/docs/speech-to-text?topic=speech-to-text-formatting#smart-formatting-example

**Comment by apaparazzi0329** [comment]
This parameter is being added with the next release scheduled for next week Monday
