### ISSUE TITLE
Add new speech_begin_event parameter to RecognizeOptions for Speech-to-text SDK

### ISSUE THREAD

**Issue by manojsingh101** [watson-developer-cloud/java-sdk#1225]
A new parameter `speech_begin_event` was added to Speech-to-text API. The STT SDK needs to be updated to expose this parameter in SDK in RecognizeOptions.

New parameter : **speech_begin_event** - Data type = **boolean**

This is an optional parameter. When `speech_begin_event =true`, the request returns a `SpeechActivity` response object. e.g. `{'SpeechActivity': {'begin': 1.76}}`

**Comment by apaparazzi0329** [comment]
There is a release coming out this week where this parameter will be included

**Comment by apaparazzi0329** [comment]
Version 13.0.0 has been released and includes the `speech_begin_event` parameter
