### ISSUE TITLE
Watson STT Java SDK: "smart_formatting_version" parameter should be "integer", not boolean

### ISSUE THREAD

**Issue by marconoel** [watson-developer-cloud/java-sdk#1226]
Related to issue https://github.com/watson-developer-cloud/java-sdk/issues/1222 which introduced the new smart_formatting_version parameter.

**Overview**
Customer is trying to use `smart_formatting_version` with value "2" to enable it and it does not work because in the SDK, it is expecting a "boolean" value, not "integer".

Also, customer is not able to use both `smart_formatting` and `smart_formatting_version` through websockets

NOTE: Need to check if this issue is also present in other SDKs (Python, Node, NET, etc)

**Expected behavior**
- `smart_formatting_version` should be **INTEGER** (NOT BOOLEAN)
- `smart_formatting` should remain **BOOLEAN**
- Customer should be able to use both `smart_formatting` and `smart_formatting_version` through websockets
- When a customer sets `smart_formatting` to "true" and `smart_formatting_version` with value "2" under websockets, the audio file or stream, should return formatted transcripts.

**Actual behavior / How to reproduce**
Customer sets `smart_formatting_version` with value "2" per our documentation but Java code does not compile because it's expecting a boolean value (true/false).

Customer sets `smart_formatting_version` with value "true". Java code compiles fine with no issue but when he runs the code with audio, STT service returns an error that it's an invalid parameter - STT service expects an "integer" (0,1,2) to work.

**SDK Version**
12.0.0

**Additional information:**
- OS: Windows, Mac, LInux
- Which version of `Java` are you using?

**Comment by marconoel** [comment]
More information from customer:

- **RecognizeOptions** class needs the **smartFormattingVersion** to be an Integer instead of Boolean. Class Github: https://github.com/watson-developer-cloud/java-sdk/blob/master/speech-to-text/src/main/java/com/ibm/watson/speech_to_text/v1/model/RecognizeOptions.java#L200
- **RecognizeWithWebsocketsOptions** class needs the **smartFormattingVersion** parameter added. Class Github: https://github.com/watson-developer-cloud/java-sdk/blob/master/speech-to-text/src/main/java/com/ibm/watson/speech_to_text/v1/model/RecognizeWithWebsocketsOptions.java
- **SpeechToText** class needs its **recognizeUsingWebSocket** method updated to add all the **RecognizeWithWebsocketsOptions** parameters (including the newly added **smartFormattingVersion**) as query parameters. Class Github: https://github.com/watson-developer-cloud/java-sdk/blob/master/speech-to-text/src/main/java/com/ibm/watson/speech_to_text/v1/SpeechToText.java#L206

**Comment by apaparazzi0329** [comment]
This appears to be an oversight from the latest release. I will release a patch version to address this issue by EOD
