### ISSUE TITLE
Make a fresh checkout build cleanly

### ISSUE THREAD

**Issue by mfulgo** [watson-developer-cloud/java-sdk#128]
It would be nice if a fresh clone of the repo actually passed all of the non-integration tests. Currently, most of the non-integration tests also fail because of missing config settings, such as `mock.server.port` and `mock.server.host`.

**Comment by germanattanasio** [comment]
Good Idea, I'm going to work on having a way to only run unit tests also

**Comment by nfriedly** [comment]
BTW, the node-sdk works around this by only running the integration tests if there is a config file present: https://github.com/watson-developer-cloud/node-sdk/blob/master/test/test.integration-all-services.js

**Comment by germanattanasio** [comment]
I've fixed the issue by using the maven `failsafe` plugin.
I've also updated travis so that integration tests are only runned for non pull requests as with the node-sdk.

Unit tests:

```
mvn test
```
Integration tests:

```
mvn verify
```
