### ISSUE TITLE
[PI] ContentItem Date Serialization

### ISSUE THREAD

**Issue by jollyrubber** [watson-developer-cloud/java-sdk#132]
The Date properties of a Content item are getting serialize to JSON in a "yyyy-MM-dd'T'HH:mm:ss.SSS" format, when it should be in milliseconds since midnight 1/1/1970 UTC. This results in a "Invalid JSON input at line x, column y" error message from the personality profile service.

**Comment by germanattanasio** [comment]
Good catch. I will work on this and hopefully it will be fixed and released next Friday

**Comment by germanattanasio** [comment]
fixed
