### ISSUE TITLE
Speech Recognition Grammar Specification

### ISSUE THREAD

**Issue by birkanu** [watson-developer-cloud/java-sdk#137]
Hi, 

Is there any way to provide a [grammar](https://en.wikipedia.org/wiki/Speech_Recognition_Grammar_Specification) for the speech that is being recognized? Most speech recognizers allow for this functionality. 

Thanks,
Birkan

**Comment by daniel-bolanos** [comment]
Hello @birkanu , not yet, but this is a feature that we are working on. 

Dani

**Comment by germanattanasio** [comment]
I'm closing this since it's not a problem in the java-sdk. The take away is that the service is working on this and will be available in a future release
