### ISSUE TITLE
[speech-to-text] RecognizeOptions not functioning properly

### ISSUE THREAD

**Issue by PranavSathy** [watson-developer-cloud/java-sdk#143]
I am running the `java-sdk` version `2.3.0`, added to my project via SBT.  The following code is in Scala:

```
    val service = new SpeechToText()
    service.setUsernameAndPassword("{username}", "{password}")

    var options = new RecognizeOptions()
    options.wordConfidence(true)
           .timestamps(true)
           .model("en-US_BroadbandModel")
           .maxAlternatives(1)
           .inactivityTimeout(-1)

    val audio = new File(s"/var/www/audio/$video_id.wav")
    val transcript = service.recognize(audio, HttpMediaType.AUDIO_WAV, options)

    println(transcript)
```

This returns the appropriate transcript for my audio, but it is not returning word confidence or timestamps at all. Does anyone know why?

**Comment by PranavSathy** [comment]
On further investigation it seems like there is no support within the TTS code for word_confidence and timestamps?

**Comment by daniel-bolanos** [comment]
STT has word_confidence and timestamps, TTS does not, at some point we hope to provide timestamps for TTS but not ready yet. Confidence for TTS I'm not sure what it would mean.

thank you

Dani

**Comment by PranavSathy** [comment]
Hi @daniel-bolanos , I apologize I editted my message, I meant STT. There is no serializer for word_confidence and timestamp JSON response from the Watson API. Like it sends the headers all correct, but they are not stored within any of the classes.

**Comment by daniel-bolanos** [comment]
Hello @PranavSathy , it seems like the code is incomplete them, sorry about that. Can you add the fix and make a pull request? you seem to have a good understanding of the code.

thank you :)

**Comment by PranavSathy** [comment]
Hi Daniel! I will try my best :) I am trying to ensure I understand it myself haha!

**Comment by PranavSathy** [comment]
PR #148 Addressed this issue
