### ISSUE TITLE
[speech-to-text] Investigate the use if WebSocket

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/java-sdk#15]
HI @daniel-bolanos I was thinking we can provide support for WebSockets in the wrapper by adding an existing library and handling the authorization using the `authorization` service. 
What do you think?

We should:
- [x] Find a websocket library
- [x] Design a listener/observer pattern to model websockets

**Comment by daniel-bolanos** [comment]
Hi @germanattanasio, I agree, I already have a working java client for the STT service, I think I pointed you to it some time ago. We can reuse that and add the token authentication part.

**Comment by germanattanasio** [comment]
Why don't you move that code to your github account and I will take a look at it

**Comment by germanattanasio** [comment]
@daniel-bolanos can you help me with this: https://gist.github.com/germanattanasio/275c6abab90b042f4925 I'm trying to write an example with websockets.

You will need to clone this repo and create a file with that content

**Comment by birkanu** [comment]
I am having the same problem. Each time I try connecting to the service, my connection is closed. I am pretty sure I am using the correct API endpoints to get a token and then connect to the WebSocket server. Can there be an SSL issue?

**Comment by daniel-bolanos** [comment]
Hello @birkanu and @rathnaum , what is the error message that you get? Can you please try the Python or Ruby WebSocket clients while we solve this issue? 

https://github.com/watson-developer-cloud/speech-to-text-websockets-python
https://github.com/watson-developer-cloud/speech-to-text-websockets-ruby

thank you

**Comment by birkanu** [comment]
Here is what's printed out on the console:

```java
Transcript using WebSockets
Closed connection.
CONNECTED: false
HERE: false
java.nio.channels.NotYetConnectedException
	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:481)
	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:458)
	at org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:176)
	at samples.IBMSpeechRecognitionSample2.transcriptUsingWebSockets(IBMSpeechRecognitionSample2.java:188)
	at samples.IBMSpeechRecognitionSample2.main(IBMSpeechRecognitionSample2.java:86)

```

**Comment by rathnaum** [comment]
I got the exact same error message too. Cheers.

Date: Fri, 4 Dec 2015 10:13:24 -0800

**Comment by birkanu** [comment]
I am not sure if this will help you, but I tried opening a WebSocket connection using [Tyrus](https://tyrus.java.net/documentation/1.12/user-guide.html) which is a reference implementation of websockets in Java. This time I got a `Handshake Error`, caused by the following reason: `Response code was not 101: 400`. There must be something wrong with the SSL Configuration.

**Comment by birkanu** [comment]
@daniel-bolanos  and @germanattanasio, any updates on this?

**Comment by germanattanasio** [comment]
I'm working in other things now, will probably have some time to look at this on Wednesday. 

If you have some time please look at the documentation and the ruby and python samples in this organization. You can learn how to use the websocket api and fix the sample by the time I start working on this again.

**Comment by germanattanasio** [comment]
We decided to use https://github.com/TakahikoKawasaki/nv-websocket-client. It's only 60kb and works in Android.

**Comment by germanattanasio** [comment]
Fixed in https://github.com/watson-developer-cloud/java-sdk/releases/tag/java-sdk-2.6.0

**Comment by rathnaum** [comment]
Is there any C# .Net SDK for speech to text service?

**Comment by daniel-bolanos** [comment]
Hello @rathnaum , there is not yet, but all you need is a websockets library for .NET. Please take a look at this post: https://developer.ibm.com/answers/questions/211086/calling-the-speech-to-text-service-from-a-c-net-ap.html
