### ISSUE TITLE
[tradeoff-analytics] missing getter\setter for status_cause on Solution

### ISSUE THREAD

**Issue by amiddavid** [watson-developer-cloud/java-sdk#150]
https://github.com/watson-developer-cloud/java-sdk/blob/master/src/main/java/com/ibm/watson/developer_cloud/tradeoff_analytics/v1/model/Solution.java
misses a getter\setter for status_cause

**Comment by amiddavid** [comment]
created a PR 
https://github.com/watson-developer-cloud/java-sdk/pull/154

**Comment by amiddavid** [comment]
now PR https://github.com/watson-developer-cloud/java-sdk/pull/155 on dev, I hope.

**Comment by germanattanasio** [comment]
Fixed in the latest release
