### ISSUE TITLE
[personality-insights] NullPointerException when serializing a Profile with Jackson

### ISSUE THREAD

**Issue by l2fprod** [watson-developer-cloud/java-sdk#151]
Hello,

I want to persist the Personality Insights Profile in Cloudant with Ektorp which uses Jackson. Jackson throws NullPointerException when serializing a Trait:

```
	... 9 more
Caused by: java.lang.NullPointerException
	at com.ibm.watson.developer_cloud.personality_insights.v2.model.Trait.getRawScore(Trait.java:115)
```

Debugging the rawScore object is null, thus the unboxing to "double" fails when getRawScore is called, leading to NPE

So is the use of Double a typo or is it on purpose? In in java-sdk/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v2/model/Trait.java:

```
  /** The raw sampling error. */
  @SerializedName("raw_sampling_error")
  private Double rawSamplingError;

  /** The raw score. */
  @SerializedName("raw_score")
  private Double rawScore;

  /** The sampling error. */
  @SerializedName("sampling_error")
  private double samplingError;
```

thanks.

**Comment by germanattanasio** [comment]
@l2fprod which version of the Java SDK are you using?

Regarding Double vs double. We are trying to use objects instead of primitive types.

`null` values are deserialized as `0.0` when using `double` and `null` when using `Double`.

Looks like we [have](https://github.com/watson-developer-cloud/java-sdk/blob/master/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v2/model/Trait.java) some `double` and `Double` in our `Trait.java` class.

I will be working on this.

**Comment by germanattanasio** [comment]
@l2fprod, the SDK uses `gson` so as a workaround you can serialize the profile doing something like:

```java
Profile profile = service.getProfile(options); // Call the service
String profileAsJson = GsonSingleton.getGson().toJson(profile);
```

**Comment by l2fprod** [comment]
For now, I workaround the issue by traversing the tree and settings the null values to 0, ugly but then I can use the POJO and nice features of Ektorp for CouchDB.

Whether you use double or Double in the model, I guess it is the "getter" that will need to be fixed. Either changing to return a "Double" or properly handling the null value to avoid NPE.

```
    new Trait().getRawSamplingError();
```
currently throws NPE.

**Comment by germanattanasio** [comment]
Fixed in the latest release

**Comment by l2fprod** [comment]
moved to 2.5. works perfectly! thank you!
