### ISSUE TITLE
[concept-insights] getConceptRelatedConcepts method does not support multiple source concepts

### ISSUE THREAD

**Issue by g-may** [watson-developer-cloud/java-sdk#163]
cURL and Node SDKs allow multple source concepts to be passed in the `concepts` query parameter at the following endpoint:
`/v2/{graph-id-path}/related_concepts`

The SDK currently uses 
`/v2/{concept-id-path}/related_concepts`
and is restricted to only one query concept

example request:
``` curl
curl -u "{username}":"{password}" -G -d "concepts=[\"/graphs/wikipedia/en-latest/concepts/IBM_Watson\",\"/graphs/wikipedia/en-latest/concepts/Business\"]&level=1&limit=2" "https://gateway.watsonplatform.net/concept-insights/api/v2/graphs/wikipedia/en-latest/related_concepts"
```

**Comment by germanattanasio** [comment]
I think the method you are looking for is `getGraphRelatedConcepts` which allows you to get the related concepts based on a given *Graph*
