### ISSUE TITLE
[language-translation] forced glossary, monolingual corpus or parallel corpus should be allowed more than one during model creation

### ISSUE THREAD

**Issue by RollinJin** [watson-developer-cloud/java-sdk#172]
In LanguageTranslation.java, it seems either forced glossary, monolingual corpus or parallel corpus can be specified.
Yet, it should be allowed to input more than one options during the model training. 
Such as train a new customized model with both forced glossary and parallel corpus

**Comment by germanattanasio** [comment]
@kcheat is this something the service support?

**Comment by melissamahoney3** [comment]
At this time you can only upload one glossary, but you can upload more than one parallel or monolingual corpus. For example, you can train a model with a glossary and two parallel corpora, but you can't train a model with two glossaries.

**Comment by RollinJin** [comment]
Thanks. I am not going to use more than two glossaries. 
A basic scenario is that when I try to create a customized model with one glossary and one parallel corpus. But it seems the parallel corpus is not used during the model creation. please check. Thanks.
