### ISSUE TITLE
setApiKey not there in class AlchemyLanguage 

### ISSUE THREAD

**Issue by akankshajain** [watson-developer-cloud/java-sdk#173]
Hello,

I tried to use Alchemy Language sample and I got compilation error in setApiKey method saying that method does not exist. On looking at AlchemyLanguage  I found that the method is really absent in this class.

Where exactly this method is defined?
```
AlchemyLanguage service = new AlchemyLanguage();
service.setApiKey("<api_key>");
```
Thanks.

**Comment by germanattanasio** [comment]
The method is defined in [`WatsonService.java`](https://github.com/watson-developer-cloud/java-sdk/blob/master/src/main/java/com/ibm/watson/developer_cloud/service/WatsonService.java#L296). 
Are you trying to compile the code in `master` or using the **jar** file?

**Comment by akankshajain** [comment]
Thanks. By mistake I had created a class with the same name "AlchemyLanguage" Hence it was trying to search for a method there itself. Issue is fixed. You can close the issue.
