### ISSUE TITLE
[visual-recognition] Cannot execute learning task : Could not train classifier. Verify there are at least 10 positive training images and 10 negative training images that are different from each other.

### ISSUE THREAD

**Issue by akankshajain** [watson-developer-cloud/java-sdk#175]
I am trying to create a classifier using java-sdk.  Here is the small code I have written. I have positive.zip and negative.zip in proper folder in my workspace. But still I get Could not train classifier.

Anything wrong with the zip file name or images names inside the folder or any of the locations of zips? Please help.

     System.out.println("Create a classifier with positive and negative images");
     File positiveImages = new File("src/main/resources/visual_recognition/positive.zip");
     File negativeImages = new File("src/main/resources/visual_recognition/negative.zip");
     
     VisualClassifier roads = service.createClassifier("roads", positiveImages, negativeImages);
     System.out.println(roads);

**Comment by akankshajain** [comment]
Most of the image files are in jpeg format with few in png format and names of the files are all different. Some long names some short.

**Comment by germanattanasio** [comment]
We have an [integration test](https://github.com/watson-developer-cloud/java-sdk/blob/master/src/test/java/com/ibm/watson/developer_cloud/visual_recognition/v2/VisualRecognitionIT.java#L90) that creates a classifier, test it and delete it so I don't know why you are getting that error. Can you please try again?

**Comment by akankshajain** [comment]
curl -u dXXXXXXXXXXXXXXXXX8:1S5XXXXXXj -X POST -F "positive_examples=@positive.zip" -F "negative_examples=@negative.zip" -F "name=roadsHack" "https://gateway.watsonplatform.net/visual-recognition-beta/api/v2/classifiers?version=2015-12-02"

Something wrong with the attached zip? Even curl doesn't work and gives same error.
[positive.zip](https://github.com/watson-developer-cloud/java-sdk/files/114467/positive.zip)

**Comment by germanattanasio** [comment]
I tried the test again and seems to be working. I think this was a hiphup in the service. I'm closing the issue but if you get the error again feel free to re-open it.

**Comment by YuningMiao** [comment]
Hi,
when I try to use curl to train and create a classifier, I got error code 400, cannot execute learning task: no classifier name given error, and here is my curl command 
`curl -u "0xxxxxxxxxxxxxxxxxxxxxxxxxxxx":"vxxxxxxxxxxxxx" \
     -X POST \
     -F "positive_examples=@bottle-positive.zip" \
     -F "negative_examples=@bottle-negative.zip" \
     -F "name=plasticbottle" \
     -k "https://gateway.watsonplatform.net/visual-recognition-beta/api/v2/classifiers?version=2015-12-02"`

**Comment by germanattanasio** [comment]
can you write this as a question in stackoverflow ? this is not related to the java-sdk
