### ISSUE TITLE
[speech-to-text] Android Audio Capture encoding issue/best practices 

### ISSUE THREAD

**Issue by shenybluemix** [watson-developer-cloud/java-sdk#179]
I am using 2.60 on Android for SpeechToText services. 

Use Case: capture the voice by Android MIC and use it as the input for SpeecToText. 

I am using MediaRecorder class of Android to do capture the audio. It looks the Audio Encoder of MediaRecorder does not support any format which Watson supports.   [http://developer.android.com/reference/android/media/MediaRecorder.AudioEncoder.html
](url)

Is there any easy way for Audio Encoding on Android to get the Audio format which is supported by Watson STT (FLAC/WAV/ogg)? 

Another STT SDK https://github.com/watson-developer-cloud/speech-android-sdk looks has a wrapper for Audio encoding to ogg but the AAR file is inconsistent.

**Comment by germanattanasio** [comment]
hi @shenybluemix this is supported in the [speech-android-sdk](https://github.com/watson-developer-cloud/speech-android-sdk). I saw you open an issue there so I will keep that open and work there instead of there.

**Comment by daniel-bolanos** [comment]
Hello @shenybluemix , please regenerate the aar from the code in the repository. The AAR is outdated.
