### ISSUE TITLE
[visual-recognition] Take URL as parameter

### ISSUE THREAD

**Issue by kaaron1** [watson-developer-cloud/java-sdk#181]
Currently some services only take an input stream, like VisualRecognition.classify, and some only take a file, like VisualInsights.getSummary. It would be great if all image related methods could take an image URL directly.

**Comment by germanattanasio** [comment]
The visual-recognition service will support URLs in the near future so I will wait until that happens

**Comment by germanattanasio** [comment]
Fixed in the next release
