### ISSUE TITLE
AlchemyDataNews.java enforces param 'return'

### ISSUE THREAD

**Issue by fmerici** [watson-developer-cloud/java-sdk#198]
Method 'getNewsDocument' enforces parameter 'return' while the Alchemy specs have 'return' as optional.
- i.e. I can query AlchemyDataNews API directly without passing parameter 'return'  but the Java SDK requires it.
- Alchemy specs: https://alchemyapi.readme.io/v1.0/docs/rest-api-documentation
- SDK implementation: 
"public DocumentsResult getNewsDocuments(Map<String, Object> parameters) {
``` 
   Validate.notNull(parameters.get(START), "start time cannot be null");
    Validate.notNull(parameters.get(END), "end time cannot be null");
    Validate.notNull(parameters.get(RETURN), "return cannot be null");"
```
Should the SDK match to the Alchemy specs?

**Comment by germanattanasio** [comment]
You are right. I can change that

**Comment by germanattanasio** [comment]
I just realized that if you don't specify `return` the output it's the document count. so I decided to add two methods to the `AlchemyDataNews` one that require returns and will return documents like
 ```
public DocumentsResult getNewsDocuments(Map parameters)
``` 
and one without `return` that will return the document count 
```
VolumeResult getVolume(final String start, final String end, final String timeSlice)
```
