### ISSUE TITLE
[alchemy-vision] Add support for text extraction

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/java-sdk#200]
POST /image/ImageGetRankedImageSceneText Identifies text in the POSTed image
GET /url/UrlGetRankedImageSceneText Identifies text in the URL

The documentation is: http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/alchemyvision/api/v1/#

**Comment by mishrasambit** [comment]
I tried this extending `com.ibm.watson.developer_cloud.service.WatsonService.`
and using the following code snippet, but I am getting error response
SEVERE: https://gateway-a.watsonplatform.net/calls/image/ImageGetRankedImageSceneText?outputMode=json&imagePostMode=raw, status: 400, error:

```
public <T extends AlchemyGenericModel> T imageGetRankedImageSceneText(
			File image, Class<T> returnType) {
		final Map<String, Object> params = new HashMap<String, Object>();
		params.put("imagePostMode", "raw");
		params.put("outputMode", "json");
		
		final String path = "/image/ImageGetRankedImageSceneText";
		
		final RequestBuilder requestBuilder = RequestBuilder.post(path);
		requestBuilder.withBody(RequestBody.create(HttpMediaType.BINARY_FILE,image));
		for (final String param : params.keySet()) {
			requestBuilder.withQuery(param, params.get(param));
		}
        return executeRequest(requestBuilder.build(), returnType);
}
```

**Comment by germanattanasio** [comment]
You should try to update `AlchemyLanguage.java` not `WatsonService` and it should be pretty straitforward. 

In any case I'm planning on working on this this week.
