### ISSUE TITLE
DialogService fails to update profile unless updating specific profile variables

### ISSUE THREAD

**Issue by davismat** [watson-developer-cloud/java-sdk#201]
When I used the APIs to get the profile for a clientID, then try to update that profile, I get a 400 error:

status: 400, error: The name_values parameter specified does not properly specify the name value pairs for the profile

Here is some example code:

```
String dialogID = "xxxx" // email bug author for dialogID if required
Integer wdsID = 0; // email bug author for wdsID if required
Map<String, String> profileMap = dialogService.getProfile(dialogID, wdsID);
profileMap.put("user_name", "Fred Jones");
dialogService.updateProfile(dialogID, wdsID, profileMap);
```
The profileMap is successfully populated, and I can see the default value for the "user_name" profile variable. But the `updateProfile` method returns the error above.

I notice that if I retrieve the profile variables individually, such as:

`dialogService.getProfile(dialogID, wdsID, "user_name")`, and then update them lines 2-3 above, there is no error.

**Comment by germanattanasio** [comment]
I think this is a bug in the service. I coudn't reproduce the issue.
I updated an integration test to validate that `updateProfile` is updating the variable in the server.

See [this](https://github.com/watson-developer-cloud/java-sdk/blob/master/src/test/java/com/ibm/watson/developer_cloud/dialog/v1/DialogServiceIT.java#L108-L113)


```java
Map<String, String> profile = service.getProfile(dialogId, c.getClientId());
String variable = profile.keySet().iterator().next();
profile.put(variable, "foo"); // update value to 'foo'
service.updateProfile(dialogId, c.getClientId(), profile);
    
assertEquals(service.getProfile(dialogId, c.getClientId()).get(variable), "foo");
assertEquals(service.getProfile(dialogId, c.getClientId(), variable).get(variable), "foo");
```
