### ISSUE TITLE
CredentialUtils for username/passwords too

### ISSUE THREAD

**Issue by shikida** [watson-developer-cloud/java-sdk#202]
Hi

CredentialUtils currently retrieves the apiKey for alchemy.

I think with just a little change, it could also retrieve username and password as well from VCAP_SERVICES

That would be great

thx

**Comment by germanattanasio** [comment]
Please check https://github.com/watson-developer-cloud/java-sdk/blob/master/src/main/java/com/ibm/watson/developer_cloud/util/CredentialUtils.java#L87

We are currently using the VCAP_SERVICES

**Comment by shikida** [comment]
for username/password, this function retrieves Credentials.basic(username, password). I can't use the result of this function in NaturalLanguageClassifier.setUsernameAndPassword(user,pass) for example

**Comment by germanattanasio** [comment]
use `setApiKet` instead
