### ISSUE TITLE
Unsupported text language on Alchemy API

### ISSUE THREAD

**Issue by gcolmen** [watson-developer-cloud/java-sdk#204]
Hello, I'm sending this simple phrase to Alchemy API (getRelations):

"delete laboratory record"

And getting this error back:

{"error":"unsupported-text-language", "code":400}

There aren't symbols in the string, or non-printable characters. I've tried with several other phrases with no problem. But I need this one!.

What could it be? Or how can I solve it?

Thanks in advance!

Giancarlo

**Comment by germanattanasio** [comment]
I don't think this is related to the java-sdk. Did you try with a curl command to see if the phrase was working ?

**Comment by gcolmen** [comment]
Thank you for your answer German. I tried that and I've received the same error, but I've noticed that Alchemy is detecting the language as "romanian", and that's why I'm getting the error. I'm now sending the request specifying the language as English and it's working perfectly.

Thanks again.

Giancarlo

**Comment by germanattanasio** [comment]
No problem, I'm glad it's working

**Comment by buzea** [comment]
>  I'm now sending the request specifying the language as English and it's working perfectly.
How did you manage this? I'm having a hard time finding out.

**Comment by max-vogler** [comment]
I think @gcolmen is referring to the `AlchemyLanguage.setLanguage()` method.

```java
final AlchemyLanguage service = new AlchemyLanguage();
service.setLanguage(LanguageSelection.ENGLISH); // <--

final Map<String, Object> params = new HashMap<String, Object>();
params.put(AlchemyLanguage.TEXT, "delete laboratory record");
final SAORelations relations = service.getRelations(params).execute();
```

**Comment by buzea** [comment]
I must pe using an older version of the SDK, because I do not dispose of the `setLanguage()` method. I have found an answer on another thread however. I used the `params.put("language", "english");` approach.

Thank you for your support!

**Comment by gcolmen** [comment]
Yes, indeed I was using params.put("language", "english"); And later they added setLanguage method.

**Comment by mauroAntonio** [comment]
guys... unfortunately the system behave is not so linear. happens that the system works correctly for a series of call and goes in error at the arriving of the n request. the only way to overcome such problem is to force the flushing of the alchemy_options. waiting for something less coarse, pls force such options paying attention to the channel/protocol in use. mauro
