### ISSUE TITLE
Doubt about Alchemy DataNews dates

### ISSUE THREAD

**Issue by shikida** [watson-developer-cloud/java-sdk#212]
doc says

```

> Example: Get 7 documents between Friday 28th August 2015 and Friday 4th September 2015.
> 
> AlchemyDataNews service = new AlchemyDataNews();
> service.setApiKey("<api_key>");
> 
> Map<String, Object> params = new HashMap<String, Object>();
> 
> String[] fields =
>     new String[] {"enriched.url.title", "enriched.url.url", "enriched.url.author",
>         "enriched.url.publicationDate", "enriched.url.enrichedTitle.entities",
>         "enriched.url.enrichedTitle.docSentiment"};
> params.put(AlchemyDataNews.RETURN, StringUtils.join(fields, ","));
> params.put(AlchemyDataNews.START, "1440720000");
> params.put(AlchemyDataNews.END, "1441407600");

But how these numbers were calculated?

for example

		Calendar d = new GregorianCalendar();
		d.set(Calendar.YEAR, 2015);
		d.set(Calendar.MONTH, Calendar.AUGUST);
		d.set(Calendar.DAY_OF_MONTH, 28);
		d.set(Calendar.HOUR, 0);
		d.set(Calendar.MINUTE, 0);
		d.set(Calendar.SECOND, 0);
		d.setTimeZone(TimeZone.getTimeZone("GMT"));
		System.out.println(d.getTimeInMillis());

gives me 

1440763200135 (millis) = 

1440763200 secs
1440720000 = ?

System.out.println(new Date(1440720000 * 1000)); 

gives me 

Thu Jan 22 22:25:55 BRT 1970

?

**Comment by shikida** [comment]
I think I've got it.
Using the query builder

http://querybuilder.alchemyapi.com/builder?hiddenArrowClass=arrow-example-1&inputDateRange=2016%2F03%2F07+00%3A00+-+2016%2F03%2F14+23%3A00&inputEntity=IBM&selectEntityType=company&selectSentiment=any&selectCategory=technology+and+computing&selectArticlePart=title&inputCount=25&return_title=0&return_publicationData=0&return_docSentiment=1&querySubmit=

it generates

https://access.alchemyapi.com/calls/data/GetNews?apikey=YOUR_API_KEY_HERE&return=enriched.url.title,enriched.url.publicationDate,enriched.url.enrichedTitle.docSentiment&start=1457308800&end=1457996400&q.enriched.url.enrichedTitle.entities.entity=|text=IBM,type=company|&q.enriched.url.enrichedTitle.taxonomy.taxonomy_.label=technology%20and%20computing&count=25&outputMode=json

so March 3rd 2016 = 1457308800

and

Calendar d = new GregorianCalendar();
		d.set(Calendar.YEAR, 2016);
		d.set(Calendar.MONTH, Calendar.MARCH);
		d.set(Calendar.DAY_OF_MONTH, 6);
		d.set(Calendar.HOUR, 0);
		d.set(Calendar.MINUTE, 0);
		d.set(Calendar.SECOND, 0);
		d.setTimeZone(TimeZone.getTimeZone("GMT-12"));
		System.out.println(d.getTimeInMillis());

gives me

1457308800945

**Comment by germanattanasio** [comment]
Alchemy uses unix timestamp. See http://www.unixtimestamp.com/
