### ISSUE TITLE
[alchemy-vision] Number format exception when there is no tag returned by the API

### ISSUE THREAD

**Issue by l2fprod** [watson-developer-cloud/java-sdk#216]
ImageKeywords for this image:
![blank](https://cloud.githubusercontent.com/assets/12746550/13875173/a08c9562-ecfc-11e5-9205-c51fcf178e4f.jpg)

will produce this output:
```json
{
    "status": "OK",
    "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
    "url": "",
    "totalTransactions": "5",
    "imageKeywords": [{
        "text": "NO_TAGS",
        "score": ""
    }]
}
```
the GSON parsing is not working in this case when trying to parse the empty string into a Double:

```
java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.google.gson.stream.JsonReader.nextDouble(JsonReader.java:925)
```

A custom typeadapter for Gson might solve the issue. Although I would put the root issue in Alchemy. This NO_TAGS is really not a good pattern, they could just return an empty array as they do with faces. I've submitted a ticket in Bluemix support to Alchemy too.

**Comment by germanattanasio** [comment]
@l2fprod  I talked to @zwalchuk and he will work with Alchemy vision to see what they can do.

**Comment by germanattanasio** [comment]
I ended up writing a custom deserializer/serializer and checks the case when `score: ""` and remove the `NO_TAGS` from the keyword list
