### ISSUE TITLE
Move to okhttp3 and switch to use MockWebServer

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/java-sdk#217]
if we switch to okhttp3 we will be able to use `MockWebServer` to mock our services. We will probably remove the current library we use to for unit tests.

**Comment by germanattanasio** [comment]
from: @jpetitto 

A quick naive implementation without having to use OkHttp3 is the following:

``` java
public interface ServiceCall<T> {
  T execute();
  void enqueue(ServiceCallback<T> callback);
}
```

``` java
public interface ServiceCallback<T> {
  void onResponse(T response);
  void onFailure(Exception e);
}
```

``` java
public class LanguageTranslation extends WatsonService {
  ...
  public ServiceCall<TranslationResult> translate(final String text, final String source, final String target, Object ignore) {
    return new ServiceCall<TranslationResult>() {
      @Override public TranslationResult execute() {
        return translate(text, source, target);
      }

      @Override public void enqueue(final ServiceCallback<TranslationResult> callback) {
        new Thread(new Runnable() {
          @Override public void run() {
            try {
              callback.onResponse(translate(text, source, target));
            } catch (Exception e) {
              callback.onFailure(e);
            }
          }
        }).start();
      }
    };
  }
}
```

And using it in an async manner from Android code:

``` java
translationService.translate(input.getText().toString(), "en", selectedTargetLanguage, null)
        .enqueue(new ServiceCallback<TranslationResult>() {
            @Override public void onResponse(TranslationResult result) {
                showTranslation(result.getFirstTranslation());
            }

            @Override public void onFailure(final Exception e) {
                showError(e);
            }
        });
```

We overload the method with an extra ignored parameter, that way we do not break existing code and tests. Then we forward the internal call to the existing `translate` method. A new thread is spawned every time.

There is a lot of additional work that needs to be done in order to support OkHttp3. Most of this work will be done inside the `WatsonService` class. Some redesign may need to be done as well, since OkHttp3 takes some different approaches (such as a stateless `OkHttpClient`).

**Comment by GrapeBaBa** [comment]
@germanattanasio 
Would you like consider use RxJava or Guava ListentableFutrue to implement both sync and async invoke. They are more close to CompletableFuture in java8? Or if we could directly use Retrofit which is a wrapper of OkHttp to refactor our  WatsonService?

**Comment by germanattanasio** [comment]
@GrapeBaBa The decision of using okhttp3 and support Async and Sync here is mainly because we need a library that can run on Java 1.6 (legacy companies see #174) and Android.  
We are also going to release an Android SDK next week. It will be just a wrapper of this + some Android classes to work with things like the microphone or speaker.

The dependencies we use in this SDK are small and android compatible. As a result we have a pretty small (1.3MB) jar that can be used in Android.

We are doing all the work in the `update-to-okhttp3` branch so master is already outdated. I will merge it back to master later today.

**Comment by germanattanasio** [comment]
@GrapeBaBa I'm really interested in your opinion on the changes for Async and Sync.

**Comment by GrapeBaBa** [comment]
@germanattanasio 
1.RxJava and Guava ListentableFuture both compatible with java 6, and they are very popular in java and Android area. Reactive method is more powerful than callback way. Just a example, jersey also provider a new reactive client https://jersey.java.net/documentation/latest/rx-client.html.
2.Retroit is also derived from square, same with okhttp. It seems combine RxJava and Okhttp already and very popular in Android area.
But you mentioned jar size is indeed a problem, maybe i can try to investigate if i can find more better method.

**Comment by germanattanasio** [comment]
Can we get an idea of the size of those dependencies?
Can you write an example like the one in this issue so that we can see how
the code will look if you use rxjava and guava?

**Comment by GrapeBaBa** [comment]
Sure, let me try to do that.

**Comment by GrapeBaBa** [comment]
@germanattanasio 
RxJava jar size close to 1MB, Guava seems 2MB, both are large. Maybe jsr166 is a good option (http://g.oswego.edu/dl/concurrency-interest/). Maybe we can add one more method in the interface, this example may be not good to display benefit from reactive method. The most benefit is that when the user need make several api call simulate, the CompletableFuture could compose these calls to avoid callback hell.

```
public interface ServiceCall<T> {
  T sync();
  void async(ServiceCallback<T> callback);
  CompletableFuture<T> rx();
}
```

```
public class LanguageTranslation extends WatsonService {
  ...
  public ServiceCall<TranslationResult> translate(final String text, final String source, final String target, Object ignore) {
    return new ServiceCall<TranslationResult>() {
      @Override public TranslationResult sync() {
        return translate(text, source, target);
      }

      @Override public void async(final ServiceCallback<TranslationResult> callback) {
        new Thread(new Runnable() {
          @Override public void run() {
            try {
              callback.onResponse(translate(text, source, target));
            } catch (Exception e) {
              callback.onFailure(e);
            }
          }
        }).start();
      }

      @Override public CompletableFuture<TransactionResult> rx() {
              return CompletableFuture.supplyAsync(new Supplier<T>() {
      @Override
      public T get() {
        return translate(text, source, target);
      }
    });
      }
    };
  }
}
```

```
translationService.translate(input.getText().toString(), "en", selectedTargetLanguage, null)
        .async(new ServiceCallback<TranslationResult>() {
            @Override public void onResponse(TranslationResult result) {
                showTranslation(result.getFirstTranslation());
            }

            @Override public void onFailure(final Exception e) {
                showError(e);
            }
        });

translationService.translate(input.getText().toString(), "en", selectedTargetLanguage, null)
        .rx()
        .whenComplete(new BiConsumer<T, Throwable>() {
      @Override
      public void accept(T t, Throwable throwable) {
        if(future.isCompletedExceptionally()){
          showError(e);
        }else{
          showTranslation(t);
        }
      }
    });
```

**Comment by germanattanasio** [comment]
Based on your example we can add react without breaking users which means we don't need to decide between react and async and we can support both. Let's finish 3.0 and we can add react in 3.1 along with sync and async, eventually we will remove async I guess.

I was looking at http://mvnrepository.com/artifact/io.reactivex/rxjava/1.1.3 it's around 1MB... 
Why do you want to add Guava?

BTW. If you can take a look at the `update-to-okhttp3`. I just finished with the migration and updated  the README talking about the breaking changes in 3.0
I implemented the changes you suggested in your pull request for static methods. (e.g `log` vs `LOG`).

**Comment by GrapeBaBa** [comment]
@germanattanasio 
Cool. My example neither use Guava nor Rxjava, just use jsr166e. It is quite small. But it is not in maven central. I searched http://mvnrepository.com/search?q=jsr166e, except twitter one, both will be OK.
