### ISSUE TITLE
[tone-analyzer] Part of the getting started code is not compiled

### ISSUE THREAD

**Issue by ishaiborovoy** [watson-developer-cloud/java-sdk#219]
Hi,
In getting started (readme) the following lines is not compiled:

Tone tone = service.getTone(text, Scorecard.EMAIL);
System.out.println(tone);

I am using maven with this dependency:
<dependency>
   <groupId>com.ibm.watson.developer_cloud</groupId>
   <artifactId>java-sdk</artifactId>
   <version>2.9.0</version>
</dependency>

**Comment by germanattanasio** [comment]
Looks like the readme wasn't updated. See an example [here](https://github.com/watson-developer-cloud/java-sdk/blob/master/examples/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/ToneAnalyzerExample.java)

**Comment by germanattanasio** [comment]
Fixed in b88f8c3
