### ISSUE TITLE
Add constants for languages in Language Translation

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/java-sdk#225]
The `LanguageTranslation` service API in the Java SDK does not define any constants for supported languages. For example, right now you have to write:

``` java
service.translate("hello", "en", "es");
```

Rather, having a set of pre-defined constants (an enum most likely) of languages supported by the service would be more helpful:

``` java
service.translate("hello", Language.EN, Language.ES);
```

**Comment by germanattanasio** [comment]
@jpetitto

**Comment by tanmayb123** [comment]
Would it be better to use something like "Language.EN" or "Language.ENGLISH"?

**Comment by tanmayb123** [comment]
#241 should take care of this.
