### ISSUE TITLE
Investigate problems with WebSocket connections

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/java-sdk#231]
See

http://stackoverflow.com/questions/36504879/watson-stt-java-varying-results-between-websockets-java-and-http-post

**Comment by germanattanasio** [comment]
Example file https://s3.amazonaws.com/mozart-company/tmp/4.flac

**Comment by germanattanasio** [comment]
I'm assigning this to @vherrin since this team has done something with OkHttp WebSockets

**Comment by abdielou** [comment]
Good. Something I forgot to mention is that I also tried with the Java Http `recognize` method and worked the same as with cURL. That was expected but at least we know that works using Java.

**Comment by germanattanasio** [comment]
Thanks, @abdielou, I'm working on moving to okhttp3 and use their WebSockets instead of the library we are using now.

**Comment by abdielou** [comment]
@germanattanasio What's the ticket about the okhttp3 implementation?

**Comment by germanattanasio** [comment]
#217
