### ISSUE TITLE
"docSentiment" field for Article model

### ISSUE THREAD

**Issue by Apisov** [watson-developer-cloud/java-sdk#232]
Hello.
Faced with "problem" that now you don't have field `docSentiment` in Article model. In case when we asking in return `enriched.url.docSentiment`. Also don't know why but you have missed getters\setters for `docSentiment` field in `EnrichedTitle` model.

As I understand for now I need to download last version of SDK and modify it or write own fetching, parsing of api. Maybe someone need this field too.

**Comment by germanattanasio** [comment]
you are right. I will work on this or you can write a pull request
