### ISSUE TITLE
test cases failed

### ISSUE THREAD

**Issue by changbaishan** [watson-developer-cloud/java-sdk#246]
Running com.ibm.watson.developer_cloud.service.GenericServiceTest
Apr 19, 2016 4:06:13 PM com.ibm.watson.developer_cloud.service.WatsonService execute
SEVERE: http://localhost:9898/v2/profile, status: 404, error: Bad request
Apr 19, 2016 4:06:14 PM com.ibm.watson.developer_cloud.service.WatsonService execute
SEVERE: http://localhost:9898/v2/profile, status: 413, error: Bad request
Apr 19, 2016 4:06:14 PM com.ibm.watson.developer_cloud.service.WatsonService execute
SEVERE: http://localhost:9898/v2/profile, status: 503, error: ServiceUnavailableException
Apr 19, 2016 4:06:15 PM com.ibm.watson.developer_cloud.service.WatsonService execute
SEVERE: http://localhost:9898/v2/profile, status: 415, error: UnsupportedException
Apr 19, 2016 4:06:16 PM com.ibm.watson.developer_cloud.service.WatsonService execute
SEVERE: http://localhost:9898/v2/profile, status: 429, error: TooManyRequestsException
Apr 19, 2016 4:06:16 PM com.ibm.watson.developer_cloud.service.WatsonService execute
SEVERE: http://localhost:9898/v2/profile, status: 409, error: Conflict Exception
Apr 19, 2016 4:06:17 PM com.ibm.watson.developer_cloud.service.WatsonService execute
SEVERE: http://localhost:9898/v2/profile, status: 503, error: Service Unavailable
Apr 19, 2016 4:06:17 PM com.ibm.watson.developer_cloud.service.WatsonService execute
SEVERE: http://localhost:9898/v2/profile, status: 403, error: Bad request
Apr 19, 2016 4:06:18 PM com.ibm.watson.developer_cloud.service.WatsonService execute
SEVERE: http://localhost:9898/v2/profile, status: 400, error: Bad request
Apr 19, 2016 4:06:18 PM com.ibm.watson.developer_cloud.service.WatsonService execute
SEVERE: http://localhost:9898/v2/profile, status: 401, error: UnauthorizedException
Apr 19, 2016 4:06:19 PM com.ibm.watson.developer_cloud.service.WatsonService execute
SEVERE: http://localhost:9898/v2/profile, status: 500, error: Bad request

**Comment by germanattanasio** [comment]
that's the expected output for those tests
