### ISSUE TITLE
Please include jar and javadoc in your future releases

### ISSUE THREAD

**Issue by changbaishan** [watson-developer-cloud/java-sdk#247]
Given that test cases often fail. It is desirable that IBM releases javadoc and jar in the future releases of watson-developer-cloud/java-sdk. In addition, it would also help if you include the library jars(such as okhttp)  in your releases.

**Comment by germanattanasio** [comment]
The library with the dependencies can be found in the releases section.
For example, if you look at the last release you will see the jar-with-dependencies.
See: https://github.com/watson-developer-cloud/java-sdk/releases/tag/2.10.0
This is already mentioned in the README.md


The javadoc for each version can be found here: http://watson-developer-cloud.github.io/java-sdk/

Looks like we are not releasing the javadocs and sources into maven so I will look at that.

**Comment by germanattanasio** [comment]
I just double check and we are releasing the javadoc and sources along with the jar.
See  http://central.maven.org/maven2/com/ibm/watson/developer_cloud/java-sdk/2.10.0/
