### ISSUE TITLE
Investigate the use of Reactive Java along with Sync and Async

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/java-sdk#255]
Based on a conversation in #217 we will investigate the use of react.  
@GrapeBaBa Let's discuss the work to be done here.

**Comment by germanattanasio** [comment]
Hi @GrapeBaBa are you an IBMer?

**Comment by GrapeBaBa** [comment]
@germanattanasio 
Yes, I am working on IBM China. My email is ckaiwh@cn.ibm.com

**Comment by germanattanasio** [comment]
@GrapeBaBa do you want to take the lead here? I think you can add a method to `ServiceCall` and we can go from there.

**Comment by GrapeBaBa** [comment]
My pleasure.

**Comment by GrapeBaBa** [comment]
@germanattanasio 
As i am busy on other project, i think i can start this issue next Monday.

**Comment by germanattanasio** [comment]
No rush. take your time!

**Comment by germanattanasio** [comment]
Fixed by @GrapeBaBa
