### ISSUE TITLE
[general-jdk]Proposal to use Lombok to simplify getter/setter/toString/equals/builder method

### ISSUE THREAD

**Issue by GrapeBaBa** [watson-developer-cloud/java-sdk#257]
@germanattanasio 
Would you like consider Lombok(https://projectlombok.org/) to simplify current model code? It can reduce many boilerplate codes using compile time code generation. It also can avoid if add one property in an exist model class, someone missing some boilerplate methods.

**Comment by germanattanasio** [comment]
There are some issues around Javadoc and developer experience when using Lombok. Take a look at http://stackoverflow.com/questions/3852091/is-it-safe-to-use-project-lombok

The goal of the java-sdk is to help developers trying to use the Watson APIs. Every decision we take should take into account the impact in the developer experience. If I add Lombok and I lose the javadoc for the getter and setter then I'm giving a poor developer experience.

IF we can sort out those issues we can totally add Lombok.

**Comment by GrapeBaBa** [comment]
@germanattanasio You are always there, your concern make sense, I paid no attention about this yet. I just see https://projectlombok.org/features/GetterSetter.html. It seems since 1.12.0, it provide a simple workaround for javadoc for getter/setter. I will try to do some samples.

**Comment by GrapeBaBa** [comment]
@germanattanasio 
After i try in my own project hyperledger-java, it is indeed a problem for javadoc, i will close this issue.
Thanks.
