### ISSUE TITLE
[AlchemyDataNews] need a method to get the enriched.url.text field

### ISSUE THREAD

**Issue by alisa-ipn** [watson-developer-cloud/java-sdk#260]
Currently, Alchemy news has a list of [accessible fields](https://docs.google.com/spreadsheets/d/1wN0e_fhYCO7GBAneN9xjrNo57OtS_0Tr8FI9xCMfmzM/edit?pref=2&pli=1#gid=0)

But not all of them are reachable through the methods provided in the SDK.
Like `enriched.url.text`

A suggested solution if possible:
In `com.ibm.watson.developer_cloud.alchemy.v1.model` package 
       `Article` class needs `String getText()` method to return the field `enriched.url.text` 

java-sdk version: 2.1.0

**Comment by germanattanasio** [comment]
fixed
