### ISSUE TITLE
[tradeoff-analytics] 'map' property missing in Dilemma object

### ISSUE THREAD

**Issue by bianca-pereira** [watson-developer-cloud/java-sdk#261]
The following line does not retrieve a 'map' property for the solved dilemma in java-sdk 2.9.0.

Dilemma dilemma = service.dilemmas(problem, true);

**Comment by germanattanasio** [comment]
How can I reproduce the issue?

**Comment by germanattanasio** [comment]
I just saw the `map` property in the API specs https://watson-api-explorer.mybluemix.net/apis/tradeoff-analytics-v1#!/tradeoff-analytics/dilemmas
