### ISSUE TITLE
Break services out into separate modules

### ISSUE THREAD

**Issue by Hsaylor** [watson-developer-cloud/java-sdk#262]
Adding async consumption options has helped with the Java SDK's consumability on Android, however there's still the problem of it being quite large. Including the Java SDK pushes Android apps dangerously close to the ~65k method limit. In order to allow for better consumption for Android development we should break each service out into separate modules so developers only have to include services they plan on using. This follows the model Google Play Services use, where you can still download the entire SDK if you desire, but you can also download one service without having to download all others.

**Comment by germanattanasio** [comment]
I think okhttp is doing something like this so we should take a look at what they are doing...

**Comment by GrapeBaBa** [comment]
+1

**Comment by germanattanasio** [comment]
(ง •̀_•́)ง

**Comment by max-vogler** [comment]
To support Android users, we could check the Java SDK for compatibility with ProGuard. That way, the unneeded methods can be removed automatically by Proguard, which is very common among Android projects.

See: [Shrink Your Code and Resources](https://developer.android.com/studio/build/shrink-code.html)

**Comment by germanattanasio** [comment]
@Hsaylor what do you think? can we have this process described in the `android-sdk` ?

**Comment by Hsaylor** [comment]
While I'm rather inexperienced with ProGuard, it seems like a possible solution. However, I think at the end of the day it's a question of SDK design. I personally think breaking everything out into separate services is still the better option, again referencing that Google Play Services and OkHttp do this as opposed to saying "just use ProGuard". Simply put I suppose my argument comes down to "why remove extra code when you could just not include it in the first place?"

**Comment by GrapeBaBa** [comment]
Two options:
1.Use maven profile to build several independent jars.
2.Change the project structure to multiple modules maven/gradle project.
Thoughts?

**Comment by max-vogler** [comment]
I totally agree with @Hsaylor's view on SDK design.

> 1.Use maven profile to build several independent jars.

There are many StackOverflow posts and even one [Sonatype blog post](http://blog.sonatype.com/2010/01/how-to-create-two-jars-from-one-project-and-why-you-shouldnt/) that warn about this. Personally, I'm seeing some problems here when users depend on multiple of these *independent* jars, which share the same common code (e.g. `http.*`)

> 2.Change the project structure to multiple modules maven/gradle project.

I think this would be the only viable option, even though the effort shouldn't be underestimated. Modularity means splitting up the project into:

 - one base module as shared dependency (containing `http.*, util.*, service.*`)
 - 18 modules
 - one master module, depending on all 19 submodules

**Comment by germanattanasio** [comment]
We should keep `java-sdk` as the module that has all the other modules.

Then we can use something like `personality-insights-v2`, `visual-recognition-v2-beta`.

@jsstylos ?

**Comment by jsstylos** [comment]
Another option would be to do modules per service as opposed to per version. (This wouldn't be as optimized for space, but maybe more logical.)

If `java-sdk` has all of the other modules would there be a separate common module, so that users who just wanted a single service would import the service module which would pull in the common module?

**Comment by germanattanasio** [comment]
There will be a common project and each module will import that project. The `java-sdk` module will import all the services.

**Comment by doconnor78** [comment]
@germanattanasio And `each module` will be an entire service wrapper as opposed to a version? So I just add a dependency on the nlc module and get all versions? (that would be my preference at least)

**Comment by germanattanasio** [comment]
Yeah, I think you we are all on the same page here. Can someone take this task, fork the repo and do a first pass moving the services to different repos? I completely booked until July 14

**Comment by germanattanasio** [comment]
Well, I guess I will have to do it 😒

**Comment by Hsaylor** [comment]
I've got you, @germanattanasio! I had some free time so I wrote an example of breaking things out using the language translation service. Check the `modules-for-android` branch and tell me what you think

**Comment by germanattanasio** [comment]
I'll take a look at it @Hsaylor. I tried to do it  during the weekend but it was more work than what I  thought

**Comment by Hsaylor** [comment]
I realized I pushed up the wrong thing >< Although the concept is the same, it might be a bit harder to see what's going on in that project...

**Comment by Hsaylor** [comment]
@germanattanasio I pushed up a much cleaner version to the `modules-for-android` branch, which includes all services. Examples and Tests are currently broken, as they haven't been updated to reflect the refactor, but the structure should be much more clear.

**Comment by germanattanasio** [comment]
got it. I will take a look at it this weekend
