### ISSUE TITLE
[speech-to-text] Provide functionality to explicitly end transcription

### ISSUE THREAD

**Issue by Hsaylor** [watson-developer-cloud/java-sdk#266]
In order to finish deprecating the speech-android-ask we need to update the java-sdk's speech-to-text to have a method which explicitly ends transcription. Specifically, this should be for the web socket transcription. After quickly reviewing the code, it looks like this can be accomplished by exposing a method within the `SpeechService` which sends a stop transcription message. In `WebSocketManager` this is done by:
```java
socket.sendMessage(RequestBody.create(WebSocket.TEXT, buildStopMessage().toString()));
```
so it just needs to be exposed within the `SpeechService`.

It would also be nice, although not necessary when it comes to work for deprecating the speech-android-sdk, to expose a method to explicitly close the web socket as well.

**Comment by germanattanasio** [comment]
@vherrin  can we get someone to help me with this?

**Comment by Hsaylor** [comment]
I'm going to close this. After a second look at the architecture and further thought this isn't something that should be necessary. The user can use the close functionality on the input stream, which should in turn stop transcription and close the socket.
