### ISSUE TITLE
[VisualRecognition] setUsernameAndPassword - throws IllegalArgumentException

### ISSUE THREAD

**Issue by anthonyencarnacion** [watson-developer-cloud/java-sdk#284]
Hi!
I'm creating an android application running on android 4.4.
As I am using the Visual Recognition v3. I got an exception upon setting the username and password of the service.

`VisualRecognition service = new VisualRecognition(VisualRecognition.VERSION_DATE_2016_05_19);
service.setUsernameAndPassword("<username>", "<password>");`

I looked into the codes and saw that we are really throwing an exception upon setting the credentials for this service.

`@Override
  public void setUsernameAndPassword(String username, String password) {
    throw new IllegalArgumentException("This service requires an api_key. Use the setApiKey() method instead");
  }`

I tried creating a new Visual Recognition service just to check if maybe Bluemix would give us an API key instead of the usual username and password.

But it is giving us the same value as before.

I'm not entirely sure how the whole Visual Recognition class works for now. But if you can inform me on how we can find a remedy for this, I can try it out.

Thank you.

**Comment by anthonyencarnacion** [comment]
So I tried to commented out some lines in the code and build the code.
And I was able to connect to my Visual Recognition service.

Here are some of the lines that I commented out.

Visual Recognition.java line : 305
`  // @Override
  // public void setUsernameAndPassword(String username, String password) {
    // throw new IllegalArgumentException("This service requires an api_key. Use the setApiKey() method instead");
  // }` 

Though after the calling the classify function I am getting not images.

**Comment by germanattanasio** [comment]
@anthonyencarnacion we are releasing a new version of the service right now.
You are using `v2-beta` in Bluemix which uses `username` and `password` but the code is trying to use `v3` which will use `api_key`.

Wait 1 more hour and your code will work!

**Comment by anthonyencarnacion** [comment]
I checked for the API key on the previously created Visual Recognition service but I was not able to find it there.
So I deleted the previous service and created a new one and saw the API Key.

I still have to test the v3 though.

Thank you..
