### ISSUE TITLE
[retrieve & rank] would like to obtain ranker confidence from a combined retrive and rank call

### ISSUE THREAD

**Issue by dgterry** [watson-developer-cloud/java-sdk#285]
Description of problem we are trying to solve:

We are using retrieve and rank to answer user questions and have noticed that answers with a low ranker confidence are not very helpful. We would like to remove answers with a low confidence server side before a user sees them.

We had originally been making calls to R&R using this approach:
https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/retrieve-and-rank/api/v1/#query_ranker

The problem is that this call does not expose the ranker's confidence and we therefore have to make an initial call to the /fcselect endpoint to obtain answers and then a second call to the /rank endpoint to obtain the confidence. 

suggested solution:
We would like the simple call mentioned earlier, that both returns and ranks results, to expose the ranker's confidence in the response for each answer.

**Comment by dgterry** [comment]
@sud-puth please add to or correct this issue as necessary

**Comment by germanattanasio** [comment]
@gjs29 what do you think?

**Comment by gjs29** [comment]
The confidence score has been exposed in the latest version of the ranker. I'll work on getting it added to this sdk as well.

**Comment by gjs29** [comment]
In the latest version of the ranker, a new field ranker.confidence is exposed. You can return it through SolrJ with the following query:
```
    final SolrQuery query = new SolrQuery("any_query")
        .setFields("ranker.confidence", "any_other_fields...")
        .setRequestHandler("/fcselect")
        .setParam("ranker_id", "{ranker-id}");
```
We are in the process of upgrading clusters to this version of the ranker and will finish in a few days. Your cluster may already have this feature exposed. No changes to this java-sdk are necessary.

**Comment by germanattanasio** [comment]
I'm closing this since no changes to the java-sdk are necessary
