### ISSUE TITLE
[retrieve & rank] would like a supported way to use SOLR highlighting along with the ranker

### ISSUE THREAD

**Issue by dgterry** [watson-developer-cloud/java-sdk#286]
Description of the problem we're trying to solve:

In our UI when a user asks a question of R&R we want to highlight the important keywords in the results. solrj provides a way to do this when we are just issuing a straight SOLR query but we have been unable to find a way to do this with the SDK when we are using the ranker.

Suggested solution:
We would like a way to specify SOLR highlighting parameters when using this SDK call: https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/retrieve-and-rank/api/v1/#query_ranker

**Comment by dgterry** [comment]
@sud-puth please revise the description if it is not accurate

**Comment by germanattanasio** [comment]
@gjs29 what do you think?

**Comment by gjs29** [comment]
Highlighting should work with the ranker when using the fcselect endpoint. Have you tried setting the following commands on your query object? hl=true hl.fl=text

**Comment by Sud-Puth** [comment]
The highlighting with the above parameters works but right now can use only REST calls since the ranker call isn't ready[https://github.com/watson-developer-cloud/java-sdk/issues/285] but we were thinking if it was possible to include that in the response object that we get from the Ranker officially.

**Comment by gjs29** [comment]
Once issue [#285] is closed, this can be accomplished with the following query:
    ```
final SolrQuery query = new SolrQuery("any_query")
        .setHighlight(true)
        .setParam("hl.fl", "field_to_highlight")
        .setFields("ranker.confidence", "any_other_fields...")
        .setRequestHandler("/fcselect")
        .setParam("ranker_id", "{ranker-id}");
```
