### ISSUE TITLE
Natural Language Classifier is missing a Get Status method

### ISSUE THREAD

**Issue by SirSpidey** [watson-developer-cloud/java-sdk#29]
Natural Language Classifier code doesn't have a method to retrieve the status of a classifier.

**Comment by germanattanasio** [comment]
`getClassifier()` will return the classifier information along with the `status`

**Comment by germanattanasio** [comment]
See https://github.com/watson-developer-cloud/java-sdk/blob/master/src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/NaturalLanguageClassifier.java#L164
