### ISSUE TITLE
Send JVM and OS statistics in User-Agent

### ISSUE THREAD

**Issue by colindean** [watson-developer-cloud/java-sdk#291]
We should be sending anonymous statistics to understand those using the library.

These properties are most interesting, but other properties could be included.
```
java.vendor
java.version
os.arch
os.name
os.version
```

The User-Agent, when the statistics are sent, should look something like this:

    Watson-Java-SDK/0.1.19 (java.vendor=IBM Corporation; os.arch=x86_64; os.version=10.11.4; os.name=Mac OS X; java.version=1.8.0_66)

This feature must be optional, likely opt-out.

**Comment by kognate** [comment]
Likely related to #296

**Comment by germanattanasio** [comment]
I'm moving this to the backlog.

Do we have an example of how to get this information dynamically? the example should use jdk1.6 and work on Android.
