### ISSUE TITLE
Determine version for User-Agent programatically

### ISSUE THREAD

**Issue by colindean** [watson-developer-cloud/java-sdk#294]
The version number is hardcoded in both the production code and the test. This should be determined programmatically, most likely from some kind of generated code or properties file.

**Comment by colindean** [comment]
I have a solid example of how to do this from one of my own projects, which is unfortunately not public. I'll try to set aside some time next week to do it.

**Comment by kognate** [comment]
This is probably also related to #296

**Comment by germanattanasio** [comment]
@colindean I'm going to leave this our of the next release for now

**Comment by max-vogler** [comment]
FYI: Just found a hardcoded user-agent String in [`service.GenericServiceTest`](https://github.com/watson-developer-cloud/java-sdk/blob/master/src/test/java/com/ibm/watson/developer_cloud/service/GenericServiceTest.java)
