### ISSUE TITLE
Allow the user-agent header to be modified

### ISSUE THREAD

**Issue by michaelkeeling** [watson-developer-cloud/java-sdk#296]
I'm a Watson developer building tools and services on top of the Watson APIs and I'd like to use the java-sdk.  The user-agent is currently hard coded to a value specific to the sdk.  Ideally it would be great if we could modify the user-agent header to include information about our client.  The goal is to allow us to collect some very basic usage information about how often the tool is being used.  Ideally we'll also know the java-sdk was used by the tool.

The ability to add a client name and version is useful.  The resulting header might look like the following

```
my-application/1.0 (java.vendor=IBM Corporation; os.arch=x86_64; os.version=10.11.4; os.name=Mac OS X; java.version=1.8.0_66) watson-apis-java-sdk/3.0.0-RC1
```

**Comment by kognate** [comment]
Can you use a different request header to pass that information or does it have to be in the user agent?

**Comment by michaelkeeling** [comment]
The problem is in the metrics on the other side.  The core problem is that if I want to use this SDK, I need a way to get standard usage data from the platform.  @germanattanasio I think could answer this question as I believe he also wrote the scripts that data collection from the http logs in WDC.

**Comment by germanattanasio** [comment]
Let's see if we can push the platform to provide a better solution for this. Otherwise, I can update the code to allow users to add information to the `User-Agent`
