### ISSUE TITLE
Proposed to increase the new construction method

### ISSUE THREAD

**Issue by handong890** [watson-developer-cloud/java-sdk#298]
Some time we using spring for our project and we want  control them keep one instance.
**So please add all constructor method with username and password**

For example com.ibm.watson.developer_cloud.dialog.v1.DialogService
` public DialogService(String username,String password) {
		    super("dialog");
		    setEndPoint(URL);
		    setUsernameAndPassword(username, password);
		  }`

if have this then I can config it to our spring project
`<bean id="dialogService" class="com.ibm.watson.developer_cloud.dialog.v1.DialogService">
		 <constructor-arg name="username" value="${dialogusername}" />
        <constructor-arg name="password" value="${dialogpassword}"  />
	</bean>	`

**Comment by germanattanasio** [comment]
fixed by @ndrlslz
