### ISSUE TITLE
How to use keyword spotting feature for IBM Waston Speech to text API?

### ISSUE THREAD

**Issue by sourav-ibm** [watson-developer-cloud/java-sdk#299]
I am using IBM Watson Speech to text API to convert audio files into text. Every feature is working fine for me. But I am unable to use the Keyword Spotting feature. The output is not giving any info regarding spotted keywords.

Here is my code:

    `SpeechToText service = new SpeechToText();
     service.setUsernameAndPassword("*********", "********");
     
     service.setEndPoint("https://stream.watsonplatform.net/speech-to-text/api");
 
     String[] keys= {"abuse","bullying","parents","physical","assaulting"};
     RecognizeOptions options = new RecognizeOptions().contentType("audio/wav").model("enUS_NarrowbandModel").continuous(true).inactivityTimeout(500).keywords(keys).keywordsThreshold(0.7);
 
 
     File audio = new File("C:\\Users\\AudioFiles\\me.wav");
 
     SpeechResults transcript = service.recognize(audio, options);
     System.out.println(transcript);`

I am using 
compile group: 'com.ibm.watson.developer_cloud', name: 'java-sdk', version: '2.9.0' for gradle build.
Is there any special function to get the spotted keywords as output as well with the transcript?

**Comment by max-vogler** [comment]
Hey @sourav-ibm! You have been using the Watson Java SDK correctly - this feature was not fully implemented yet. I added it in PR #314

**Comment by sourav-ibm** [comment]
Hey @max-vogler after fixing this bug please let me know. I want to use this feature as it will be a very useful feature for my project.

**Comment by max-vogler** [comment]
I fixed it already. If you don't want to wait for the next version release, you can use the feature now by downloading [my `fix-299` branch](https://github.com/max-vogler/watson-java-sdk/tree/fix-299) instead of the Maven repo.
