### ISSUE TITLE
[text-to-speech] Add support for getVoice() method

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/java-sdk#303]
We need to add support for the TTS getVoice() method. The comparable STT getModels() and getModel() methods are already supported. But for TTS, only getVoices() is provided.

**Comment by max-vogler** [comment]
Fixed in 1d55571c7.

**Comment by jeffpk62** [comment]
Thanks!  Will this be fixed in v2.10 onward or only in v3.0?

**Comment by max-vogler** [comment]
I cannot answer this bindingly - @germanattanasio or another owner can. Although I don't see a branch for ongoing v2.x development, so chances are the fix will only be integrated in v3.x.
