### ISSUE TITLE
[text-to-speech] Correct name of German Birgit Voice object

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/java-sdk#304]
The equivalent Voice object for the voice de-DE_BirgitVoice is currently named DE_GIRGIT.  We need to change the name of the object to DE_BIRGIT.

**Comment by max-vogler** [comment]
I deprecated `DE_GIRGIT` and added the correct `DE_BIRGIT` in 84d9400 of PR #312

**Comment by jeffpk62** [comment]
Sounds good.  Thanks!

**Comment by germanattanasio** [comment]
fixed by @max-vogler
