### ISSUE TITLE
[text-to-speech] Synchronize uses of voices between getVoices() and synthesize() methods

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/java-sdk#305]
The getVoices() method returns the same information as the equivalent HTTP and Node interfaces:

```
  {
    "description": "Isabela: Brazilian Portuguese (portugu&ecirc;s brasileiro) female voice.",
    "gender": "female",
    "language": "pt-BR",
    "name": "pt-BR_IsabelaVoice",
    "url": "https://stream.watsonplatform.net/text-to-speech/api/v1/voices/pt-BR_IsabelaVoice"
  }
```

However, the synthesize() method for the Java SDK does not accept the string version of a voice (e.g., 
pt-BR_IsabelaVoice).  It instead accepts a Voice object of the form Voice.BR_ISABELA.  We need to do one of the following:

- Modify the output of the getVoices() (and getVoice()) method to return the name of the Voice object used for each language with the Java SDK or
- Modify the synthesize() method to accept the string form of the voice name used by the HTTP and Node SDK interfaces.

This change would synchronize the Java methods and make the output more meaningful and useful to users.

**Comment by jeffpk62** [comment]
We may also want to consider taking the approach that's used for STT createSession(), where overloaded methods accept either an object or a string for the model.  For TTS, that approach would need to be adopted by synthesize(), but that might lead to excessive versions of the method.  Anyway, just an additional consideration.

**Comment by max-vogler** [comment]
I added `Voice.getByName(String)` to 1c18bb0 of PR #312. This is imho more modular and composable than adding overloaded methods to `TextToSpeech`.

**Comment by jeffpk62** [comment]
Thanks, Max.  So what is the visible result of this in the interface?  Can you add a quick example, please?  I'm assuming this is a v3.0 fix, and I'm not testing with that for the imminent release, so if you could show some example output, I'd appreciate it!

By the way, I only mentioned the overloading because it was addressed that way in STT, the corollary of TTS, and because German had suggested that as one possible alternative solution.  As long as we make the connection between the voice strings and objects clear in some visible fashion, it's a very useful enhancement.

Thanks again.  -jeff

**Comment by max-vogler** [comment]
After initializing your data:
```java
String name = "en-US_AllisonVoice";
TextToSpeech service = new TextToSpeech();
```
you can get a Voice object by calling 
```java
Voice voice = Voices.getByName(name); // this method is new
```
and use it with all existing methods:
```java
service.synthesize("Tomato", voice, WAV)
// or
service.synthesize("Tomato", voice, WAV)
// or
service.getPronunciation("Tomato", voice, Phoneme.IPA)
```

**Comment by max-vogler** [comment]
I understand that overloading methods is a viable alternative and I can change my PR if requested. Let me explain my design decision against overloading:

> Modify the synthesize() method to accept the string form of the voice name used by the HTTP and Node SDK interfaces.

I understand that this is a neat shortcut, although more methods need to be added to support this fully: `getPronunciation(String, String, Phoneme)`, `synthesize(String, String)`, and `synthesize(String, String, AudioFormat)`. That is why my PR includes the other approach, where only one Method `Voice.getByName` is added.

**Comment by jeffpk62** [comment]
I agree with your decision to avoid additional overloading, Max, especially given the ramifications you describe (thanks for the added detail!).  I just wanted to explain why I'd mentioned it.  That's all good.

But I think there's still a disconnect between the getVoices() method (and the new getVoice() method that I think was added) and the information a user needs to use a voice with synthesis.  With all of the interfaces (HTTP/cURl, Node, and Java; not sure about Python at the moment), these methods return the following information:

```
{
  "url": "https://stream.watsonplatform.net/text-to-speech/api/v1/voices/en-US_AllisonVoice",
  "name": "en-US_AllisonVoice",
  "language": "en-US",
  "customizable": true,
  "gender": "female",
  "description": "Allison: American English female voice."
}
```

A developer would call one of these methods to learn what voices are available and what values they can pass to synthesize audio.  For the HTTP and Node interfaces, the information in the **name** field is the value a developer passes to a method that synthesizes audio.  With the Java interface, the developer passes a Voice object, but the name of the object isn't included in the previous output.  We need to address that disconnect so that calling a voice method returns the actual object name a developer needs to use.  Otherwise, these methods offer little practical value with the Java SDK.

The methods of the Voice object itself are somewhat ancillary and not immediately obvious to the user.  The user needs to go deeper into the Javadoc to discover them and to understand the connection between the voice strings and the voice objects.  We can solve these problems by exposing the Voice object in the output of the getVoices() and getVoice() methods for Java, making the voices methods more useful and the interface easier to use.

Sorry if I was less than clear in the original issue description or if I've misinterpreted something.  I hope this explanation 

Thanks!  -jeff

**Comment by max-vogler** [comment]
Transcribing parts of the chat between @jeffpk62 here:

- In v3, the Voice objects are better visible and integrated. The use case from above ("How to specify a Voice in the synthesize() method) has been improved in v3, simply by using Voice objects instead of String IDs consistently.
- @jeffpk62 mentioned an interesting point: The usage of Voice objects instead of String ids introduced a major difference between the Java and Node.js SDKs. Somebody else has to decide whether similarity along the SDKs is more important than following programming language patterns in this point.

**Comment by germanattanasio** [comment]
fixed by @max-vogler and merged into `master` already
