### ISSUE TITLE
Concept Insights : ConceptualSearch

### ISSUE THREAD

**Issue by sandhya9** [watson-developer-cloud/java-sdk#309]
Using https://github.com/watson-developer-cloud/java-sdk/releases/download/java-sdk-3.0.0-RC1/java-sdk-3.0.0-RC1-jar-with-dependencies.jar
 
and passing user_fields as a string, please see the following code snippet, This is really urgent for keynote/presentation session at Devoxx, UK.
 
 
        Map<String, Object> parameters = new HashMap<>();
        parameters.put(ConceptInsights.IDS, ids);
        parameters.put(ConceptInsights.LIMIT, 20);
        RequestedFields requestedFields = new RequestedFields();
        requestedFields.include("user_fields");
        parameters.put(ConceptInsights.DOCUMENT_FIELDS, requestedFields);
        QueryConcepts queryConcepts = conceptInsights.conceptualSearch(corpus, parameters);
        // output results
        LOGGER.log(Level.INFO, "Found {0} matches for conceptual search", queryConcepts.getResults().size());
        return new ResponseEntity<>(queryConcepts.getResults(), HttpStatus.OK);
  
 
The video link has been attached as a user_field to the document created in devoxx_corpus, please see the following code snippet :

``` 
private void processConceptInsights(final SpeechResults speechResults) {
        LOGGER.info("create document");
        Document newDocument = new Document(corpus, UUID.randomUUID().toString());
        newDocument.setName(docName);
        newDocument.setLabel(docName);
        final Map<String, String> userFields = new HashMap<>();
        userFields.put("youTubeLink", youTubeLink);
        newDocument.setUserFields(userFields);
 
        LOGGER.info("Add speech results into document");
        StringBuilder stringBuilder = new StringBuilder();
        for (Transcript transcript : speechResults.getResults()) {
            stringBuilder.append(transcript.getAlternatives().get(0).getTranscript());
        }
        newDocument.addParts(new Part("part_", stringBuilder.toString(), HttpMediaType.TEXT_PLAIN));
        conceptInsights.createDocument(newDocument);
    }
}
```
 
The equivalent curl command for doing conceptualSearch with document_fields set to user_fields works :
 
`curl -u {username}:{password} -G -d "ids=[\"/graphs/wikipedia/en-20120601/concepts/Java_Servlet\"]" -d "document_fields={\"user_fields\":1}" "https://gateway.watsonplatform.net/concept-insights/api/v2/corpora/eve6tionsto1/devoxx_corpu/conceptual_search"|jq`
 
Therefore, can you please tell me if I am missing something or there is a bug in the conceptualSearch API ?

**Comment by g-may** [comment]
There is a bug in the SDK -- try adding getters and setters for "user_fields" to `Result.java` in `com.ibm.watson.developer_cloud.concept_insights.v2.model`

``` java
// Add this import:
import java.util.Map;

/**
 * The Class Result.
 */
public class Result extends GenericModel {

  @SerializedName("explanation_tags")
  private List<Annotation> explanationTags;
  private String id;
  private String label;
  private Double score;
  
  // Add these lines:
  @SerializedName("user_fields")
  private Map<String, String> userFields;
  public Map<String, String> getUserFields() {
	return userFields;
  }
  public void setUserFields(Map<String, String> userFields) {
	this.userFields = userFields;
  }

 ...
```

**Comment by sandhya9** [comment]
Hi ,
Thank you ! Have you updated Result class ? 
Thank you, Sandhya

**Comment by jsstylos** [comment]
This will get added into the SDK but may not be published by your conference, so if you need this urgently I recommend cloning the repository and adding the code above

**Comment by stephanj** [comment]
I can confirm that this fixes the bug, thanks!

**Comment by sandhya9** [comment]
Can you please host the attached 3.0.0-RC2-SNApSHOT.jar  as a public maven repository , so the developers at Devoxx, UK can do the hands-on Lab at Devoxx, UK, 2016. 
[java-sdk-3.0.0-RC2-SNAPSHOT.jar.zip](https://github.com/watson-developer-cloud/java-sdk/files/300576/java-sdk-3.0.0-RC2-SNAPSHOT.jar.zip)
