### ISSUE TITLE
2.10.0 is not available version in maven central

### ISSUE THREAD

**Issue by ishaiborovoy** [watson-developer-cloud/java-sdk#315]

**Comment by germanattanasio** [comment]
I would recommend you to use the `3.0.0-RC1`.
In any case `2.10.0` is on maven central (see [this](http://mvnrepository.com/artifact/com.ibm.watson.developer_cloud/java-sdk/2.10.0))

Make sure your `pom.xml` has the right dependency name:
```xml
<dependency>
   <groupId>com.ibm.watson.developer_cloud</groupId>
   <artifactId>java-sdk</artifactId>
   <version>2.10.0</version>
</dependency>
```
