### ISSUE TITLE
Migrate to OkHttp's MockWebServer

### ISSUE THREAD

**Issue by max-vogler** [watson-developer-cloud/java-sdk#316]
# Summary

Remove `MockServer` and use `MockWebServer` in unit tests

- [x] `natural_language_classifier`
- [x] `personality_insights`
- [x] `service.GenericServiceTest`
- [x] `tone_analyzer`

## Backlog:
- [x] `document_conversion`
- [x] Remove dependency, clean up WatsonServiceUnitTest

**Comment by germanattanasio** [comment]
I'm moving this to the backlog. The Document conversion team will probably do this
