### ISSUE TITLE
Missing models for integration tests

### ISSUE THREAD

**Issue by max-vogler** [watson-developer-cloud/java-sdk#324]
It seems like several server-side models are missing for integration tests:
- [ ] `NotFoundException: Not found` at `testGetClassifiers(NaturalLanguageClassifierIT.java:134)`
- [ ] `NotFoundException: Not found` at `testClassify(NaturalLanguageClassifierIT.java:95)`
- [ ] `NotFoundException: Not found` at `testGetRankerStatus(RetrieveAndRankIT.java:185)`
- [ ] `NotFoundException: Not found` at `testGetRankers(RetrieveAndRankIT.java:177)`

Additionally one resource file is missing:
- [x] `FileNotFoundException: src/test/resources/personality_insights/contentitems.json` at
`getProfileWithContentItems(PersonalityInsightsIT.java:105)`

See: [Travis build log](https://travis-ci.org/watson-developer-cloud/java-sdk/jobs/136098866#L836)

**Comment by germanattanasio** [comment]
fixed
