### ISSUE TITLE
Remove Javax

### ISSUE THREAD

**Issue by Hsaylor** [watson-developer-cloud/java-sdk#341]
It was brought to my attention today that using the SDK on API 19 (Android 4.4) and below will fail. This is due to the use of the `javax` library. Android only has an extremely limited version of `javax` available to use, even more so for earlier versions.

Specifically the block of code causing the failure is

```java
private static String getKeyUsingJNDI(String serviceName) {
    if (!isClassAvailable("javax.naming.Context")) {
      log.info("JNDI string lookups is not available.");
      return null;
    }
    try {
      Context context = new InitialContext();
      String lookupName = "watson-developer-cloud/" + serviceName + "/credentials";
      return (String) context.lookup(lookupName);
    } catch (NamingException e) {
      return null;
    }
  }
```
(there is another case of `javax` usage within the relationship extraction service `Dataset`, but this looks like a typo to me)

Ideally it would be best to remove `javax` to prevent this. 
It should be noted, however, that the current implementation works on API 21 and above.

**Comment by max-vogler** [comment]
Good find! The `javax` usage in `Dataset` is definitely a wrong auto-completion and unintended.

**Comment by max-vogler** [comment]
A simple solution would be to replace `NamingException` with `Exception` to catch all kinds of unexpected errors. Is there any reason speaking against it?

**Comment by Hsaylor** [comment]
No, I just first wanted to investigate completely removing `javax` first. Just using `Exception` for now is the most efficient fix we can do. Pull request #349

**Comment by germanattanasio** [comment]
@Hsaylor is it safe to say that after merging #349 we can close this issue ?

**Comment by Hsaylor** [comment]
Yep.
