### ISSUE TITLE
ServiceResponseException null pointer?

### ISSUE THREAD

**Issue by max-vogler** [watson-developer-cloud/java-sdk#348]
The [`ServiceResponseException`](https://github.com/watson-developer-cloud/java-sdk/blob/master/src/main/java/com/ibm/watson/developer_cloud/service/exception/ServiceResponseException.java) class is always assigning `null` to the `response` field. This is undocumented and looks like a bug.
 ```java
public ServiceResponseException(int statusCode, String message, Response response) {
    super(message);
    this.statusCode = statusCode;
    this.response = null;
  }
```

**Comment by germanattanasio** [comment]
We probably need to return response there...
