### ISSUE TITLE
[dialog] Java SDK version 3.* API not compatible with version 2.*

### ISSUE THREAD

**Issue by tomking1988** [watson-developer-cloud/java-sdk#353]
After I migrated from Java SDK 2.7 to 3.0.1, a lot of original API failed.
For example:
DialogService.CONVERSATION_ID become private and the following API is not applicable:
 public Conversation converse(final Map<String, Object> params) 

This discrepancy is really disappointing. And no guidance offered to help migrate.
Please do update document to help user migrate from version 2 to version 3:
http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/dialog/api/v1/#

**Comment by germanattanasio** [comment]
Hi @tomking1988 take a look at the [README](https://github.com/watson-developer-cloud/java-sdk#breaking-changes-for-v30)
