### ISSUE TITLE
DocumentConversion(String) constructor neglects API endpoint from VCAP_SERVICES

### ISSUE THREAD

**Issue by craigeebach** [watson-developer-cloud/java-sdk#377]
The com.ibm.watson.developer_cloud.document_conversion.v1.DocumentConversion.DocumentConversion(String) constructor replaces the API endpoint set by its super class WatsonService with a hardcoded value.  The WatsonService(String) constructor correctly sets the API URL endpoint based on what is defined by VCAP_SERVICES.  But after this endpoint is set in the super class constructor, the DocumentConversion(String) constructor sets it back to a hardcoded value.  

It is possible to workaround with code like this:
```
		DocumentConversion dc = new DocumentConversion("2015-12-15");
		String url = com.ibm.watson.developer_cloud.util.CredentialUtils.getAPIUrl("document_conversion");
		if (url != null && !url.isEmpty()) {
			dc.setEndPoint(url);
		}
```
 
java-sdk version:

```
        <dependency>
            <groupId>com.ibm.watson.developer_cloud</groupId>
            <artifactId>java-sdk</artifactId>
            <version>3.0.1</version>
        </dependency>
```

I'm Using JDK 8

**Comment by germanattanasio** [comment]
fixed in #404
