### ISSUE TITLE
[STT] audio file null or does not exist

### ISSUE THREAD

**Issue by shreyasi10080** [watson-developer-cloud/java-sdk#378]
Code:

final SpeechToText service = new SpeechToText();
    service.setUsernameAndPassword("<username>", "<password>");

    final File audio = new File("src/test/resources/sample1.wav");
    final SpeechResults transcript = service.recognize(audio, HttpMediaType.AUDIO_WAV);

    System.out.println(transcript);

Getting the following error:
07-13 13:19:19.566 7235-7235/com.ibm.watson.developer_cloud.android.myapplication W/System.err: java.lang.IllegalArgumentException: audio file is null or does not exist
07-13 13:19:19.571 7235-7235/com.ibm.watson.developer_cloud.android.myapplication W/System.err:     at com.ibm.watson.developer_cloud.util.Validator.isTrue(Validator.java:40)
07-13 13:19:19.571 7235-7235/com.ibm.watson.developer_cloud.android.myapplication W/System.err:     at com.ibm.watson.developer_cloud.speech_to_text.v1.SpeechToText.recognize(SpeechToText.java:268)
07-13 13:19:19.571 7235-7235/com.ibm.watson.developer_cloud.android.myapplication W/System.err:     at com.ibm.watson.developer_cloud.speech_to_text.v1.SpeechToText.recognize(SpeechToText.java:319)
07-13 13:19:19.571 7235-7235/com.ibm.watson.developer_cloud.android.myapplication W/System.err:     at com.ibm.watson.developer_cloud.speech_to_text.v1.SpeechToText.recognize(SpeechToText.java:299)

audio.exists() returns false. Tried various combinations of file path none of them are working.
Please help!

**Comment by max-vogler** [comment]
Hey @shreyasi10080! That code only works if you clone the GitHub repo. If you use the Watson Java SDK as Maven, Gradle or Jar dependency, the file won't be found. You can download [sample1.wav](https://raw.githubusercontent.com/watson-developer-cloud/java-sdk/master/src/test/resources/speech_to_text/sample1.wav) manually into your project folder and change your code like this:

```java
File audio = new File("sample1.wav");
```

**Comment by germanattanasio** [comment]
This is working but not release yet
