### ISSUE TITLE
"Unauthorized: Access is denied due to invalid credentials" Conversation Service

### ISSUE THREAD

**Issue by ysfAskri** [watson-developer-cloud/java-sdk#379]
I use a correct credential and workspace id but the response **status: 500** and the message is : **"Unauthorized: Access is denied due to invalid credentials"**
this is the screenshots:
~~CodeJava~~
~~ServiceCredential~~
~~WorkSpaceId~~
[Request](https://postimg.org/image/odfgbx6tj/)
[Response](https://postimg.org/image/e0t5pudaf/)

**Note: I use Conversation of Watson Section not on the catalog lab**

**Comment by max-vogler** [comment]
I removed the screenshots containing your credentials. The underlying problem is that the Java SDK still uses the `conversation-experimental` endpoint, while your credentials are valid for the `conversation` endpoint.

You can change your code like this until we push a fix:
```java
ConversationService service = new ConversationService(ConversationService.VERSION_DATE_2016_05_19);
service.setUsernameAndPassword("<username>", "<password>");
service.setEndPoint("https://gateway.watsonplatform.net/conversation/api");

MessageRequest newMessage = new MessageRequest.Builder().inputText("Hi").build();
MessageResponse response = service.message("<workspace-id>", newMessage).execute();
System.out.println(response);
```

**Comment by bujjiphani** [comment]
I have a similar problem.
conversation = ConversationV1(
  version = '2016-09-20',
  username = "{myuser}",
  password = '{mypass}',
  url = 'https://gateway.watsonplatform.net/conversation/api/v1'
)

How do I get to know the correct version that I should use?
I created my instance and workspace yesterday!
