### ISSUE TITLE
cannot get "word_alternatives" from the result by using java sdk

### ISSUE THREAD

**Issue by Focuson-github** [watson-developer-cloud/java-sdk#382]
I want get "word_alternatives" from the result by using java sdk, but it does not work. Thus, i add some code to get "word_alternatives". May I add some code to java sdk. Looking forward to your reply.

**Comment by max-vogler** [comment]
You're welcome to add your code! Feel free to open a pull request.

**Comment by Focuson-github** [comment]
I want to pull request, but when i push my code, the client show me a message:  "ERROR: Permission to watson-developer-cloud/java-sdk.git denied to Focuson-github."  how can i push my code?

**Comment by germanattanasio** [comment]
based on #391  seems like you realized how to write a pull request
