### ISSUE TITLE
[Conversation] - MessageResponse.getText() returns string enclosed with square brackets `[]`

### ISSUE THREAD

**Issue by ugrani** [watson-developer-cloud/java-sdk#392]
### java-sdk version - 3.0.1

**Comment by ugrani** [comment]
Hello - I just realized that, the code has already been changed to accommodate the response text messages as an array (public List<String> getText()).  But the maven repository (latest 3.0.1) is not updated (https://mvnrepository.com/artifact/com.ibm.watson.developer_cloud/java-sdk/3.0.1).

**Comment by germanattanasio** [comment]
@ugrani while we prepare the next release you can use the SNAPSHOT version from sonatype 
https://oss.sonatype.org/content/repositories/snapshots/com/ibm/watson/developer_cloud/java-sdk/

**Comment by germanattanasio** [comment]
I'm closing this since the work was completed. it just wasn't released yet
