### ISSUE TITLE
STT getModels does not return full data

### ISSUE THREAD

**Issue by lagarwalla** [watson-developer-cloud/java-sdk#393]
The actual STT getModel service returns 5 fields:
"url": "https://stream.watsonplatform.net/speech-to-text/api/v1/models/en-US_NarrowbandModel",
 "rate": 8000,
 "name": "en-US_NarrowbandModel",
 "language": "en-US",
 "description": "US English narrowband model."

But the SDK's STT getModels() method only returns "rate" and "name". We have use case where we need "description" also.

getModels() should be returning all 5 fields and not trim the data.

**Comment by germanattanasio** [comment]
fixed
