### ISSUE TITLE
TTS synthesize() does not accept "audio/l16" or "audio/basic"

### ISSUE THREAD

**Issue by lagarwalla** [watson-developer-cloud/java-sdk#394]
TTS synthesize() does not accept "audio/l16" or "audio/basic". 

The 'new AudioFormat("audio/l16")' is not public, so can not create new AudioFormat using string.

**Comment by rafspiny** [comment]
There is no AudioFormat for "audio/ogg; codec=vorbis" as well.

This is limiting API usage on old Android version that do not handle the default ogg codec opus.
It would be nice to see it. I am facing this issue on a Galaxy Nexus with Android 4.3

**Comment by germanattanasio** [comment]
@Hsaylor is this something you think we can have in the android-sdk ?

**Comment by rafspiny** [comment]
@germanattanasio I forgot to specify that in my particular case, I have built an API, deployed on Bluemix with Liberty for Java, that process a text and then return a synthesized text in response using the TTS service.
I am not really using the android-sdk

Thank you for looking into this.

**Comment by lagarwalla** [comment]
Can the AudioFormat constructor be made public so that in future string can be passed to for new formats ?

**Comment by germanattanasio** [comment]
It's private because the service allows a fixed number of audio formats so there is no need to make it public. I know that in this case I forgot about 3 important formats but hopefully that will not happen again.
