### ISSUE TITLE
AlchemyLanguage getLanguage() not accepting String with less than 15 characters.

### ISSUE THREAD

**Issue by akosialz** [watson-developer-cloud/java-sdk#397]
Using this code block:

(type of variable **al** is AlchemyLanguage; length of message is < 15):
```java
Map<String, Object> params = new HashMap<>();
params.put(AlchemyLanguage.TEXT, message);
String language = al.getLanguage(params).execute().getIso6393();
```
Whenever I execute the getLanguage() from **al**,
the error pops out stating that

com.ibm.watson.developer_cloud.service.exception.BadRequestException: not-enough-text-for-language-id

And after a thorough investigation found out that we need at least 15 characters (white spaces not included) in order to execute getLanguage().

**Comment by germanattanasio** [comment]
I'm closing this one @akosialz feel free to open if you think this is a problem in the SDK
