### ISSUE TITLE
[Text To Speech] TTS speech Customisation_ID expected in synthesize 

### ISSUE THREAD

**Issue by jackleekopij** [watson-developer-cloud/java-sdk#426]
Grabbing Java-SDK 3.3.0 in Maven expects Customization_ID when calling synthesize. Should this be optional? This change broke a previous project.

![img_0480](https://cloud.githubusercontent.com/assets/20328608/17711923/5f17ff0c-63b9-11e6-87e5-24f568fec9d2.JPG)

**Comment by germanattanasio** [comment]
Depending on which version you were using before. We switched to use `AudioFormat` instead of a String. Check the  `examples` folder
