### ISSUE TITLE
[Document Conversion Service JDK API] omit Parent ID missing from the answer units  

### ISSUE THREAD

**Issue by christianIreland** [watson-developer-cloud/java-sdk#428]
When using the Watson SDK-API to submit documents to the Document Conversion Service, the Answer Units generated are missing the Parent ID.

The issue is easily reproducible, just by using the Watson SDK. A snippet of code is reported below:
```java
private Answers convertDocumentToAnswer(File document,  String mediaType) throws FileNotFoundException {
		ServiceCall<Answers> answersCall;
		JsonObject dcsConfigJson = loadDCSConfiguration();
		answersCall = getCoversionService().convertDocumentToAnswer(document, mediaType, dcsConfigJson);
		return answersCall.execute();
	}
```

The issue is reproducible in all the JDK versions available. 
Java SDK version is `1.8.0_101`

Apparently, the reason why the issue is happening is the ParentID field missing from the class Answer part of Answers

**Comment by christianIreland** [comment]
an example of the conversion is reported below:

{
  "answer_units": [
    {
      "content": [
        {
          "media_type": "text/html",
          "text": "\u003cp\u003ethis is the first chapter\u003c/p\u003e"
        },
        {
          "media_type": "text/plain",
          "text": "this is the first chapter"
        }
      ],
      "id": "cdf93476-f4ba-40eb-af1e-cdf96bb19ff0",
      "title": "First Chapter",
      "type": "h1"
    },
    {
      "content": [
        {
          "media_type": "text/html",
          "text": "\u003cp\u003ethis is the second chapter\u003c/p\u003e"
        },
        {
          "media_type": "text/plain",
          "text": "this is the second chapter"
        }
      ],
      "id": "d19d0ef9-ec74-4816-b48a-82bb76e8568b",
      "title": "Second Chapter",
      "type": "h1"
    }
  ],
  "source_document_id": "",
  "timestamp": "2016-08-19T08:16:37.163+0100"
}

**Comment by christianIreland** [comment]
the issue was closed by mistake

**Comment by SirSpidey** [comment]
Thanks @christianIreland.
Looks like `direction` might also be missing from `Answers.AnswerUnits`
