### ISSUE TITLE
Where is Relationship Extraction?

### ISSUE THREAD

**Issue by sergiofigueras** [watson-developer-cloud/java-sdk#432]
Hello guys,

I was using 2.8.0 version, and now I'm moving for 3.3.0. But I realized that I was using import com.ibm.watson.developer_cloud.relationship_extraction.v1.RelationshipExtraction

Where is that functionality now?

**Comment by sergiofigueras** [comment]
Ok, found it in WatsonService. Thanks.

**Comment by germanattanasio** [comment]
Relationship Extraction was deprecated. See http://www.ibm.com/watson/developercloud/doc/sireapi/

The service was integrated into AlchemyLanguage so you will have to do some changes to your code.
