### ISSUE TITLE
SpeechToText sending inputstream in chunks

### ISSUE THREAD

**Issue by nadworny** [watson-developer-cloud/java-sdk#434]
We are implementing a following use case using Java's SpeechToText Watson service: 
- Client opens a socket and streams an audio stream to it 
- Server waits for connection and as soon it's established it forwards the audio stream to SpeechToText using recognizeUsingWebSocket method

Using the java.net.ServerSocket it can be implemented but this approach requires to define a port for the ServerSocket which when deployed to an application / web server (Liberty / Tomcat) won't be available to the outside world (only 80/443/4443 are accessible) on Bluemix. The only way we found out to be able to use a web server for that is the WebSocket API but this doesn't allow for streaming the data; the only way to send an audio stream would be to split it into chunks. 

That would be fine but the Java's SpeechToText library unfortunately doesn't accept chunks of data within the same session (only files & inputstream are supported). To be able to to use this approach I would have to re-engineer the existing SpeechToText library which I would rather not do... Funnily enough the Javascript's SpeechToText library seems to support streams and writing chunks of data to it. 

Do you have an idea how we could approach this problem using Java? Do you plan to support writing chunks of data in Java's SpeechToText library anytime soon the same way you support it for Javascript?

**Comment by nadworny** [comment]
Hi guys,

Any news on that one? We are in the middle of project and would need to go forward...

**Comment by germanattanasio** [comment]
The `recognize` method accepts an `InputStream` you can use a `BufferedInputStream` and write to that buffer whenever you have data. The `read()` method will block the thread until you have more data.

I don't think there is a problem here. What you do with JavaScript can be done with this SDK without changes.

**Comment by nadworny** [comment]
Thanks for the answer but maybe I haven't made my point quite clear or I simply don't understand your suggestion... 

You are proposing to use a BufferedInputStream with an AudioInputStream as an argument of the constructor? This won't solve the main problem that we have - how to transfer that stream from the client to the server in byte chunks over WebSocket and then transform it into an InputStream which will be provided to the recognize method? Once again - recognize is happening on a server side and recording on a client side.

**Comment by androidfanatic** [comment]
@nadworny did you find a solution? I used a connected PipedInputStream and PipedOutputStream to stream byte buffers to STT websocket but I'd like to see if there are other approaches.

**Comment by germanattanasio** [comment]
I read this issue like 10 times and I'm still unable to understand the use case 😢 , @nadworny can you give me an example and also what you are doing now as a workaround.

**Comment by germanattanasio** [comment]
Closed due to inactivity.
