### ISSUE TITLE
Decoding delay for MicrophoneWithWebSocketsExample

### ISSUE THREAD

**Issue by afaisma** [watson-developer-cloud/java-sdk#437]
Decoding is delayed for speech with no pauses for MicrophoneWithWebSocketsExample 
To reproduce the problem - cc hltu004.watson.ibm.com/u/faisman/longaudiofiles/sttworkload-0.0.1-SNAPSHOT.jar, and run:
java -jar sttworkload-0.0.1-SNAPSHOT.jar
Then do very quick counting from one to twelve and again, and again, without pauses. 
In my tests the delays could reach 60-90 seconds and probably more

Please note that the same speech is not delaying the transcription in  Bluemix demo at https://speech-to-text-demo.mybluemix.net/.

**Comment by germanattanasio** [comment]
Can you probably a way for us to reproduce your problem? We need the audio file and the java code you are using.

**Comment by afaisma** [comment]
I sent you the audio and the code in a separate email. If you can access hltu004.watson.ibm.com/u/faisman/longaudiofiles/sttworkload-0.0.1-SNAPSHOT.jar, you can get the build there.

**Comment by germanattanasio** [comment]
Which version of the SDK are you using?

**Comment by germanattanasio** [comment]
I need the code (without credentials), sdk version, jdk version, and audio file.
