### ISSUE TITLE
[Alchemy] AlchemyLanguage getCombinedResults call should be able to handle anchorDate as a parameter

### ISSUE THREAD

**Issue by roy713** [watson-developer-cloud/java-sdk#441]
Relates to #436.

Since `getCombinedResults` can handle `dates`, it should be able to process the `anchorDate` parameter, similar to how it is done in the `getDates` method.

For example,  you could add the same code that's in the `getDates` call to handle this parameter:
````java
    if (params.containsKey(ANCHOR_DATE) && params.get(ANCHOR_DATE) instanceof Date) {
      String anchorDate = anchorDateFormat.format(params.get(ANCHOR_DATE));
      paramsCopy.put(ANCHOR_DATE, anchorDate);
    }
````

You could also create a private method and reuse it in the `AlchemyLanguage` class.

**Comment by roy713** [comment]
@germanattanasio - it's worth noting that the `format` method access in the `SimpleDateFormat` is not thread-safe. You could wrap it in a `synchronized` block or something of the sort.

**Comment by germanattanasio** [comment]
That looks like a pretty easy change @roy713. Can you write a PR with that ?
