### ISSUE TITLE
Missing artifact com.ibm.watson.watson.developer_cloud:java-sdk:jar:3.4.0

### ISSUE THREAD

**Issue by ysfAskri** [watson-developer-cloud/java-sdk#451]
<dependency>
    <groupId>com.ibm.watson.watson.developer_cloud</groupId>
    <artifactId>java-sdk</artifactId>
    <version>3.4.0</version>
</dependency>

**Missing artifact com.ibm.watson.watson.developer_cloud:java-sdk:jar:3.4.0**

**Comment by ylassoued** [comment]
I was unable to use the latest release for the same reason as above... I was not able to use the source code in an Android project either... It would be great if someone could make this release available on Maven Central...

**Comment by ysfAskri** [comment]
i'm using the version of 3.3.1 it works for me 
until V 3.4.0 will be able

**Comment by germanattanasio** [comment]
I'm working on it but Maven central seems to be down :(

**Comment by germanattanasio** [comment]
Can you guys use the jar in the meantime ?

**Comment by germanattanasio** [comment]
You can also point to the snapshot repo https://oss.sonatype.org/content/repositories/snapshots/com/ibm/watson/developer_cloud/

**Comment by ysfAskri** [comment]
I'm waitiiing :D ..... 
Good Job  @germanattanasio ;)

**Comment by germanattanasio** [comment]
fixed

**Comment by ylassoued** [comment]
Brilliant! Thanks @germanattanasio!
