### ISSUE TITLE
Missing [Language Translator API] in 3.4.0 SDK

### ISSUE THREAD

**Issue by glaoup** [watson-developer-cloud/java-sdk#452]
Can't see the Language Translator Api inside SDK 3.4.0. Only Language Translation API is present

**Comment by glaoup** [comment]
Sorry, forgot to mention that the Language Translator API is missing on the java-sdk-3.4.0-jar-with-dependencies.jar file

**Comment by germanattanasio** [comment]
That change will be release with in `v3.4.0` You can get the SNAPSHOT from [sonatype](https://oss.sonatype.org/content/repositories/snapshots/com/ibm/watson/developer_cloud/java-sdk/3.4.1-SNAPSHOT/java-sdk-3.4.1-20160930.155842-2-jar-with-dependencies.jar).

See: https://oss.sonatype.org/content/repositories/snapshots/com/ibm/watson/developer_cloud/
