### ISSUE TITLE
Translator service

### ISSUE THREAD

**Issue by shikida** [watson-developer-cloud/java-sdk#468]
Using 3.5.0

Test #1

    	LanguageTranslator service = new LanguageTranslator();
    	service.setUsernameAndPassword("**", "**");
    	TranslationResult translationResult = service.translate(
    			  "Hello world", Language.ENGLISH, Language.SPANISH)
    			  .execute();
    	System.out.println(translationResult.getFirstTranslation());

result

"Hello world"

Test #2

    public static void main(String[] args){
    	LanguageTranslator service = new LanguageTranslator();
    	service.setUsernameAndPassword("**", "**");
    	TranslationResult translationResult = service.translate(
    			  "Hello world!", Language.ENGLISH, Language.SPANISH)
    			  .execute();
    	System.out.println(translationResult.getFirstTranslation());

result

"Hola!"

Test #3 

    	LanguageTranslator service = new LanguageTranslator();
    	service.setUsernameAndPassword("**", "**");
    	TranslationResult translationResult = service.translate(
    			  "Hello world world!", Language.ENGLISH, Language.SPANISH)
    			  .execute();
    	System.out.println(translationResult.getFirstTranslation());

response

"Hola mundo!"

I am not sure if it's a problem of the API or of this library. 

:-(

**Comment by germanattanasio** [comment]
it's not a problem in this Library. I will contact the service
