### ISSUE TITLE
The example for AlchemyDataNews has no setAPIKey method

### ISSUE THREAD

**Issue by remkohdev** [watson-developer-cloud/java-sdk#472]
The proper way to set the apikey is:

// call alchemyAPI Data News
AlchemyDataNews service = new AlchemyDataNews("<api_key>");

but in your example
https://github.com/watson-developer-cloud/java-sdk/blob/master/examples/java/com/ibm/watson/developer_cloud/alchemy_data_news/v1/GetNewsDocumentExample.java

it has setAPIKey("") method, which causes an error

**Comment by germanattanasio** [comment]
The method is defined in `WatsonService`. See https://github.com/watson-developer-cloud/java-sdk/blob/master/core/src/main/java/com/ibm/watson/developer_cloud/service/WatsonService.java#L323

The constructor also accept the API Key and calls the `setApiKey()` method.
