### ISSUE TITLE
Leaked connections in RnR

### ISSUE THREAD

**Issue by jsmodic** [watson-developer-cloud/java-sdk#485]
A customer says using the RetrieveAndRank client sometimes yields log messages like:
```
AVERTISSEMENT: A connection to https://gateway.watsonplatform.net/ was leaked. Did you forget to close a response body?
```
I think it's a matter of com.ibm.watson.developer_cloud.util.ResponseUtils not closing the okhttp Response body's in all situations, but it warrants further investigation.

**Comment by germanattanasio** [comment]
That's correct. We used to have this problem so I need to know if is happening in the last version fo the sdk or not.

**Comment by germanattanasio** [comment]
@jsmodic do you know which version of the SDK was the user using? I'm not able to replicate this on 3.8.0

**Comment by jsmodic** [comment]
I haven't heard anything of it again and no other customer has reported this, so we can probably consider this a closed issue for now.
