### ISSUE TITLE
[text-to-speech] The service supports a WebSocket interface

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/java-sdk#502]
The Text to Speech service, like Speech to Text, supports a WebSocket interface. For Text to Speech, the WS interface provides extra functionality not available with the HTTP REST interface, specifically use of the SSML tag and word timing output. This interface should also be available from the Java SDK.

**Comment by yeta-io** [comment]
Upvote

**Comment by germanattanasio** [comment]
I can work on this during probably next week

**Comment by yeta-io** [comment]
Thanks,

I have already implementation done using websockets, but I'd like to have official api.

**Comment by froesmatheus** [comment]
Hi, any news about the Websocket implementation? @germanattanasio

**Comment by germanattanasio** [comment]
I didn't have time to work on it. @yeta-io do you think you could write a PR?

**Comment by lpatino10** [comment]
Added in [v6.10.0](https://github.com/watson-developer-cloud/java-sdk/wiki/Changelog#version-6110) 🎉
