### ISSUE TITLE
[speech-to-text] Integration tests are not deleting custom language models

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/java-sdk#503]
From: @nfriedly:
```
hey, there are like a hundred `IEEE-java-sdk-permanent` customizations
for speech to text
I think some code is creating those that shouldn't be
(The node SDK's integration test automatically nukes
anything that doesn't have the word `permanent` in the
name and is > 1 day old before running it's tests - so
the Java SDK may well be leaving behind temporary ones too.) 
```

**Comment by jeffpk62** [comment]
German, I can address this one for you.  Just let me know.

**Comment by germanattanasio** [comment]
Yes please, assign the issues to you and you are set.

**Comment by jeffpk62** [comment]
@germanattanasio, the integration test already had a finally clause that deleted the custom model.  The 140 models that existed were from December and January.  I did the following:

- Updated the name and description of the IT custom model to indicate that it's temporary.  Otherwise, the IT code is already good.
- Verified that the STT tests all pass without the old models and that we're not leaking any new models.
- Deleted 135 of the old custom models.  Five of the models are from early December but are in a locked state that prevents their deletion.  I will follow up with the Speech team.  The five that remain are all safe to delete, and they all generate the following conflict exception in response to attempted deletion:

```
Deleting: js-sdk-test-temporary
Feb 15, 2017 2:42:05 PM com.ibm.watson.developer_cloud.service.WatsonService processServiceCall
SEVERE: DELETE https://stream.watsonplatform.net/speech-to-text/api/v1/customizations/526fe850-
c093-11e6-9657-e53f14d32a55, status: 409, error: Customization '526fe850-c093-11e6-9657-e53f14d32a55'
is currently locked to process your last request.
com.ibm.watson.developer_cloud.service.exception.ConflictException: Customization '526fe850-
c093-11e6-9657-e53f14d32a55' is currently locked to process your last request.
        at com.ibm.watson.developer_cloud.service.WatsonService.processServiceCall(WatsonService.java:426)
        at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:180)
        at com.ibm.watson.developer_cloud.speech_to_text.v1.delete.main(delete.java:34)
```

At this point, this can probably be closed, since no further changes are need to the SDK.

**Comment by jeffpk62** [comment]
The Speech team is looking into deleting the locked models.  We can't do anything with them.

**Comment by germanattanasio** [comment]
You have the credentials so I think you can delete them

**Comment by jeffpk62** [comment]
@germanattanasio, you would think, but unfortunately, I can't.  I used the credentials to delete the other 135 models fine.  But these five are stuck in a strange locked state that generates the conflict error above.  

```
[{
  "customization_id": "cd7ed480-b804-11e6-b9f2-8b43fbcefce6",
  "created": "2016-12-01T20:29:04.840",
  "language": "en-US",
  "owner": "8a6f5bb1-5b2d-4a20-85a9-eaa421d25c88",
  "name": "js-sdk-test-temporary",
  "description": "Temporary customization to test the JS SDK. Should be automatically deleted within a few minutes.",
  "base_model_name": "en-US_BroadbandModel",
  "status": "pending",
  "progress": 0
}, {
  "customization_id": "d83fab10-b804-11e6-adcf-c7643de6fea4",
  "created": "2016-12-01T20:29:22.881",
  "language": "en-US",
  "owner": "8a6f5bb1-5b2d-4a20-85a9-eaa421d25c88",
  "name": "js-sdk-test-temporary",
  "description": "Temporary customization to test the JS SDK. Should be automatically deleted within a few minutes.",
  "base_model_name": "en-US_BroadbandModel",
  "status": "training",
  "progress": 0
}, {
  "customization_id": "970feba0-c092-11e6-9657-e53f14d32a55",
  "created": "2016-12-12T17:44:11.354",
  "language": "en-US",
  "owner": "8a6f5bb1-5b2d-4a20-85a9-eaa421d25c88",
  "name": "js-sdk-test-temporary",
  "description": "Temporary customization to test the JS SDK. Should be automatically deleted within a few minutes.",
  "base_model_name": "en-US_BroadbandModel",
  "status": "pending",
  "progress": 0
}, {
  "customization_id": "99bc46f0-c092-11e6-adcf-c7643de6fea4",
  "created": "2016-12-12T17:44:15.839",
  "language": "en-US",
  "owner": "8a6f5bb1-5b2d-4a20-85a9-eaa421d25c88",
  "name": "js-sdk-test-temporary",
  "description": "Temporary customization to test the JS SDK. Should be automatically deleted within a few minutes.",
  "base_model_name": "en-US_BroadbandModel",
  "status": "training",
  "progress": 0
}, {
  "customization_id": "526fe850-c093-11e6-9657-e53f14d32a55",
  "created": "2016-12-12T17:49:25.717",
  "language": "en-US",
  "owner": "8a6f5bb1-5b2d-4a20-85a9-eaa421d25c88",
  "name": "js-sdk-test-temporary",
  "description": "Temporary customization to test the JS SDK. Should be automatically deleted within a few minutes.",
  "base_model_name": "en-US_BroadbandModel",
  "status": "pending",
  "progress": 0
}]
```

The service had an issue with this in the past, and I think these predate the fix.  They're following up for me.

**Comment by jeffpk62** [comment]
@germanattanasio, Tony sent the following:

`OK, I cleared those 5 models.  You should now be able to delete them, let me know if you are successful now.`

And I was able to clear the last five models.  We're clean now.

**Comment by balakrishnanitw** [comment]
{
   "owner": "5b65fb45-5c04-4381-b4d7-9f778a89ff6e",
   "base_model_name": "en-US_BroadbandModel",
   "customization_id": "1cd859d1-a522-4001-b8e0-e3e3637b48e1",
   "versions": ["en-US_BroadbandModel.v2017-11-15"],
   "created": "2018-05-18T10:07:39.606Z",
   "name": "EVA acoustic model",
   "description": " VOICE EVA custom acoustic model",
   "progress": 0,
   "language": "en-US",
   "error": "{\"code\":500,\"code_description\":\"Internal Server Error\",\"error\":\"<2018-05-23 11:12:21,856 src/binary-io.cc:47>\\tRD_ERROR\\tInput::Input cannot stat \\\"/tmp/tmpx6l64v/rapidOut/fea.1187.bin\\\" (No such file or directory)\\n\"}",
   "status": "failed"
}

training getting failed...any help pls?
