### ISSUE TITLE
[speech-to-text] Interim results not returned with recognize() method

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/java-sdk#504]
The recognize() method does not return interim results when the interimResults parameter is set to true in sessionless mode.  Instead, the output is identical to omitting the parameter.  We currently document that the parameter is supported and will return interim results.  The method should probably return interim results with the final results, all at once, as the service does.  Alternatively, the documentation could be updated to say that the parameter is a no-op outside of a session.  Which would you prefer?

**Comment by jeffpk62** [comment]
Note also that interim results are not return from within a session, either.  Apparently, the parameter is not functioning either with or without a session.  But it is supported as a viable parameter in both cases.  Also, the Java SDK does not support the equivalent of an observeResult() method, as the HTTP REST and Node interfaces do.

**Comment by germanattanasio** [comment]
We don't support interim results in HTTP because you need to do 2 HTTP calls to get them. We encourage users to use the WebSocket connection for that.

**Comment by jeffpk62** [comment]
So no interim_results with HTTP sessionless or session-based calls?  OK, I'll update the documentation accordingly; thanks.

**Comment by jeffpk62** [comment]
@germanattanasio, I updated the docs to say that Java supports interim results only with WebSockets and that the `interimResults` parameter is a no-op for non-WebSocket requests.  It would probably be good to add a caveat to the documentation for the `interimResults` parameter of the `RecognizeOptions `object saying that it's supported only with the `recognizeUsingWebSocket()` method.
