### ISSUE TITLE
[discovery] Add Timeslice Aggregation

### ISSUE THREAD

**Issue by maniax89** [watson-developer-cloud/java-sdk#513]
### Description

**Feature Request**: Add in the `timeslice` aggregation enum for a discovery `QueryRequest` . The spec can be found at http://www.ibm.com/watson/developercloud/doc/discovery/query-reference.shtml#aggregrations

Excerpt:

> A specialized histogram that uses dates to create interval segments. Valid date interval values are minute, hour, day, week, month, and year. The syntax is timeslice(<interval>) and timeslice(<field>,<interval>). In order to use timeslice, the time fields in your documents have to be converted into a date data type in the JSON. So you can create a timeslice if there's a "date", "publicationDate", or something similar, but you can't create it if there's just a date in the text. This example returns intervals of 1 day.

Example:
```
timeslice(my_time_field,1day)
```
### Solution

- [ ] add `TIMESLICE` to the `AggregationType` enum in the `com.ibm.watson.developer_cloud.discovery.v1.model.query` package.
- [ ] create the proper deserialization of the response in the `com.ibm.watson.developer_cloud.discovery.v1.model.query.QueryAggregationAdapterFactory` class as well as create the appropriate models that extend the `com.ibm.watson.developer_cloud.discovery.v1.model.query.NestableAggregation` class (see `Histogram` aggregation for example)
- [ ] write a test that ingests a JSON document with a date and then uses the new `TIMESLICE` aggregation to create time-specific histogram

### When you open an issue for a feature request, please add as much detail as possible:
- [x] A descriptive title starting with the service name
- [X] A description of the problem you're trying to solve
- [X] A suggested solution if possible

**Comment by stanleywym** [comment]
+1
