### ISSUE TITLE
[discovery] Rename 'json' to 'json_normalizations' in Configuration

### ISSUE THREAD

**Issue by maniax89** [watson-developer-cloud/java-sdk#517]
### Description

Users are unable to create a configuration with json normalization operations because the serialized name is incorrect.

### Steps to reproduce

1. Create a configuration file with some json normalization, example:
    ```json
    {
      "name": "my_config",
      "conversions": {
        "json_normalizations": [
          {
            "operation": "copy",
            "source_field": "some_field",
            "destination_field": "other_field"
          }
        ]
    }
    ```
1. Read in the file with the SDK
    ```java
     Configuration config = GsonSingleton.getGson().fromJson(new FileReader("/path/to/config-file.json"), Configuration.class);
    ```
1. Attempt to create a configuration
    ```java
    Discovery discovery = new Discovery("2016-12-15");
    discovery.setEndpoint("https://gateway.watsonplatform.net/discovery/api");
    discovery.setUsernameAndPassword("my_username", "my_password");
    String environmentId = "my_environment_id";
    CreateConfigurationRequest.Builder createBuilder = new CreateConfigurationRequest.Builder(environmentId);
     createBuilder.configuration(config);
     CreateConfigurationResponse createResponse = discovery.createConfiguration(createBuilder.build()).execute();
    ```
1. Expected config is not returned on GET requests:
    ```java
    GetConfigurationRequest getRequest = new GetConfigurationRequest.Builder(environmentId).build();
    GetConfigurationResponse getResponse = discovery.getConfiguration(getRequest).execute();
    System.out.println(getResponse); //does not have expected config, should be same as above with 'conversions.json_normalizations' key
    ```

### Solution
- [ ] change the `@SerializedName` annotation to `json_normalizations` in `com.ibm.watson.developer_cloud.discovery.v1.model.configuration.Conversions`
- [ ] write a test with a sample configuration like above and a test document

### When reporting a bug, please be sure to include the following:

- [X] Start the title with the service name in brackets:  `[speech-to-text] websockets...`
- [X] Steps to reproduce
- [X] Expected behavior
- [X] Actual behavior
- [X] JDK version (1.8.0_71 IBM)
- [X] java-sdk version (3.5.3)

**Comment by Mikemosca** [comment]
@maniax89 - hi Andrew

Is the configuration schema defined anywhere in the documentation?  Your test case works if you use "json" instead of "json_normalizations".  I just want to make sure the schema calls for "json_normalizations" before I change it.  Thanks!

<pre>
{
  "name": "my_config",
  "conversions": {
    "json_normalizations": [
      { ...

</pre>

**Comment by maniax89** [comment]
yes it calls for `json_normalizations` - see here https://watson-api-explorer.mybluemix.net/apis/discovery-v1#!/Configurations/get_v1_environments_environment_id_configurations_configuration_id

**Comment by Mikemosca** [comment]
Thanks, I was looking in the API reference.

**Comment by Mikemosca** [comment]
In review - https://github.com/watson-developer-cloud/java-sdk/pull/597
