### ISSUE TITLE
[discovery] Make configuration NormalizationOperation operation into enum

### ISSUE THREAD

**Issue by maniax89** [watson-developer-cloud/java-sdk#518]
### Description
**Feature Request**: Enumerate the possible values of the `operation` in `com.ibm.watson.developer_cloud.discovery.v1.model.configuration.NormalizationOperation`. See valid options at https://watson-api-explorer.mybluemix.net/apis/discovery-v1#!/Configurations/post_v1_environments_environment_id_configurations:

> copy - Copies the value of the source_field to the destination_field field. If the destination_field already exists, then the value of the source_field overwrites the original value of the destination_field.
> 
> move - Renames (moves) the source_field to the destination_field. If the destination_field already exists, then the value of the source_field overwrites the original value of the destination_field. Rename is identical to copy, except that the source_field is removed after the value has been copied to the destination_field (it is the same as a copy followed by a remove).
> 
> merge - Merges the value of the source_field with the value of the destination_field. The destination_field is converted into an array if it is not already an array, and the value of the source_field is appended to the array. This operation removes the source_field after the merge. If the source_field does not exist in the current document, then the destination_field is still converted into an array (if it is not an array already). This is ensures the type for destination_field is consistent across all documents.
> 
> remove - Deletes the source_field field. The destination_field is ignored for this operation.
> 
> remove_nulls - Removes all nested null (blank) leif values from the JSON tree. source_field and destination_field are ignored by this operation because remove_nulls operates on the entire JSON tree. Typically, remove_nulls is invoked as the last normalization operation (if it is inoked at all, it can be time-expensive). = ['copy', 'move', 'merge', 'remove', 'remove_nulls'],

### Solution

- [ ] Make the string into an enum in the `NormalizationOperation` class
- [ ] write a test that uses the `GetConfigurationRequest` and verify the response deserializes the operations appropriately

### When you open an issue for a feature request, please add as much detail as possible:
- [X] A descriptive title starting with the service name
- [X] A description of the problem you're trying to solve
- [X] A suggested solution if possible

**Comment by Mikemosca** [comment]
in review - https://github.com/watson-developer-cloud/java-sdk/pull/601
