### ISSUE TITLE
[discovery] Conform Enrichment options to spec

### ISSUE THREAD

**Issue by maniax89** [watson-developer-cloud/java-sdk#519]
### Description

**Feature Request**: Configuration enrichment options for Discovery do not give much information on what you can do. Use the spec at https://watson-api-explorer.mybluemix.net/apis/discovery-v1#!/Configurations/post_v1_environments_environment_id_configurations to determine appropriate models

> EnrichmentOptions {
> extract (string, optional):
> 
> A comma sepeated list of analyses that should be applied when using the alchemy_language enrichment. See the the service documentation for details on each extract option.
> 
> Possible values include:
> 
>     entity
>     keyword
>     taxonomy
>     concept
>     relation
>     doc-sentiment
>     doc-emotion
>     typed-rels
> 
> ,
> sentiment (boolean, optional),
> quotations (boolean, optional),
> showSourceText (boolean, optional),
> hierarchicalTypedRelations (boolean, optional),
> model (string, optional):
> 
> Required when using the typed-rel extract option. Should be set to the ID of a previously published custom Watson Knowledge Studio model. ,
> language (string, optional):
> 
> If provided, then do not attempt to detect the language of the input document. Instead, assume the language is the one specified in this field.
> 
> You can set this property to work around unsupported-text-language errors.
> 
> Supported languages include English, German, French, Italian, Portuguese, Russian, Spanish and Swedish. Supported language codes are the ISO-639-1, ISO-639-2, ISO-639-3, and the plain english name of the language (e.g. "russian"). = ['english', 'german', 'french', 'italian', 'portuguese', 'russian', 'spanish', 'swedish', 'en', 'eng', 'de', 'ger', 'deu', 'fr', 'fre', 'fra', 'it', 'ita', 'pt', 'por', 'ru', 'rus', 'es', 'spa', 'sv', 'swe']
> }

### Solution
- [ ] change the `Map<String, Object> options` in the `com.ibm.watson.developer_cloud.discovery.v1.model.configuration.Enrichment` to conform to the EnrichmentOption model
- [ ] write a test that utilizes the deserialization of the config (`GetConfigurationRequest`)

### When you open an issue for a feature request, please add as much detail as possible:
- [X] A descriptive title starting with the service name
- [X] A description of the problem you're trying to solve
- [X] A suggested solution if possible

**Comment by lihuiniu** [comment]
@maniax89 This is Hui, could you do tell me how can I add the "language": "english" via IBM Watson online tooling? I tried multiple times still not sure how to do right using the online-created configuration file?

**Comment by maniax89** [comment]
@lihuiniu there isn't a way to modify many of the enrichment options exposed in the tooling as of right now. In the tooling, users can only specify `source_field` (we generate the `destination_field`for them) + the enrichment `options.extract` value -> see https://watson-api-explorer.mybluemix.net/apis/discovery-v1#!/Configurations/getConfiguration for the references

For the java-sdk, the `options` field is just a generic map. this issue is meant to make it less generic and instead make it have the same model specified in the API documentation
