### ISSUE TITLE
[discovery] Update example in Readme 

### ISSUE THREAD

**Issue by vermavikrant** [watson-developer-cloud/java-sdk#525]
### Description:
The usage example given in Readme of Discovery service needs update.
Direct Link: https://github.com/watson-developer-cloud/java-sdk/blob/master/discovery/README.md 

### Explanation
The first 3 lines for Usage example needs to be changed,
#### From:
```
Discovery service = new Discovery("2016-12-15");
service.setEndpoint("https://gateway.watsonplatform.net/discovery/api/");
service.setUsernameAndPassword("<username>", "<password>");
```
#### To:
```
Discovery discovery = new Discovery("2016-12-15");
discovery.setEndPoint("https://gateway.watsonplatform.net/discovery/api/");
discovery.setUsernameAndPassword("<username>", "<password>");
```
#### Changes: 
```
object name changed from 'service' to 'discovery'
line2: method name changed from 'setEndpoint' to 'setEndPoint'
```
#### Optional Changes: 
The version date Discovery object using (2016-12-15) can be updated to latest version date being used.

### When reporting a bug, please be sure to include the following:

- [x] Start the title with the service name in brackets:  `[speech-to-text] websockets...`
- [x] Steps to reproduce (not required)
- [x] Expected behavior (not required)
- [x] Actual behavior (not required)
- [x] JDK version (not required)
- [x] java-sdk version (3.5.3)

**Comment by germanattanasio** [comment]
fixied
