### ISSUE TITLE
[Alchemy Language] CombinedResults missing Emotion

### ISSUE THREAD

**Issue by cfrasineanu-intx** [watson-developer-cloud/java-sdk#545]
According to https://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#combined-call one can get the emotion analysis via the Combined Calls method, but the CombinedResults object returned by AlchemyLanguage#getCombinedResults does not have a method to get the emotion analysis results.
I am using java-sdk 3.5.3

**Comment by josepmao** [comment]
@germanattanasio can you help check this one?  from the api reference, combined-call method should support emotion with "doc-emotion", which not working now.
There is no emotion in class CombinedResults at all

**Comment by germanattanasio** [comment]
The service was deprecated Josep can you use natural language understanding
?

**Comment by josepmao** [comment]
get it.  Thanks @germanattanasio for the info

**Comment by cfrasineanu-intx** [comment]
Thanks @germanattanasio. We can close this issue as OBE

**Comment by germanattanasio** [comment]
I'm going to leave it open and see if someone can actually add emotion. it should be an easy fix but it's not a priority now
