### ISSUE TITLE
[discovery] Add Filter Aggregation

### ISSUE THREAD

**Issue by JamieGilbertIBM** [watson-developer-cloud/java-sdk#582]
**Description**

Feature Request: Add in the filter aggregation enum for a discovery QueryRequest . The spec can be found at http://www.ibm.com/watson/developercloud/doc/discovery/query-reference.shtml#aggregrations

Excerpt:

> Most often used in a combined query, and it filters the aggregation results using the query language syntax. This example filters results by the concept Pharmacovigilance.

Example:

`filter(enriched_text.concepts.text:Pharmacovigilance)`

**Solution**

- [ ] add `filter `to the `AggregationType `enum in the `com.ibm.watson.developer_cloud.discovery.v1.model.query` package

- [ ] create the proper deserialization of the response in the `com.ibm.watson.developer_cloud.discovery.v1.model.query.QueryAggregationAdapterFactory` class as well as create the appropriate models that extend the `com.ibm.watson.developer_cloud.discovery.v1.model.query.QueryAggregation` class (see `Calculation `aggregation for example)

- [ ] write a test that ingests a JSON document and then uses the new `filter `aggregation to create filter aggregation chained after a term aggregation

**When you open an issue for a feature request, please add as much detail as possible:**

- [x] A descriptive title starting with the service name

- [x] A description of the problem you're trying to solve

- [x] A suggested solution if possible

**Comment by stanleywym** [comment]
+1
