### ISSUE TITLE
[conversation] version.properties file could not be found

### ISSUE THREAD

**Issue by DimuthRuwantha** [watson-developer-cloud/java-sdk#586]
When the project is built and run the war file, it gives null in `InputStream` in the `RequestUtils.class`  in the `java-sdk/conversation`. but when I run it from the ide it works.
this is the line of code which returns null
```java
InputStream inputStream = Thread.currentThread().getContextClassLoader().getResourceAsStream("version.properties");
```

- [x] 1.8 JDK version
- [x]  3.5.3  java-sdk version
I have already asked on the [StackOverfolw](http://stackoverflow.com/questions/42311861/version-properties-file-could-not-be-found)

**Comment by germanattanasio** [comment]
This is something we need to fix before our next release

**Comment by DimuthRuwantha** [comment]
Hello Sir,
If you need more clarifications about what was actually happend please
don't hesitate to leave me a message.
Since I'm new to maven there may something I have done wrong.
Thanking you in advance,
Regards.





*Dimuth Ruwantha,Undergraduate,Faculty of Engineering,University of
Ruhuna,Sri Lanka.*

On Mon, Feb 20, 2017 at 11:12 PM, German Attanasio <notifications@github.com

**Comment by DimuthRuwantha** [comment]
try adding this two lines into the RequestUtils.class
`ClassLoader classLoader = RequestUtils.class.getClassLoader();
Thread.currentThread().setContextClassLoader( classLoader );`

**Comment by germanattanasio** [comment]
Hi @DimuthRuwantha sorry for the delay, do you think you can write a PR for this particular issue. It seems like you know how to fix it.

**Comment by DimuthRuwantha** [comment]
Thank you for the notification sir.
Even-though I couldn't write a PR due to busy schedules of my exams, I
could contribute to watson at-least by a word.
Regards.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>





*Dimuth Ruwantha,Undergraduate,Faculty of Engineering,University of
Ruhuna,Sri Lanka.*
