### ISSUE TITLE
Just 2 suggestions (speech to text and language translation)

### ISSUE THREAD

**Issue by shikida** [watson-developer-cloud/java-sdk#62]
First of all, congrats for this fine piece of software. Extremely useful.
Here go my suggestions:

# Speech to text
I'm getting much better results using
```
recognize(audio, "audio/wav");
```
instead of
```
recognize(audio, "audio/l16; rate=44100")
```
my wav file properties, when I right click using linux UI says

Codec: Uncompressed 16-bit PCM audio
Channels: Stereo
Sample rate: 44100 Hz
Bitrate: N/A

# LanguageTranslation

When I try to translate "obrigacão" from pt to en, Watson does not recognize the tilde.

But if I submit "obrigacao", then it correctly translate it to "duty".

So my suggestion is to "clean up" the string like this
```
s = Normalizer.normalize(s, Normalizer.Form.NFD).replaceAll("\\p{InCombiningDiacriticalMarks}+", "");
```
before using the translate() method

TIA

Leo

**Comment by germanattanasio** [comment]
fixed as part of #72
