### ISSUE TITLE
Visual Recognition 3.7.0 not found at maven central

### ISSUE THREAD

**Issue by julianommartins** [watson-developer-cloud/java-sdk#621]
Team, Im not able to get 3.7.0 from maven central. Just 3.6.0. The documentation tell to use 3.7.0.

**Comment by julianommartins** [comment]
FYI:  Failed to execute goal on project watsontests: Could not resolve dependencies for project com.ibm.mysa:watsontests:jar:0.0.1-SNAPSHOT: Failure to find com.ibm.watson.developer_cloud:java-sdk:jar:3.7.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]

**Comment by germanattanasio** [comment]
Hi @julianommartins, it usually takes a few hours for the jar to be available in Maven.
It's available now https://search.maven.org/#artifactdetails%7Ccom.ibm.watson.developer_cloud%7Cjava-sdk%7C3.7.0%7Cjar

**Comment by julianommartins** [comment]
Worked now. thanks.

**Comment by germanattanasio** [comment]
https://search.maven.org/#artifactdetails%7Ccom.ibm.watson.developer_cloud%7Cvisual-recognition%7C3.7.0%7Cjar

**Comment by germanattanasio** [comment]
I'm reopening this issue because it seems like Visual Recognition is the one that returns 404

**Comment by germanattanasio** [comment]
I redeployed 3.7.0 and tested that Visual Recognition is there. https://repo1.maven.org/maven2/com/ibm/watson/developer_cloud/visual-recognition/3.7.0/visual-recognition-3.7.0.jar

**Comment by julianommartins** [comment]
Strange, I just got the same issue. Here is my POM
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.ibm.mysa</groupId>
  <artifactId>watsontests</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <dependencies>

	<dependency>
		<groupId>com.ibm.watson.developer_cloud</groupId>
		<artifactId>java-sdk</artifactId> 
		<version>3.7.0</version>
	</dependency>

  </dependencies>
</project>

**Comment by julianommartins** [comment]
It worked now. Tks
