### ISSUE TITLE
Missing readme in Natural Language Understanding

### ISSUE THREAD

**Issue by bjoernkarmann** [watson-developer-cloud/java-sdk#634]
There is missing a readme for the natural-language-understanding, just like in the Natural Language Classifier.

**Comment by aruniyengar** [comment]
When the readme file for natural-language-understanding is added to the github repository, it would be good to include examples similar to the ones in:
 java-sdk/natural-language-understanding/src/test/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/NaturalLanguageUnderstandingIT.java

The readme file could direct users to this file.
