### ISSUE TITLE
natural-language-understanding: limiting number of categories returned would be a useful feature

### ISSUE THREAD

**Issue by aruniyengar** [watson-developer-cloud/java-sdk#642]
For natural-language-understanding, it would be good to have the ability to limit the number of categories returned. I can limit the number of concepts, entities, and keywords returned but not the number of categories.

It appears that the class:
https://github.com/watson-developer-cloud/java-sdk/blob/develop/natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/CategoriesOptions.java
has not been fully implemented yet

**Comment by germanattanasio** [comment]
I don't think the API supports this

**Comment by germanattanasio** [comment]
@g-may what can we do here?

**Comment by germanattanasio** [comment]
I've communicated this to the team working on Natural Language Understanding.
