### ISSUE TITLE
[java-sdk] Broken link to jar with dependencies in installation guide

### ISSUE THREAD

**Issue by JSHHansen** [watson-developer-cloud/java-sdk#647]
In the Readme.md under "Installation", when you click the link for the jar with dependencies under "jar" subsection you get 404.

This is the link my browser tries to open:

https://github.com/watson-developer-cloud/java-sdk/releases/download/java-sdk-3.7.2/java-sdk-3.7.2-jar-with-dependencies.jar

**Comment by germanattanasio** [comment]
Fixed
