### ISSUE TITLE
[natural-language-understanding] Wrong usage of constructor in readme file

### ISSUE THREAD

**Issue by teja-tummalapalli** [watson-developer-cloud/java-sdk#649]
In readme file the NLU service is created with default constructor.

`NaturalLanguageUnderstanding service = new NaturalLanguageUnderstanding();`

But this constructor is not  available. The two constructors available accepts one string or three strings.
Working example:
`NaturalLanguageUnderstanding service = new NaturalLanguageUnderstanding("2017-02-27");`

So readme need to changed to reflect correct usage.
`

**Comment by germanattanasio** [comment]
Fixed
