### ISSUE TITLE
Concept Insights: fix corpus id in createCorpus

### ISSUE THREAD

**Issue by msushkov** [watson-developer-cloud/java-sdk#66]
Concept Insights API requires corpus `id` to be of the form `/corpora/{account_id}/{corpus}`. `createCorpus()` takes in a `Corpus` object, where an `id` is required. `createCorpus()` creates a URL for the request by concatenating `/v2/corpora/{account_id}` and the `id` from the `Corpus` object; currently this concatenation results in `/v2/corpora/{account_id}/corpora/{account_id}/corpus`.

Proposed solution: since Concept Insights API does not require an `id` for the corpus, allow `Corpus.id` to be `null` in `createCorpus()`. Add a `name` field to `Corpus` and use that when calling `createCorpusIdPath()` from `createCorpus()`.

**Comment by msushkov** [comment]
@alseddnm

**Comment by germanattanasio** [comment]
@alseddnm is working on this.

**Comment by germanattanasio** [comment]
@alseddnm did some work on this e447b8ccdb50f65f13e64253dbd79aa74e13e30b

**Comment by germanattanasio** [comment]
fixed in the next release
