### ISSUE TITLE
[Conversation] The Java-SDK should support the `/workspaces` API for Watson Conversation Service

### ISSUE THREAD

**Issue by doconnor78** [watson-developer-cloud/java-sdk#663]
The Watson Conversation service has released the `/workspaces` REST API. The Java SDK should be updated to support the methods on that API (POST/GET etc)

**Comment by germanattanasio** [comment]
We have the 3.7.3-SNAPSHOT in sonatype.

https://oss.sonatype.org/content/repositories/snapshots/com/ibm/watson/developer_cloud/java-sdk/

**Comment by germanattanasio** [comment]
3.8.0 Added support for `/workspaces`
