### ISSUE TITLE
[Conversation] dialog_nodes field is missing from the WorkspaceExportResponse object

### ISSUE THREAD

**Issue by JoshSharpe** [watson-developer-cloud/java-sdk#673]
In version 3.8.0 of the sdk, dialog_nodes is missing from the WorkspaceExportResponse object.

Code: https://github.com/watson-developer-cloud/java-sdk/blob/develop/conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/WorkspaceExportResponse.java#L71
Docs: https://www.ibm.com/watson/developercloud/conversation/api/v1/#get_workspace

**Comment by mkistler** [comment]
That was intentional because Dialog Nodes are not considered "public" yet.
