### ISSUE TITLE
Doubt - how to retrieve documents from Alchemy News?

### ISSUE THREAD

**Issue by shikida** [watson-developer-cloud/java-sdk#68]
Sorry, I can see that DocumentsResult toString() returns a clear JSON with all the results.
But I am kind of lost about iterating on the objects.

DocumentsResult docs = s.getNewsDocuments(map);
Documents documents = docs.getDocuments();
System.out.println(documents.getNext()); => returns something I can't understand that seems like some serialized object

How do I access the elements inside the Documents object?

TIA

Leo

**Comment by shikida** [comment]
Silly me.
Just add 
public List<Document> getDocuments() {
		return documents;
	}
to Documents POJO and
		public Sentiment getSentiment() {
			return sentiment;
		}
to Article.EnrichedTitle

**Comment by germanattanasio** [comment]
did you have to update the code to support that? That looks suspicious. If that's the case, can you do a Pull request with your changes?

**Comment by shikida** [comment]
Seems like a minor problem. Someone probably forgot to generate getters/setters for some attributes. I am not used to GIT :-) I have to spend some time to learn its incantations :-)

**Comment by shikida** [comment]
Much more important than that, IMO, is to guarantee that the result is always serialized / deserialized to JSON, because since some APIs (such as Alchemy) are limited daily, users can save the response and reuse it for tests / development (e.g. DocumentsResult docs = GsonSingleton.getGson().fromJson(json,DocumentsResult.class))

**Comment by germanattanasio** [comment]
@shikida that's a very good point. All our classes redefine the toString to be the json representation. so you can serialized them easily by calling the `toString()`

**Comment by shikida** [comment]
shouldn't have something like d.getSource().getEnriched().getArticle().getEnrichedTitle().getSentiment() ? How do I get the Sentiment from an anticle using 1.1.1?

**Comment by germanattanasio** [comment]
Sorry but I don't understand what you are asking: ( can you please provide the snippet you are using and describe what the problem is.

**Comment by shikida** [comment]
Sorry, I was not finding this object path -- d.getSource().getEnriched().getArticle().getEnrichedTitle().getEntities().get(0).getSentiment()

please close this issue, thanks
