### ISSUE TITLE
Stream audio from mic to IBM Watson SpeechToText service using Java SDK

### ISSUE THREAD

**Issue by varadharajan1** [watson-developer-cloud/java-sdk#685]
Hi,

https://github.com/watson-developer-cloud/java-sdk/blob/master/examples/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/MicrophoneWithWebSocketsExample.java

The above example "Line not supported" message and program exits.

```java
if (!AudioSystem.isLineSupported(info)) {
  System.out.println("Line not supported");
  System.exit(0);
}
```

Note: `watson-develomer-cloud/java-sdk/3.8.0 (java-sdk-3.8.0-jar-with-dependencies.jar)`

Thanks

**Comment by germanattanasio** [comment]
Java SDK version? Android? Can you please provide steps to reproduce the issue

**Comment by varadharajan1** [comment]
Hi,

Thank you for your prompt reply.
I used JDK 1.8 and watson java-sdk 3.8.0.  No Android. 

Regards
Varadharajan

**Comment by varadharajan1** [comment]
Hi,

Thank you for your prompt reply.
I used JDK 1.8 and watson java-sdk 3.8.0 (java-sdk-3.8.0-jar-with-dependencies.jar)

Steps to reproduce:

1) Create SpeachToText watson service on BlueMix
2) Get the username and password and replace it on the below example.

In the https://github.com/watson-developer-cloud/java-sdk/blob/master/examples/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/MicrophoneWithWebSocketsExample.java

3) Execute the MicrophoneWithWebSocketsExample.java 

Regards
Varadharajan

**Comment by germanattanasio** [comment]
> The audio format that you are using is not supported by that `DataLine` not by Java. In this case, you're trying to record from the default audio input (usually the microphone) and your sound card doesn't support the audio format that you're using. You need to check what audio formats your system supports and use one of those
See: http://stackoverflow.com/questions/30287131/java-recording-audio-line-not-supported

**Comment by germanattanasio** [comment]
You are probably trying that on your computer. Check your microphone and `DataLine` configuration
