### ISSUE TITLE
Java SDK + React Native Compatibility 

### ISSUE THREAD

**Issue by RobertWSaunders** [watson-developer-cloud/java-sdk#695]
Feature Request: Enable the Java SDK to be used with React Native Android projects. Currently React Native does not support `okhttp 3.7.0` which is needed by the SDK to run IBM JDK. 

When adding the SDK to the `build.gradle` of a Android project generate using React Native file like: 

```gradle
dependencies {
    compile project(':react-native-tts')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile "com.ibm.watson.developer_cloud:speech-to-text:3.8.0"
}
```
After syncing Gradle and building the project an error will occur: 

```Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lokhttp3/internal/ws/RealWebSocket$1;
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
```
This error is a result of `com.facebook.react:react-native:+` requiring `okhttp 3.4.2` and `com.ibm.watson.developer_cloud:speech-to-text:3.8.0` requiring `okhttp 3.7.0`, therefore this is a versioning issue. You can see the dependancy trace below:

![screen_shot_2017-05-10_at_2 32 21_pm_720](https://cloud.githubusercontent.com/assets/13367451/26015508/441b37ec-372f-11e7-97f6-3689414cbc29.png)

Because of this, you are unable to use React Native at the same time as the Watson Java SDK.

Reproducible Steps:

NOTE: Assuming you can create React Native applications from the command line using the `react-native-cli` if not, please look at [here.](https://facebook.github.io/react-native/docs/getting-started.html)

1. Create a new React Native Project:
`react-native init AwesomeProject`

2. Open the Android Application and add the Watson Java SDK to `AwesomeProject/android/app/build.gradle` and make sure to sync Gradle:
```
dependencies {
    compile project(':react-native-tts')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile "com.ibm.watson.developer_cloud:speech-to-text:3.8.0" //add this line
}
```

3. Build the project, either through the CLI or using Android Studio. 

If there are any other questions comment them and I'll be happy to answer, would be really great to get the SDK to work with React Native projects, and also this may help improve the compatibility with other frameworks similar to React or dependancies that also use a lower version of `okhttp`.

**Comment by RobertWSaunders** [comment]
This has since been fixed as the React Native update their version of `okhttp`. :) The Java SDK is now compatible in React Native projects.

**Comment by germanattanasio** [comment]
Nice!

**Comment by RobertWSaunders** [comment]
The issue persists now that React Native has been downgraded to `okhttp 3.6.0`. See [`3af9be5`].
 (https://github.com/facebook/react-native/commit/3af9be52b272b767b480ed4f989ddfd6146a56f8)

**Comment by germanattanasio** [comment]
@RobertWSaunders I think I'm going to close this. We need to use the `okhttp-3.8.0` because of an issue with the IBM TLS certificates. This should work once the `react-native` project updates their dependency
