### ISSUE TITLE
[speech-to-text] Websocket interface - add support for specifying channels number for audio/l16

### ISSUE THREAD

**Issue by assaftibm** [watson-developer-cloud/java-sdk#702]
JDK 1.8.0.131
java-sdk-3.8.0
speech-to-text:3.8.1-SNAPSHOT
Windows 7 64bit

When sending PCM chunks to the service (mimetype: audio/l16 rather than audio/wav), it always assumes that the data is in mono.

 It would be useful to add an option by which the client can specify whether the data is of a mono or stereo recording. Note that the service has no problem to deal with stereo files in general, as is evident in its supports for transcribing stereo wav files.

**Comment by germanattanasio** [comment]
@daniel-bolanos ^^

**Comment by androidfanatic** [comment]
Would specifying content type in RecognizeOptions work? I've not tried this yet!

Something like this: 

    options = new RecognizeOptions.Builder()
	  .model("en-US_BroadbandModel")
	  .contentType("audio/l16; rate=16000; channels=2");

**Comment by daniel-bolanos** [comment]
@androidfanatic , yeah, that is correct. For headerless audio the number of channels can be passed in the `content-type` the way you did. For file formats with a header, that info is in the header.
