### ISSUE TITLE
Suggestion - Conversation API example enhancement 

### ISSUE THREAD

**Issue by shikida** [watson-developer-cloud/java-sdk#707]
Just because we don't  have any example or unit test with this, and just because Conversation is all about walking on the tree of nodes of the Conversation model, I'd like to suggest a very minor change in the documentation, just to show how to get from node 1 to node 2 of the conversation tree.

In order to do that, It' s incredibly simple, but since it's not documented anywhere, it's quite frustrating for newbies I guess.

All we need is to show that we must assign to the next message the context of the previous answer, like this

```
private Map<String, Object> ctx = new HashMap<>();

method xyzInTheLoop(){
  MessageRequest newMessage = new MessageRequest.Builder().inputText(StringUtils.join(words, " ")).context(ctx).build();
  MessageResponse response = service.message("...", newMessage).execute();
  **ctx = response.getContext();**
  System.out.println(">"+newMessage.inputText());
  System.out.println("<"+response.getTextConcatenated(" "));
}
```
TIA

**Comment by germanattanasio** [comment]
Hi @shikida, we can add the example but can you update the snippet and make it a complete example. We usually use the `car_dashboard.json` for examples
