### ISSUE TITLE
Conversation node contains an answer that has a @ sign (email) and output is interpreted as an entity

### ISSUE THREAD

**Issue by shikida** [watson-developer-cloud/java-sdk#708]
Not sure if this is a bug or not, but I have a node that contains an email.

When I try to print the MessageResponse object, here's what happens

`System.out.println("OUT "+response.getOutput());`

> OUT {log_messages=[{level=err, msg=Error when resolving SpEL expression [ entities['us']?.metadata?.ibm.com ]. Original expression was [ @us.ibm.com ].}, {level=err, msg=Error when updating output with output of dialog node id [node_1_1490098759027]. Node output is [{"text":{"values":["****** xyz@us.ibm.com ********** "],"selection_policy":"sequential"}}]
> org.springframework.expression.spel.SpelEvaluationException: EL1007E:(pos 0): Property or field 'com' cannot be found on null

If I use this instead

`System.out.println("OUT "+response.getTextConcatenated(" "));`

No error is reported.

Maybe I am not understanding what getOutput() means in this case.What's the difference between getOutput() and getTextConcatenated()? is this a bug?

**Comment by germanattanasio** [comment]
This is not a problem with the SDK. See https://stackoverflow.com/questions/38703213/getting-org-springframework-expression-spel-spelparseexception-error-from-watson. You need to make sure special characters are escaped in the conversation nodes.
