### ISSUE TITLE
Checkstyle causes gradle build to fail

### ISSUE THREAD

**Issue by kognate** [watson-developer-cloud/java-sdk#712]
There are checkstyle errors causing the gradle build
to fail.  These are mostly (very) minor issues.

**Comment by mkistler** [comment]
@kognate I am unable to reproduce the checkstyle errors in my environment.  Any thoughts on why?

**Comment by germanattanasio** [comment]
@mkistler I found that it depends on the JDK you are using.

**Comment by germanattanasio** [comment]
fixed in the previous pull request
