### ISSUE TITLE
[Retrieve & Rank] Error 500 - Internal server error

### ISSUE THREAD

**Issue by leliseu** [watson-developer-cloud/java-sdk#721]
Well, regarding the steps to reproduce the error, I don't really have a step-by-step, but here's what happened:
We have an application running on Bluemix since july 2016 and we using Retrieve & Rank API service. 
Recently our API calls started returning error code 500 and we are unable to use our application right now. We openned a ticket to Bluemix support and they confirmed that this issue should have been resolved using jdk 3.8.0, but it still returns to us the error code 500. 
Therefore Bluemix Support team asked us to open an issue on this GitHub.   

Expected Behavior:
Return a list of the collections we have

Actual Behavior:
Error code 500
![rrerror500](https://cloud.githubusercontent.com/assets/29230864/26834417/aca26f94-4aab-11e7-84cd-289686ee9c6f.png)
![rrinternalerror](https://cloud.githubusercontent.com/assets/29230864/26834416/ac90fb7e-4aab-11e7-980f-9fc15724948e.png)

Java-jdk version 3.8.0 and 3.7.2 both with the same error

And here is the code of our Servlet:

```java
package br.ibm.pcm;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;


import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.solr.client.solrj.SolrServerException;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

/**
 * Servlet implementation class GetColletions
 */
@WebServlet("/GetCollections")
public class GetCollections extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public GetCollections() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		response.getWriter();
        PrintWriter out;
        response.setContentType("text/html");
        out = response.getWriter ();
        
        JSONObject obj = new JSONObject();
    	JSONArray list = new JSONArray();
        WatsonProcessing wp = new WatsonProcessing();
        
        try {
			List<String> collections = wp.listCollections();
			for(int i=0; i<collections.size();i++){
	    	list.add(collections.get(i));
			}
		} catch (SolrServerException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	obj.put("collections", list);
    	out.print(obj);
	}



	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}
```

And this is the code from our class to list the collections ( receiving error 500 ):

```java
public List<String> listCollections() throws SolrServerException, IOException {
		    HttpSolrClient solrClient=null;
		  	List<String> cluster_ids = GetClusterIds();
		  	List<String> collections= new ArrayList<String>();
		  	
		  	for(int i=0;i<cluster_ids.size();i++){
				  solrClient = getSolrClient(RR.getSolrUrl(cluster_ids.get(i)), USERNAME, PASSWORD,cluster_ids.get(i));
				    CollectionAdminRequest.List listCollectionRequest = new CollectionAdminRequest.List();
				    CollectionAdminResponse listResponse = listCollectionRequest.process(solrClient);
				    List<String> lista_collections = (List<String>) listResponse.getResponse().get("collections");	
				    for(int j=0;j<lista_collections.size();j++){
				    	collections.add(lista_collections.get(j));
				    }
		  	}

			return collections;
	  }
```

**Comment by germanattanasio** [comment]
Hi @leliseu, Can you try updating your SolrJ dependency? can you also check if calling `listClusters()` works?

**Comment by leliseu** [comment]
Hello @germanattanasio ! Sorry for the delayed response, I`ve updated the SolrJ and SolrJ-core both to version 6.5.1 and java-jdk is already at 3.8.0 but I still get the error code 500 while trying to get the collections from the clusters or any other call to our Retrieve & Rank service ... 
listClusters() worked for almost a year, we haven`t changed anything on the code, right now it is returning code 500 but it has worked for almost a year ... I will be glad to help in anything I can, just let me know what you need.
Thanks in advance!
Attached below are some screenshots of the proccess and also the error we receive:
`Error 500: java.lang.RuntimeException: java.net.UnknownServiceException: Unable to find acceptable protocols
. isFallback=false, modes=[ConnectionSpec&#40;cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256
, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions
=[TLS_1_2, TLS_1_1, TLS_1_0], supportsTlsExtensions=true&#41;, ConnectionSpec&#40;cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256
, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions
=[TLS_1_0], supportsTlsExtensions=true&#41;, ConnectionSpec&#40;&#41;], supported protocols=[TLSv1, TLSv1
.1, TLSv1.2]
![error500](https://user-images.githubusercontent.com/29230864/26992798-a64c8d36-4d36-11e7-9c70-e7251ad59db6.png)
![updated_dependencies](https://user-images.githubusercontent.com/29230864/26992799-a66ae57e-4d36-11e7-9595-e3880f9550cb.png)
![updated_dependencies2](https://user-images.githubusercontent.com/29230864/26992800-a69a49ae-4d36-11e7-9563-9904c97d8a7e.png)


`

**Comment by leliseu** [comment]
@germanattanasio Do you think it is possible to us to schedule a meeting or something so that we could work together and try to fix this real-time? My email is leliseu@br.ibm.com and I`m available from Monday to Friday from 9:00AM till 6:00PM GMT-3, message me if you need anything else!

**Comment by leliseu** [comment]
After uploading it a few time to Bluemix it finally worked out! Thanks!

**Comment by elamocaibm** [comment]
Did this problem just fixed itself? My team's experiencing the exact same issue.

**Comment by leliseu** [comment]
The problem fixed after I updated a few dependencies such as SolrJ and Solr-core
