### ISSUE TITLE
[speech-to-text] Recent commit removed ability to configure OkHttpClient for services

### ISSUE THREAD

**Issue by DigitalZebra** [watson-developer-cloud/java-sdk#722]
Hello,
We are currently using the ability to configure OkHttpClient in the method `WatsonService.configureHttpClient` to configure proxies and other settings needed before connecting to the speech to text service via the SDK. We noticed that this configuration API was removed with commit https://github.com/watson-developer-cloud/java-sdk/pull/690/commits/3e1c6b6e36c42ef132aea2e5dfadf1722305d941 to fix issue #686. Unfortunately this puts us in a bind as we won't be able to upgrade to the latest version of the SDK and take advantage of future bug fixes and features.

Is there another way recommended to configure settings like this? Or, is there some other way we could provide the same functionality with the new singleton implementation that was added? I'm thinking that some sort of OkHttpClient factory that could be injected in to `WatsonService` would satisfy the requirement of re-using the connections and also providing a way to override how the client is constructed.

Thanks much!

**Comment by germanattanasio** [comment]
My bad @DigitalZebra, I will work on this and get it fixed next week

**Comment by DigitalZebra** [comment]
Thank you so much! We really appreciate it. Let me know if I can assist in any way.

**Comment by germanattanasio** [comment]
If you can write a PR that will be awesome!
