### ISSUE TITLE
[Speech-to-Text] Stops in seconds for websocket transcription

### ISSUE THREAD

**Issue by nimicent** [watson-developer-cloud/java-sdk#727]
Hey guys this is Julia in Watson,

Since there is a possible NDA I cannot go into detail publicly and client has not had time to file issue due to migrating to Node from Java. I don't think they have done this process before so I can help with this and re-route the correspondence furthermore.

This is big migration and I think they prefer Java so it might save time to solve this issue for them.

Especially as their Node deployment is not fully functional and this is slowing down their development cycle. I have been troubleshooting this with said client and another speech engineer for around a week now. 

The client has said that they are not sure they can find another file that fails the same way that is externally shareable for the filing of this issue.

_"It opens a socket and within about 5 seconds disconnects because the socket closed. No results returned. We have other files that work fine."_

So steps to reproduce are particular to specific files and these are not externally shareable resources.

The expected behavior is to transcribe audio without failing.

An STT expert and I have been troubleshooting this with them and from crossing off that they are properly compressing audio and also using the API correctly, we have been able to exhaust our support and leave the actual Java SDK in question for this STT issue.

Java SDK 3.8.0

**Comment by germanattanasio** [comment]
@nimicent I need the code and file you are using in order to reproduce the issue.
