### ISSUE TITLE
Retrieve and Rank readme needs updating

### ISSUE THREAD

**Issue by dpowell1** [watson-developer-cloud/java-sdk#730]
There is no such method `createSolrCluster`. How does one create a SolrCluster?

**Comment by germanattanasio** [comment]
https://github.com/watson-developer-cloud/java-sdk/blob/master/retrieve-and-rank/src/main/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/ClusterLifecycleManager.java#L31
