### ISSUE TITLE
Use Jdiff to publish the API changes along with the javadoc

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/java-sdk#741]
See: http://javadiff.sourceforge.net/

Guava uses this in their release history: https://github.com/google/guava/wiki/ReleaseHistory

**Comment by germanattanasio** [comment]
@chohanbin if the build passes and we publish the API Diff then we can close this issue

**Comment by lpatino10** [comment]
Unfortunately, the changes we made don't quite work yet. Hopefully fixes in #949 will let us close this.

**Comment by germanattanasio** [comment]
I'm looking at http://watson-developer-cloud.github.io/java-sdk/apidiff/ and I don't think it's working 🤔

**Comment by germanattanasio** [comment]
is this working @lpatino10?

**Comment by lpatino10** [comment]
Nope, still not working 😕
