### ISSUE TITLE
[conversation] CreateDialogNode class uncomplete

### ISSUE THREAD

**Issue by ghiringh** [watson-developer-cloud/java-sdk#742]
Hi,

The class named CreateDialogNode contains a private attribute dialogNode corresponding to the name or the title of the dialogNode. It is the only attribute present in the class and in the builder (intern class).

Example : 
CreateDialogNode cdn = new CreateDialogNode.Builder().dialogNode("name").build();

This makes impossible to set the attributes : 
- conditions
- context
- description
- goTo
- metadata
- output
- parent
- previousSibling

Example: 
CreateDialogNode cdn = new CreateDialogNode.Builder().dialogNode("name")
.conditions(conditions)
.context(context).build();

Having a private contructor, the CreateDialogNode class cannot be extended. Then the setter and getter for these other parametters have to be implemented in the SDK.
In finale, it makes impossible to create a conversation fully through the API.

Thanks

**Comment by germanattanasio** [comment]
We are working on this @ghiringh. See #732.
