### ISSUE TITLE
[NaturalLanguageUnderstanding ] NoSuchMethodError in Java SDK

### ISSUE THREAD

**Issue by amalober** [watson-developer-cloud/java-sdk#743]
I am trying to run the documentation example (with text instead of a url) like this:

```
NaturalLanguageUnderstanding service = new NaturalLanguageUnderstanding(
NaturalLanguageUnderstanding.VERSION_DATE_2017_02_27,
service.setUsernameAndPassword(serviceUsername, servicePassword);

EntitiesOptions entities = new EntitiesOptions.Builder().sentiment(true).limit(1).build();
Features features = new Features.Builder().entities(entities).build();
AnalyzeOptions parameters = new AnalyzeOptions.Builder().test(testString).features(features).build();
AnalysisResults results = service.analyze(parameters).execute();

```
and it immediately returns the error:

_Exception in thread "main" java.lang.NoSuchMethodError: com.ibm.watson.developer_cloud.http.RequestBuilder.query([Ljava/lang/Object;)Lcom/ibm/watson/developer_cloud/http/RequestBuilder;
	at com.ibm.watson.developer_cloud.natural_language_understanding.v1.NaturalLanguageUnderstanding.analyze(NaturalLanguageUnderstanding.java:123)
	at ...[my main in the last line of code I shared ( `service.analyze(parameters).execute();`)_

When I go to the SDK code, I find that in the NaturalLanguageUnderstanding class (analyze method), the line that fails is the builder.query() invocation:
```
 public ServiceCall<AnalysisResults> analyze(AnalyzeOptions parameters) {
    RequestBuilder builder = RequestBuilder.post("/v1/analyze");
    builder.query(VERSION, versionDate);

```
If I go to the RequestBuilder class, I found no query(String,String) method (nor in it's parent). 

I also found that `RequestBuilder.post("/v1/analyze") `ends up with the host "http://do.not.use/v1/analyze"
Since  it ends up calling  `return new RequestBuilder(HTTPMethod.POST, url);`
and the code is
```
  private RequestBuilder(HTTPMethod method, String url) {
    this.method = method;
    if (url == null)
      throw new IllegalArgumentException("url cannot be null");

    // Since HttpUrl requires requires a http/s full url, add a default endpoint
    httpUrl = HttpUrl.parse(url);
    if (httpUrl == null)
      this.httpUrl = HttpUrl.parse(RequestUtil.DEFAULT_ENDPOINT + url);
  }
```
url is "/v1/analyze", httpUrl will be null and RequestUtil.DEFAULT_ENDPOINT  is "http://do.not.use"
- [NaturalLanguageUnderstanding ] 
- [1.8 ] JDK version
- [ 3.8.0] java-sdk version

**Comment by germanattanasio** [comment]
@amalober can you try with the code in `develop` or `3.8.1-SNAPSHOT`
