### ISSUE TITLE
[conversation] Why is the API Endpoint hardcoded?

### ISSUE THREAD

**Issue by ExtremoBlando** [watson-developer-cloud/java-sdk#748]
Using the latest java-sdk version, had to compile myself to replace 
`private static final String URL = "https://gateway.watsonplatform.net/conversation/api"`
 with
` "private static final String URL = "https://gateway-fra.watsonplatform.net/conversation/api"`
 otherwise it would fail with 401 Unauthorized

Why is the API Endpoint hardcoded if there are several possibilities? I have the service placed in Germany.

Thanks in advance.

**Comment by germanattanasio** [comment]
The default value is hardcoded, but you can replace it calling `setEndPoint()`

**Comment by germanattanasio** [comment]
I think we can improve the README so that people know about this method. Do you think you can write a PR for that @ExtremoBlando?
