### ISSUE TITLE
UnsupportedEncodingException is never thrown from the try statement body

### ISSUE THREAD

**Issue by weiwunb** [watson-developer-cloud/java-sdk#75]
`com.ibm.watson.developer_cloud.service.Request	`

Unreachable catch block for UnsupportedEncodingException. This exception is never thrown from the try statement body

	public Request withContent(String content, String contentType) {
		try {
			StringEntity stringEntity = new StringEntity(content, UTF_8);
			if (contentType != null) {
				stringEntity.setContentType(contentType);
			}
			return withEntity(stringEntity);
		} catch (UnsupportedEncodingException e) {
			throw new RuntimeException(e);
		}
	}

**Comment by germanattanasio** [comment]
As a result of #72, this was fixed.
