### ISSUE TITLE
Discovery : Not returning Passages.

### ISSUE THREAD

**Issue by vivekmalikymca** [watson-developer-cloud/java-sdk#757]
I don't think we have option to enable passages in current sdk. 
could you please add passages support.

** queryBuilder class doesn't have any method for passages just unlike count and filter
current option.
      queryBuilder.query(q);
      discovery.query(queryBuilder.build()).execute();

**Comment by lpatino10** [comment]
This capability should be possible in version 3.8.0 of the SDK. It's possible as an option in the QueryRequest.Builder as shown here: https://www.ibm.com/watson/developercloud/discovery/api/v1/?java#query-collection
