### ISSUE TITLE
Date Format Exception for Android

### ISSUE THREAD

**Issue by shafiblogs** [watson-developer-cloud/java-sdk#76]
While using jar file, I got an exception in android " Unknown pattern charecter 'X' "

Solution for this issue. 

package name: com.ibm.watson.developer_cloud.util
class name: GsonSingleton
change string constant 
`String DATE_FORMAT_UTC = "yyyy-MM-dd'T'HH:mm:ss.SSSX";`
like this
`String DATE_FORMAT_UTC = "yyyy-MM-dd'T'HH:mm:ss.SSSZ";`

Please change one line above and deploy new jar.

**Comment by germanattanasio** [comment]
We currently have: `""yyyy-MM-dd'T'HH:mm:ss.SSSZ"`. Hopefully this will be part of our next release. Thanks

**Comment by germanattanasio** [comment]
fixed in the next release

**Comment by shafiblogs** [comment]
Thanks

**Comment by germanattanasio** [comment]
http://developer.android.com/reference/java/text/SimpleDateFormat.html for future reference
