### ISSUE TITLE
[speech-to-text] Websockets issue while using java SDK

### ISSUE THREAD

**Issue by joveval** [watson-developer-cloud/java-sdk#797]
I've tried to use `recognizeUsingWebSocket` but when using it I just obtain a log message:
`2017-09-07 10:07:09.836 ERROR 13200 --- [WebSocketThread] .w.d.s.v.w.SpeechToTextWebSocketListener : Stop message discarded because WebSocket is unavailable`
And after that nothing more happens.

### Additional information
- [ ] Steps to reproduce:
`SpeechToText service = new SpeechToText();`
`service.setUsernameAndPassword("<username>", "<password>");`
`File file = new File(audioFileURL);`
`InputStream inStream = new FileInputStream(file);`
`service.recognizeUsingWebSocket(inStream,options, new BaseRecognizeCallback(){//implementation});`

- [ ] Expected behavior:
Method `public void onTranscription(SpeechResults speechResults)`  must be executed after Speech to text API has extracted text from audio.
- [ ] Actual behavior
Just `2017-09-07 10:07:09.836 ERROR 13200 --- [WebSocketThread] .w.d.s.v.w.SpeechToTextWebSocketListener : Stop message discarded because WebSocket is unavailable` appears.
- [ ] JDK version : 1.8
- [ ] java-sdk version: 3.9.1

**Comment by germanattanasio** [comment]
@lpatino10 can you take a look at this?

**Comment by lpatino10** [comment]
If you are still having this problem, would you be able to provide more information on your `RecognizeOptions` or implementation details? I just ran the following code on my computer with the same JDK and java-sdk versions and I'm seeing the `onTranscription()` method being executed:

```java
SpeechToText service = new SpeechToText();
service.setUsernameAndPassword(<username>, <password>);
File file = new File("src/main/resources/sample1.wav");
InputStream inStream = new FileInputStream(file);

RecognizeOptions options = new RecognizeOptions.Builder()
    .interimResults(true)
    .inactivityTimeout(40)
    .timestamps(true)
    .maxAlternatives(2)
    .wordAlternativesThreshold(0.5)
    .model("en-US_BroadbandModel")
    .contentType(HttpMediaType.AUDIO_WAV)
    .inactivityTimeout(120)
    .build();

service.recognizeUsingWebSocket(inStream, options, new BaseRecognizeCallback() {

@Override
public void onConnected() {
    System.out.println("onConnected()");
}

@Override
public void onDisconnected() {
    System.out.println("onDisconnected()");
}

@Override
public void onTranscriptionComplete() {
    System.out.println("onTranscriptionComplete()");
}

@Override
public void onError(Exception e) {
    e.printStackTrace();
}

@Override
public void onTranscription(SpeechResults speechResults) {
    System.out.println("onTranscription()");
}
```

**Comment by joveval** [comment]
I've added:
 `.interimResults(true)`
 `.inactivityTimeout(40)`
 `.contentType(HttpMediaType.AUDIO_FLAC)`
 `.inactivityTimeout(120)`
to `RecognizeOptions`
And now is working. Thanks for your help!

**Comment by germanattanasio** [comment]
![selfie-0](https://i.imgur.com/2PabAv4.gif)
