### ISSUE TITLE
[Conversation] doesn't return the same order of entities when input different speechs

### ISSUE THREAD

**Issue by YingjiaLiu** [watson-developer-cloud/java-sdk#798]
SDK version: 3.9.1
VERSION_DATE_2017_04_21.
Please refer to Ticket #5377-13727509

When analyzing the entities in MessageResponse, the order for "she goes down a tunnel" get reversed.
Below is the entity list in `MessageResponse`.
```json
[{
  "entity": "Location",
  "location": [
    23,
    29
  ],
  "value": "Tunnel"
}, {
  "entity": "Direction",
  "location": [
    13,
    17
  ],
  "value": "Down"
}, {
  "entity": "Pronoun",
  "location": [
    2,
    5
  ],
  "value": "She"
}]
```

**Comment by lpatino10** [comment]
The entities returned in `MessageResponse` don't come back in any particular order. They should be parsed based on the entity properties like `value` or `location`.
