### ISSUE TITLE
Training  Conversation API through java coding

### ISSUE THREAD

**Issue by gopikrishnagurram** [watson-developer-cloud/java-sdk#806]
Hi, 
I want to train conversation api from java conversation client library, I want sample examples to create Entity,  Node conditions and responses. Is it possible, If yes how? 

Thanks

**Comment by germanattanasio** [comment]
Hi @gopikrishnagurram, You can use the Javadoc to learn about the SDK: http://watson-developer-cloud.github.io/java-sdk/docs/java-sdk-4.0.0/

You can also look at the documentation for Conversation: https://console.bluemix.net/docs/services/conversation/index.html
