### ISSUE TITLE
[text-to-speech] Return AudioInputStream instead of InputStream

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/java-sdk#81]
Lots of users are trying to use the InputStream they get from Text to Speech into an `AudioInputStream` without luck.

**Comment by svergara1987** [comment]
Hello, I'm one of those having this problem. 
I've tried different variants and was able to save an audio file in my file system and play it later (not by code). But couldn't play the stream using Java. 
Attached, you can see the last test and the corresponding output. 
Any suggestion?
![new test code](https://cloud.githubusercontent.com/assets/15147119/10526037/aed70ca0-735e-11e5-89c1-022be173dbcf.PNG)
![new test output](https://cloud.githubusercontent.com/assets/15147119/10526042/b2fee69a-735e-11e5-8c8c-88dc19961353.PNG)

**Comment by germanattanasio** [comment]
@daniel-bolanos I think this is related to the way we save the wav file by default. It could be the encoding we are using. What do you think?

**Comment by germanattanasio** [comment]
@daniel-bolanos I've created a test Case so that we can test the problem: https://gist.github.com/germanattanasio/e2b1e3d25fa85a16a503

**Comment by germanattanasio** [comment]
The issue is that the InputStream coming from `/synthesize` doesn't have the `content-length` specified because it was streamed (`InputStream`) :bowtie:.
There are two options:
 1. Read the inputStream and put the `content-length` manually
 1. Find a way to reproduce it without `content-length`

I'm going to implement the first one in a `Utils` class.

cc: @svergara1987

**Comment by germanattanasio** [comment]
@daniel-bolanos discovered this by adding manually the `content-length`, after that I was able to reproduce the file with `AudioInputStream`.

**Comment by svergara1987** [comment]
Great! Thanks @germanattanasio . 
I'm already waiting for that Utils class

**Comment by RobWills** [comment]
Is this the kind of solution you need?

    InputStream is;
    is = tts_service.synthesize(text, Voice.GB_KATE, HttpMediaType.AUDIO_WAV);

    File audio = new File(System.getProperty( "user.home" ) + "/" + "output.wav");

    OutputStream outStream = null;				
    try {
        outStream = new FileOutputStream(audio);

        byte[] buffer = new byte[8 * 1024];
        int bytesRead;
        while ((bytesRead = is.read(buffer)) != -1) {
            outStream.write(buffer, 0, bytesRead);
        }
    } catch (Exception e) {
        System.out.println(e.getMessage());
    } finally {
        IOUtils.closeQuietly(is);
        IOUtils.closeQuietly(outStream);
        audio = null;
    }

**Comment by germanattanasio** [comment]
I think the problem is that the service is streaming the audio back to the user and since it doesn't know the size, is not adding the proper headers to the wav file.
Some modern audio players can play the audio without knowing the size but when you are trying to play it in java you need to know those things.

The android-speech-sdk has a class that deal with this and I was thinking on copy some of that code here (see [this](https://github.com/watson-developer-cloud/speech-android-sdk)).

**Comment by Tympanix** [comment]
Did you ever finish the utils class and would you mind sharing?

**Comment by germanattanasio** [comment]
There is a fix already in `dev`. The idea is to read the `InputStream` into a `byte[]` and once we know the audio file size create a new WAV header with it.  

The header of a WAV (RIFF) file is 44 bytes long and has the following format:

Positions	| Sample Value | Description
--- | --- | ---
1 - 4 |	"RIFF" |	Marks the file as a riff file. Characters are each 1 byte long.
**5 - 8** |	**File size (integer)** |	**Size of the overall file - 8 bytes, in bytes (32-bit integer). Typically, you'd fill this in after creation.**
9 -12 |	"WAVE" |	File Type Header. For our purposes, it always equals "WAVE".
13-16 |	"fmt " |	Format chunk marker. Includes trailing null
17-20 |	16 |	Length of format data as listed above
21-22 |	1 |	Type of format (1 is PCM) - 2 byte integer
23-24 |	2 |	Number of Channels - 2 byte integer
25-28 |	44100 |	Sample Rate - 32 byte integer. Common values are 44100 (CD), 48000 (DAT). Sample Rate = Number of Samples per second, or Hertz.
29-32 |	176400 |	(Sample Rate * BitsPerSample * Channels) / 8.
33-34 |	4 |	(BitsPerSample * Channels) / 8.1 - 8 bit mono2 - 8 bit stereo/16 bit mono4 - 16 bit stereo
35-36 |	16 |	Bits per sample
37-40 |	"data" |	"data" chunk header. Marks the beginning of the data section.
**41-44** |	**File size (data)** |	**Size of the data section.**

> Sample values are given above for a 16-bit stereo source.

The Text to Speech service doesn't know the file size upfront so it can't write the values for **5-8** and **41-44**. The method `reWriteWaveHeader()` in the `WaveUtils` class write those values after reading the entire InputStream

**Comment by germanattanasio** [comment]
@Tympanix, @svergara1987 can you guys check if the code in `dev` fixes the issue you were facing here?

**Comment by germanattanasio** [comment]
Fixed in https://github.com/watson-developer-cloud/java-sdk/releases/tag/java-sdk-2.6.0
