### ISSUE TITLE
[visual recognition] Possibly missing API calls (version 4.0.0 compared to 3.9.1)

### ISSUE THREAD

**Issue by jsharpetbscg** [watson-developer-cloud/java-sdk#813]
Hiya

The 3.9.1 API had the following API calls:

VisualRecognitionOptions vro = new VisualRecognitionOptions.Builder().images(tmpFile).build();
RecognizedText t = service.recognizeText(vro).execute();

The "VisualRecognitionOptions" and "RecognizedText" appear to have been remove/not present

Is this due to the closing of the Beta "find Similar"?

JoN

**Comment by germanattanasio** [comment]
`recognizeText` was deprecated and that's why it's not in the SDK. 
Check the API specification here: https://watson-api-explorer.mybluemix.net/apis/visual-recognition-v3
