### ISSUE TITLE
[natural-language-understanding] Field missing in DocumentSentimentResults class

### ISSUE THREAD

**Issue by ayush2k** [watson-developer-cloud/java-sdk#814]
Document field of  Sentiment analysis results doesn't include `label` field.
https://github.com/watson-developer-cloud/java-sdk/blob/develop/natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/DocumentSentimentResults.java

Based on the document of NLU, the document field should consist of Label and Score. 
Example:
`{
"score": 0.127034,
"label": "positive"
}`

**Comment by lpatino10** [comment]
PRs to `develop` and `master` were merged.
