### ISSUE TITLE
watson-developer-cloud/java-sdk SockertTimeoutException issue

### ISSUE THREAD

**Issue by ysadam24** [watson-developer-cloud/java-sdk#818]
When I used watson-developer-cloud/java-sdk conversation version 4.0.0, We have encountered a problem with SocketTimeoutException.

I suspect that the excute method of the SeviceCall implementation generated by the createServiceCall method of the WatsonService class does not close after calling the excute method of OkHttp3.

### WatsonService.class
```java
 /**
   * Creates the service call.
   *
   * param <T> the generic type
   * param request the request
   * param converter the converter
   * return the service call
   */
  protected final <T> ServiceCall<T> createServiceCall(final Request request, final ResponseConverter<T> converter) {
    final Call call = createCall(request);
    return new ServiceCall<T>() {
      @Override
      public T execute() {
        try {
          Response response = call.execute();
          return processServiceCall(converter, response);
        } catch (IOException e) {
          throw new RuntimeException(e);
        }
      }
....
```
### okhttp3 - interface Call
```java
 /**
...
 The caller may read the response body with the response's {@link Response#body} method. To
 avoid leaking resources callers must {@linkplain ResponseBody close the response body} or the
 Response.
...
   */
  Response execute() throws IOException;
```
Please correct after confirmation.

**Comment by germanattanasio** [comment]
@ysadam24 What service and method are you trying to execute? We read the response and that close the socket. The only methods that aren't closing the response are the methods that return an `InputStream`

**Comment by ysadam24** [comment]
I am sorry. We found a closing part.

I have additional questions.

I created a service object on every request.
Could this be the cause of the problem?
Do I need to create only one service object, and do I need to share a service object on the per-request thread?

**Comment by germanattanasio** [comment]
If you have only one instance you will only do the authorization dance once because the instance will reuse the cookies from the first request. That will save you 200ms for every subsequent request.

**Comment by germanattanasio** [comment]
Closing since this is not an issue.
