### ISSUE TITLE
Unable to Execute Tradeoff Analytics

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/java-sdk#82]
I attempted to use your Java SDK to integrate Tradeoff Analytics into an application that we are developing at the Mobile Innovation Lab. We imported your jar (even downloaded and re-built it with gradle) and tried to execute the example test for Tradeoff Analytics, but were greeted with an error.

The error seemed to be related to GSON, which required the Column class to have a default constructor with no arguments. To resolve the error for our particular use-case, we had to modify the source code by adding a default constructor with no arguments, and by changing the abstract Column class to a concrete class.

These changes obviously aren't ideal, but they were enough for our use-case to get us back in business.

**Comment by germanattanasio** [comment]
you are talking about the example we have in the `examples` folder ?

**Comment by glennrfisher** [comment]
Yes. Sorry for the confusion.

The example linked below compiled, but failed for us due to the lack of a default constructor for the Column class with no arguments.

https://github.com/watson-developer-cloud/java-sdk/blob/master/examples/java/com/ibm/watson/developer_cloud/tradeoff_analytics/v1/TradeoffAnalyticsExample.java

**Comment by germanattanasio** [comment]
Fixed in the next release
