### ISSUE TITLE
Missing "continuous(Boolean b)" in RecognizeOptions of Speech-to-Text.

### ISSUE THREAD

**Issue by scprotz** [watson-developer-cloud/java-sdk#820]
I was moving my code to the newest version of STT and it was complaining about the 'continuous(true) call in the RecognizeOptions.Builder() call.  I read through the source code and it is missing the function in 4.0.

Hope this can be added back soon, or a suggestion for a workaround (my quick 5 minute read of the class didn't suggest any alternatives to setting it).

here is my sample line of code that is failing:

```java
RecognizeOptions options = new RecognizeOptions.Builder().continuous(true).interimResults(true).inactivityTimeout(120).contentType(HttpMediaType.AUDIO_RAW + "; rate=" + SAMPLE_RATE).build();
```

**Comment by mkistler** [comment]
The `continuous` parameter has been removed from STT recognize.  See this issue for the Swift SDK for some good information on how applications can adapt to this change.

https://github.com/watson-developer-cloud/swift-sdk/issues/632

**Comment by scprotz** [comment]
If this is the case, then it needs to be documented in the sample on STT readme on github.
