### ISSUE TITLE
Add customizationWeight parameter to Speech to Text trainCustomization() method

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/java-sdk#823]
In addition to appearing on the various recognize methods (via the RecognizeOptions object), the customizationWeight parameter can also be specified when a custom language model is trained.  The parameter needs to be added to the trainCustomization() method.

**Comment by lpatino10** [comment]
This feature will be added with the upcoming 5.0.0 release 👍

**Comment by lpatino10** [comment]
Closing as this feature is now available as of the v5.0.1 release.
