### ISSUE TITLE
Conversation - OutputData does not have nodes_visisted data 

### ISSUE THREAD

**Issue by sheethalk** [watson-developer-cloud/java-sdk#824]
com.ibm.watson.developer_cloud.conversation.v1.model.OutputData 
This method should not use **`nodesVisited`** but should use **`nodes_visited`**

```
 public List<String> getNodesVisited() {
      return GsonSerializationHelper.serializeDynamicModelProperty(this.get("**nodesVisited**"), nodesVisitedType);
  }
```

**Comment by lpatino10** [comment]
Thanks for bringing this to our attention. The issue is actually something that needs to be fixed across the SDK so I'll start working on that first thing in the morning.
