### ISSUE TITLE
[Visual_Recognition] Issue of authorization in dedicated environment.

### ISSUE THREAD

**Issue by KyubeomKim** [watson-developer-cloud/java-sdk#838]
Hi.
I found the issue of Authorization in Dedicated environment.

In our Visual Recognition Dedicated, the credentials are username and password. This is different from the public environment. (not API key)
However, we can't authenticate the user with the SDK 'setUsernameAndPassword()' method.
When this method is used, a 401 authentication error occurs.
We also changed the endpoint to our endpoint with the 'setEndPoint()' method.
Attach the code and error log below.

- code (Instance declaration section)

VisualRecognition service = new VisualRecognition( VisualRecognition.VERSION_DATE_2016_05_20);
service.setEndPoint("our endpoint");
service.setUsernameAndPassword("username","password");

- error
status: 401,
error: 
<HTML>
  <BODY>
    <p>Watson Message</p>
    <p>Credentials Required</p>
  </BODY>
</HTML>

**Comment by germanattanasio** [comment]
@lpatino10 ☝️ this is very important
