### ISSUE TITLE
[natural-language-classifier]A certificate error occurs in Java 8 environment.

### ISSUE THREAD

**Issue by Hidetomi** [watson-developer-cloud/java-sdk#841]
SSLHandshakeException occurs.
It is reproduced by sending a request to the API with jdk 8 u 144. It is reproduced in java version 9 as well.
The problem is that you are using the SHA1 algorithm on APIURL 's root certificate.
This problem is not a problem on the program, but because the program ends abnormally, it registers Issue.

**Comment by lpatino10** [comment]
Would you be able to give me any more information, like the code you're trying to run, the stack trace, and the version of the SDK you're using?

**Comment by Hidetomi** [comment]
## Can be solved by the following method, is it mandatory to use jdk?
### file:
`java.security`
### edit(before):
```
jdk.certpath.disabledAlgorithms=MD2, MD5, \
    RSA keySize < 1024, DSA keySize < 1024, EC keySize < 224
```
### edit(after):
```
jdk.certpath.disabledAlgorithms=MD2, MD5, SHA1 jdkCA & usage TLSServer, \
    RSA keySize < 1024, DSA keySize < 1024, EC keySize < 224
```

## Requested information
### using the version of the SDK
`3.7.1`
### the code(Excerpt):
```
        NaturalLanguageClassifier service = new NaturalLanguageClassifier();
        service.setApiKey(API_KEY);
        service.setUsernameAndPassword(USER_ID, PASSWORD);
        service.setEndPoint("https://gateway.watson-j.jp/natural-language-classifier/api");
        Classifiers classifiers = service.getClassifiers().execute();
        System.out.println(classifiers.toString());
```

### the stack trace: 
> Exception in thread "main" java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Usage constraint TLSServer check failed: SHA1 used with certificate: CN=Cybertrust Japan Public CA G3, O="Cybertrust Japan Co., Ltd.", C=JP.  Usage was tls server
> 	at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:193)
> 	at tst.watson.Test.main(Test.java:15)

> Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Usage constraint TLSServer check failed: SHA1 used with certificate: CN=Cybertrust Japan Public CA G3, O="Cybertrust Japan Co., Ltd.", C=JP.  Usage was tls server
> 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
> 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
> 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
> 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
> 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
> 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
> 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
> 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
> 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
> 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
> 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:267)
> 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:237)
> 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:148)
> 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186)
> 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
> 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
> 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
> 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
> 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
> 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
> 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
> 	at okhttp3.RealCall.execute(RealCall.java:63)
> 	at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:190)
> 	... 1 more
> 

> Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Usage constraint TLSServer check failed: SHA1 used with certificate: CN=Cybertrust Japan Public CA G3, O="Cybertrust Japan Co., Ltd.", C=JP.  Usage was tls server
> 	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:362)
> 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:270)
> 	at sun.security.validator.Validator.validate(Validator.java:260)
> 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
> 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
> 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
> 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
> 	... 28 more

> Caused by: java.security.cert.CertPathValidatorException: Usage constraint TLSServer check failed: SHA1 used with certificate: CN=Cybertrust Japan Public CA G3, O="Cybertrust Japan Co., Ltd.", C=JP.  Usage was tls server
> 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
> 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:223)
> 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
> 	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
> 	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)
> 	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:357)
> 	... 34 more

> Caused by: java.security.cert.CertPathValidatorException: Usage constraint TLSServer check failed: SHA1 used with certificate: CN=Cybertrust Japan Public CA G3, O="Cybertrust Japan Co., Ltd.", C=JP.  Usage was tls server
> 	at sun.security.util.DisabledAlgorithmConstraints$UsageConstraint.permits(DisabledAlgorithmConstraints.java:690)
> 	at sun.security.util.DisabledAlgorithmConstraints$Constraint.next(DisabledAlgorithmConstraints.java:481)
> 	at sun.security.util.DisabledAlgorithmConstraints$jdkCAConstraint.permits(DisabledAlgorithmConstraints.java:539)
> 	at sun.security.util.DisabledAlgorithmConstraints$Constraints.permits(DisabledAlgorithmConstraints.java:384)
> 	at sun.security.util.DisabledAlgorithmConstraints.permits(DisabledAlgorithmConstraints.java:158)
> 	at sun.security.provider.certpath.AlgorithmChecker.check(AlgorithmChecker.java:326)
> 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
> 	... 39 more
>

**Comment by germanattanasio** [comment]
This issue was fixed and should not be a problem if you use a version > 4.0.

**Comment by Hidetomi** [comment]
I tried it with version 4.2.1.
This problem was not reproduced.
I appreciate your comment.
