### ISSUE TITLE
[conversation] nodes_visited_details option for message method

### ISSUE THREAD

**Issue by FlatErik90** [watson-developer-cloud/java-sdk#855]
IBM recently announced that a _nodes_visited_details_ option attached to the message method would invoke

> additional diagnostic information about the nodes that were visited during processing of the message.
[Release Notes](https://console.bluemix.net/docs/services/conversation/release-notes.html#release-notes)

According to the API Explorer, this option has to be added to the URL as `&nodes_visited_details=true`. But I don't see any way to do this via the Java SDK. So maybe there needs to be an additional method similar to the MessageOptions.Builder.alternateIntents(true) that would add this parameter to the URL.

**Comment by lpatino10** [comment]
The newest major version of the SDK should be released in the next week or two, and this will include updates for all services, including the `nodesVisitedDetails` parameter.

**Comment by FlatErik90** [comment]
Is there any news about when the new major version is to be released?

**Comment by germanattanasio** [comment]
This week.

**Comment by lpatino10** [comment]
Hey @FlatErik90, v5.0.1 has just been released and has the `nodesVisitedDetails` functionality. Thanks for your patience!
