### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by smccants** [watson-developer-cloud/java-sdk#889]
The JavaDocs for com.ibm.watson.developer_cloud.speech_to_text.v1.model.RecognizeOptions and com.ibm.watson.developer_cloud.speech_to_text.v1.model.RecognizeOptions.Builder are incomplete.  All the references to inactivityTimeout do not contain the units of the timeout.  

It seems the units are seconds (based on the example, I expected milliseconds) based on this documentation:  https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/#recognize_audio_websockets

Maybe other units missing in JavaDocs for these files?

**Comment by germanattanasio** [comment]
I think we are having some issues with the script that publish the javadocs. We will take a look @smccants

**Comment by smccants** [comment]
It seems to be missing in the code.  I think this is a trivial fix unless your java docs are generated through something more complicated.

**Comment by lpatino10** [comment]
Hi @smccants. The new documentation generated for v5.0.1 should have more complete, including the `inactivityTimeout` information you were looking for earlier.

With this update, I'm going to close this issue.
