### ISSUE TITLE
[Speech to Text] STT tool for WebSocket written in Java suddenly stops outputing.

### ISSUE THREAD

**Issue by alpha-netzilla** [watson-developer-cloud/java-sdk#904]
If I use small size audio files, STT runs properly.
However, I use large size audio files(e.g. 50MB), this tool stops outputs on the way to transcribe.

I wrote a script at latest version(5.1.1) using the following updated procedures.
https://github.com/watson-developer-cloud/java-sdk/tree/develop/speech-to-text

e.g. output in my case
```
Stop message discarded because WebSocket is unavailable
{
  "results": [
    {
      "final": false,
      "alternatives": [
        {
          "transcript": "hello "
        }
      ]
    }
  ],
  "result_index": 0
}

-snip-

{
  "results": [
    {
      "final": false,
      "alternatives": [
        {
          "transcript": "today is "
        }
      ]
    }
  ],
  "result_index": 11
}
```

The output should continue.
Note: The messages of "Stop message discarded because WebSocket is unavailable" is output only when using a large size file.

I tried other wss tools written in node, ruby, etc.
They transcribed to the end.

This problem only occurs in this java tool.

**Comment by lpatino10** [comment]
Hi @alpha-netzilla, thanks for submitting this issue. I'll be sure to take a look at the cause of this problem as soon as I get the chance.

**Comment by germanattanasio** [comment]
@alpha-netzilla can you provide the code for the script you are using so that we can reproduce this issue on our end?

Can you also try with the latest version of the SDK after enabling the logging as described [here](https://github.com/watson-developer-cloud/java-sdk#debug)?

**Comment by alpha-netzilla** [comment]
I used the sample code below using the latest version of the SDK after enabling the logging.

WebSocket support
https://github.com/watson-developer-cloud/java-sdk/tree/develop/speech-to-text

I changed only one place.
```java
InputStream audio = new FileInputStream("myAudio.wav");
```
Note: The myAudio.wav is a large size audio file(e.g. 50MB).


However, the problem I pointed out has not been solved. The SDK suddenly stopped outputs with no error message.

Through trial and error, I found the workaround by chance. I inserted "Thread.sleep()" in SpeechToTextWebSocketListener.java code.


- com.ibm.watson.developer_cloud.speech_to_text.v1.websocket.SpeechToTextWebSocketListener.java

```java
  private void sendInputStream(InputStream inputStream) {
    byte[] buffer = new byte[ONE_KB];
    int read;
    try {
      // This method uses a blocking while loop to receive all contents of the underlying input stream.
      // AudioInputStreams, typically used for streaming microphone inputs return 0 only when the stream has been
      // closed. Elsewise AudioInputStream.read() blocks until enough audio frames are read.
      while (((read = inputStream.read(buffer)) > 0) && socketOpen) {
        if (read == ONE_KB) {
          socket.send(ByteString.of(buffer));
        } else {
          socket.send(ByteString.of(Arrays.copyOfRange(buffer, 0, read)));
        }
        Thread.sleep(10);
      }
    } catch (IOException e) {
      LOG.log(Level.SEVERE, e.getMessage(), e);
    } finally {
      try {
        inputStream.close();
      } catch (IOException e) {
        // do nothing - the InputStream may have already been closed externally.
      }
    }
  }
```

I would appreciate if you could investigate the cause.

**Comment by lpatino10** [comment]
Hey @alpha-netzilla. The latest release `v6.5.0` addresses some issues with WebSockets and I think might clear up this issue of large files. Maybe this will work for you.

If you try, let me know if it helps.

**Comment by alpha-netzilla** [comment]
I confirmed that the issue has been fixed.
Thank you for promptly handling the matter with care.
