### ISSUE TITLE
[java-sdk] Cannot connect to Discovery API on Oracle JRE, can connect on IBM JRE

### ISSUE THREAD

**Issue by andrewrfreed** [watson-developer-cloud/java-sdk#910]
I am trying to connect to https://gateway.watsonplatform.net/discovery/api
This works fine on IBM JRE 8.0, but does not work on Oracle JRE 8.0.

java-sdk version is 5.1.0

Oracle JRE version is 1.8.0_162-b12
IBM JREs version is 1.8.0_151 (build 8.0.5.6)

The error received is handshake_failure.
When trace is turned up very high I see a suspicious line:
Invalidated: [Session-1, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384]

The certificate I want is included in the default cacerts file.

**Comment by andrewrfreed** [comment]
Using the java-sdk in WebSphere Liberty, I was able to get this to work by forcing a downlevel version of TLS.  (Desired version was SSL_TLS2)

<ssl id="myDefaultSSLConfig"
         keyStoreRef="defaultKeyStore"
         sslProtocol="TLSv1.1"/>

**Comment by lpatino10** [comment]
Hey @andrewrfreed. Glad you were able to find a workaround for this for now.

I'm a little busy with things at the moment but I'll take a closer look at this issue as soon as I get the chance.

**Comment by germanattanasio** [comment]
@andrewrfreed how did you downgraded the TLS version? did you do that in the http client using `configureHttpClient()`?

**Comment by andrewrfreed** [comment]
I no longer have access to the code repo but I think that's exactly what I did.

**Comment by germanattanasio** [comment]
I just tested the latest release with the Oracle SDK and it worked. I don't think this was an SDK issue. I think it's related to the component in our platform that handles the TLS handshake.

@andrewrfreed feel free to reopen if this still occurs
