### ISSUE TITLE
[Assistant] getWorkspace throws a java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by guatson** [watson-developer-cloud/java-sdk#911]
```
public WorkspaceExport getWorkspace(WorkspaceBean workspace, boolean export) {
		Assistant service = new Assistant("2018-02-16");
		//service.setEndPoint("https://gateway.watsonplatform.net/assistant/api/");
		service.setUsernameAndPassword(workspace.getUsername(), workspace.getPassword());
		GetWorkspaceOptions options = new 
                                GetWorkspaceOptions.Builder(workspace.getWorkspaceid())
                                .export(export)
				.build();
		WorkspaceExport response = service.getWorkspace(options).execute();
		return response;
  }
```
I am converting my old working code from Conversation version 4.0.0 to Assistant 5.1.1 to be able to manage DialogNodes of "type":"folder".
This code was working well, the update API was throwing issues so I decided to convert to this version, but I am receiving  the following error:
``` 
Exception in thread "main" java.lang.NoSuchMethodError: com.ibm.watson.developer_cloud.http.RequestBuilder.constructHttpUrl(Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)Lokhttp3/HttpUrl;
	at com.ibm.watson.developer_cloud.assistant.v1.Assistant.getWorkspace(Assistant.java:266)
	at cl.nimatec.tools.workspaces.WorkspacesFacade.getWorkspace(WorkspacesFacade.java:324)
	at cl.nimatec.tools.workspaces.WorkspacesFacade.getWorkspaceIntentsDiff(WorkspacesFacade.java:167)
	at cl.nimatec.tools.workspaces.ComparaMueveEntToExcel.main(ComparaMueveEntToExcel.java:20)

```

I have check all my variable where not null, 
- [ ] Expected behavior.  Get a WorkspaceExport object with the Virtual Assistant training.
- [ ] Actual behavior.  Rhrows exception
- [ ] JDK version :  ibm_sdk80
- [ ] java-sdk version 1.8

**Comment by germanattanasio** [comment]
Make sure you update all the versions including the `core` version. 
Are you using gradle or maven?

**Comment by guatson** [comment]
Maven, it bring all the libs.
Initially I used artifact java-sdk, then assistant only.
✌
I will try to download dependency manually, it seems the error is at
okhttp..while Is a debugging I was able to see only IBM sdk sourcecode...

**Comment by germanattanasio** [comment]
Can you share your `pom.xml` file?

**Comment by lpatino10** [comment]
It sounds like your `core` library isn't updated.

With the latest release, we added a new method to the `core` that every service method calls. I see it in the error message: `constructHttpUrl` in the `RequestBuilder` class. That's why my guess is that your updated `Assistant` class is trying to call that method, but your `core` isn't updated so it can't find it.

If you think the `core` should've been updated, maybe try running a clean and build? Otherwise, sharing your `pom.xml` should be helpful.

**Comment by guatson** [comment]
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>ConversationTools</groupId>
	<artifactId>ConversationTools</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<build>
		<sourceDirectory>src</sourceDirectory>
		<resources>
			<resource>
				<directory>src</directory>
				<excludes>
					<exclude>**/*.java</exclude>
				</excludes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.7.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>com.ibm.watson.developer_cloud</groupId>
			<artifactId>java-sdk</artifactId>
			<version>5.1.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.17</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.17</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-io</artifactId>
			<version>1.3.2</version>
		</dependency>

	</dependencies>
</project>

`

**Comment by guatson** [comment]
![image](https://user-images.githubusercontent.com/22660771/38276700-43552cf8-376c-11e8-867e-dae43c639023.png)

**Comment by guatson** [comment]
I tried the following:

* Delete the .m2/repository folder
* Reload the dependencies, rebuild the project
* The issue persist.

What I am going to do:
* Create a new project solely for this simple test to call a Workspace.

What I found:
* When I run in Debug mode the source code is not really sync to the binaries, it shows lines in source code where there are comments...

**Comment by lpatino10** [comment]
I just created a new Maven project and used your `pom.xml` file with no issues, so I'm not sure off the top of my head what the problem is. Let me know if creating a new project still doesn't resolve the issue and we can investigate further.

**Comment by guatson** [comment]
Thanks to all, I've created a new project from scratch and worked fine...
