### ISSUE TITLE
[Discovery-add document] : getting errors when adding documents to my collection by multithreaded calls

### ISSUE THREAD

**Issue by mbesoft** [watson-developer-cloud/java-sdk#915]
I'm opening the same issue again (#907) because it seems that the problem is not related to the file type ... it happens randomly.

I uploaded 10 documents --> got the this error : "Error during indexing. The document contains a field type that is different than one with the same name in other documents" on 3 of them (only 7 were ingested)

I deleted the collection, tried again with 20 docuements (the previous ones and ten others) and it worked ... We are still facing the same issue even when we use the GUI Discovery

I can give you the documents if it could help ?

**Comment by germanattanasio** [comment]
Hi @mbesoft, It seems like you are getting the error when using the tooling too.
Let me get someone from the @watson-developer-cloud/discovery team to help you here.

**Comment by jeanlange** [comment]
## What's going on

Hi @mbesoft - The issue isn't with the /file/ type. It's about the /field/ type of one or more of your fields. What's happening is that one document gets ingested first, and that sets the schema for the index - and then a future document is ingested and doesn't match the schema, so it throws that error.

That's what [this documentation](https://console.bluemix.net/docs/services/discovery/troubleshooting.html#troubleshooting) (linked in the previous ticket) was trying to explain. I'll drop a note to our doc folks to ask them to clarify and add a suggestion about what to do. Meanwhile:

Here's an example of how that could happen:
* You have at least 2 documents, `document1` and `document2`
* Each document has a field - say, `xyz`.
  * In `document1`, that field looks like a date. For example: `'xyz': '2013-03-05'`
  * In `document2`, that field looks like just a normal string. For example: `'xyz': 'hello world'`.
* If `document1` gets ingested first, the unset schema looks at field `xyz` and says 'ah-hah, this is a date type! I will note that all future things that are ingested into this field name should be a date.'
  * Then, when `document2` is ingested, the schema sees the field `xyz` again and tries to parse the string value `hello world` as a date - and can't.
  * In this situation, you get the error above.
* On the other hand, if `document2` gets ingested first, the unset schema looks at field `xyz` and says 'ah, this is a string type.'
  * then, when `document1` gets ingested, the index has no problem storing the thing that looks like a date as a string.
  * In this situation, you get a successful ingestion.

## What can you do about it?
This is an ordering problem - if you can force the order to one that works, ingesting the more permissive field type first, you should be fine. So I suggest changing your code to always ingest one schema-setting document first, then the rest of them.

**Comment by mbesoft** [comment]
Now everything's clear ! 
Many thanks for your help @jeanlange and @germanattanasio .

**Comment by germanattanasio** [comment]
Thanks @jeanlange
