### ISSUE TITLE
Support multiple targets for GetTargetedSentiment

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/java-sdk#92]
The GetTargetedSentiment implies that it supports specifying multiple targets in a single call. http://www.alchemyapi.com/api/sentiment/textc.html#targetedsentiment However, it's not clear how you specify multiple targets to the REST API (you use the "targets" field instead of the "target", but how do you segment the multiple targets?). The Java wrapper should support this, and not check just for "target" but also "targets" in the code, and convert an array and/or List of targets to the appropriate format.

**Comment by germanattanasio** [comment]
I'll wait until @jsstylos find out how to actually send the targets.

**Comment by jsstylos** [comment]
And the answer is... pipe characters: cats|dogs
