### ISSUE TITLE
[java-sdk] IBM Watson APIs Java SDK use token authentication fail

### ISSUE THREAD

**Issue by changemyminds** [watson-developer-cloud/java-sdk#932]
I have some problem.  I use Watson APIs Java SDK and my Authentication was use function setUsernameAndPassword(username, password), but now I want to use [Tokens for authentication](https://console.bluemix.net/docs/services/watson/getting-started-tokens.html#tokens-for-authentication).

my "Username and Password" Code
```java
mAssistant = new Assistant("2018-02-16");
mAssistant.setUsernameAndPassword(mUserName, mPassword);
InputData input = new InputData.Builder("Hello").build();
MessageOptions options = new MessageOptions.Builder("{workspaceId}")
                                           .input(input)
                                           .build();
MessageResponse response = mAssistant.message(options).execute();
System.out.println(response);
```
it work fine.

Tokens for authentication
```java
mAssistant = new Assistant("2018-02-16");
Map<String, String> map = new HashMap<>();
map.put("X-Watson-Authorization-Token", "{token_string}");
mAssistant.setDefaultHeaders(map);
mAssistant.setSkipAuthentication(true);
InputData input = new InputData.Builder("Hello").build();
MessageOptions options = new MessageOptions.Builder("{workspaceId}")
                                           .input(input)
                                           .build();
MessageResponse response = mAssistant.message(options).execute();
System.out.println(response);
```

get the error code
```none
E/WatsonService: POST status: 403, error: Forbidden
com.ibm.watson.developer_cloud.service.exception.ForbiddenException: Forbidden
05-07 16:05:57.720 10392-10476/mvi.rcu W/System.err:     at com.ibm.watson.developer_cloud.service.WatsonService.processServiceCall(WatsonService.java:401)
05-07 16:05:57.720 10392-10476/mvi.rcu W/System.err:     at com.ibm.watson.developer_cloud.service.WatsonService$WatsonServiceCall.execute(WatsonService.java:459)
```
Is Watson APIs Java SDK support "X-Watson-Authorization-Token" or I incorrect use ?

Thanks!

**Comment by lpatino10** [comment]
Hey @changemyminds. I just checked myself and it seems that this form of authentication works fine with other services, so it might just not be supported by the Assistant service. I'm going to get more details to verify and I'll get back to you. The code you've written looks fine though.

**Comment by lpatino10** [comment]
Hey @changemyminds. I just checked myself and it seems that this form of authentication works fine with other services, so it might just not be supported by the Assistant service. I'm going to get more details to verify and I'll get back to you. The code you've written looks fine though.

**Comment by lpatino10** [comment]
Alright I've got a workaround @changemyminds.

Due to the Conversation -> Assistant rename, there seems to be an issue with authorization using the new name. Therefore, once you get your authorization token, you can use the `setEndPoint()` method to call the Conversation endpoint, like so:

```java
mAssistant = new Assistant("2018-02-16");
Map<String, String> map = new HashMap<>();
map.put("X-Watson-Authorization-Token", "{token_string}");
mAssistant.setDefaultHeaders(map);
mAssistant.setSkipAuthentication(true);

// change here
mAssistant.setEndPoint("https://gateway.watsonplatform.net/conversation/api");
```

Assistant is just an alias for Conversation internally so your API calls should work the same. Let me know if this works okay for you.

**Comment by changemyminds** [comment]
Method-1
Get token by url https://gateway.watsonplatform.net/assistant/api
```
curl -X GET --user {username}:{password} "https://gateway.watsonplatform.net/authorization/api/v1/token?url=https://gateway.watsonplatform.net/assistant/api"
```
Use token
```
mAssistant = new Assistant("2018-02-16");
Map<String, String> map = new HashMap<>();
map.put("X-Watson-Authorization-Token", "{token_string}");
mAssistant.setDefaultHeaders(map);
mAssistant.setSkipAuthentication(true);
```

Method-2
Get token by url https://gateway.watsonplatform.net/conversation/api
```
curl -X GET --user {username}:{password} "https://gateway.watsonplatform.net/authorization/api/v1/token?url=https://gateway.watsonplatform.net/conversation/api"
```
Use token
```
mAssistant = new Assistant("2018-02-16");
Map<String, String> map = new HashMap<>();
map.put("X-Watson-Authorization-Token", "{token_string}");
mAssistant.setDefaultHeaders(map);
mAssistant.setSkipAuthentication(true);
mAssistant.setEndPoint("https://gateway.watsonplatform.net/conversation/api");
```
Thanks for your answer. It work fine for me. But there have two method for use token, which method is better ?

**Comment by lpatino10** [comment]
If you're using the Assistant service, I think it makes more sense to use the first method. Like you said though, both are essentially equivalent.

Since this has been resolved, I'm going to go ahead and close this issue.
