### ISSUE TITLE
Watson Language translation call from Android app - code crashes in translate call

### ISSUE THREAD

**Issue by bramach5** [watson-developer-cloud/java-sdk#95]
I am trying to do a simple Android app that calls Watson language translation API.

Below is the code ...
 ```java
mytranslation = new LanguageTranslation();
mytranslation.setEndPoint("https://gateway.watsonplatform.net/language-translation/api");
mytranslation.setUsernameAndPassword("username","password");
TranslationResult result = mytranslation.translate("Hello world", "en", "es");
translated_string = result.toString();
watsonResp.setText("Success, Watson is initialized  " + translated_string );
```
App does work fine without the Watson service... so, I guess something must be going wrong in the above snippet that calls Watson service. It crashes on the translate line.

One other strange thing that seems to be happening is that even if I give an incorrect password, it still crashes on the translate line. Should it not stop earlier ? Not sure why this happens.

**Comment by germanattanasio** [comment]
@bramach5 this will be fixed in the next release.
