### ISSUE TITLE
[java-sdk] IBM Watson Assistant MessageResponse issue

### ISSUE THREAD

**Issue by changemyminds** [watson-developer-cloud/java-sdk#953]
I have some problem. 
On some mobile phones (version 7.0, ASUS_Z012DA), I found that if I let the phone standby for about ten minutes and then resume the phone and execute the following code it will wait three minutes before going to the exception. Is Assistant class have timeout function? 
Or I need to check time if the following code waits a long time then interrupt and resend it.
I think it is a network issue. Because at afternoon it works fine.
Do you have any ideal? thanks.

```java
new Thread(new Runnable() {
    @Override
    public void run() {
        try {
            // some time wait three minutes ...
            MessageResponse messageResponse = mAssistant.message(mMessageOptions).execute();
        }
        catch (Exception ex) {
            Log.e("watson", ex.getMessage());
        }
    }
});
```
sdk : com.ibm.watson.developer_cloud:java-sdk:5.4.0.
Android phone : android version 7.0, ASUS_Z012DA

**Comment by germanattanasio** [comment]
What's the error? Can you add the logs from the simulator?

**Comment by changemyminds** [comment]
Sorry. I can't repeat the issue to get the error log.  Because it work fine now. 
So I think it is network issue cause by special cell phone.

**Comment by germanattanasio** [comment]
Cool. I'm going to close this issue then. Feel free to re-open it
