### ISSUE TITLE
Update your documentation guys, will you ?

### ISSUE THREAD

**Issue by VRudzins** [watson-developer-cloud/java-sdk#961]
Hi guys.
I am making a Watson Workspace app that uses Discovery Service to extract passages of text that have particular String in it and display them and the headers they were under to the user.

At some point I needed to implement a way for user to upload a new document to collection. After 3 days  I finally did that, the app recognizes the files posted in space, downloads the file and posts it to collection using your Java SDK 6.1.0 API. 

It works. Good job.

But your documentation is all over the place. It's painful, example code snippets refer to methods and classes that were renamed like 2 versions ago.

I was raging and sweating immensely here comparing the code examples and Java SDK 6.1.0 API Javadoc. Some of the classes and method names do not exist anymore or were renamed and I had to guess them myself until everything fits in.

**Comment by lpatino10** [comment]
Hey @VRudzins, thanks for the feedback.

I've created a PR to update our code examples, which is referenced in this issue. As far as I can tell, this should bring all of the code examples in this repo up to date.

If I've missed something or you'd like me to get in contact with a different team about their documentation being outdated, please let me know.
