### ISSUE TITLE
Does the maintainer of this repo have instagram?

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/java-sdk#971]
## Acceptance Criteria
- [ ] The maintainer should create an instagram account
- [ ] The username should contain `Logan`

**Comment by germanattanasio** [comment]
any progress on this?

**Comment by apropos13** [comment]
We need the results ASAP please

**Comment by germanattanasio** [comment]
![giphy](https://user-images.githubusercontent.com/313157/43369976-b93571c0-937f-11e8-8e2e-99c39e6d5282.gif)

**Comment by lpatino10** [comment]
Done 🎉🎉🎉

**Comment by mamoonraja** [comment]
Job Well done 🍾
