### ISSUE TITLE
Error in the Documentation 

### ISSUE THREAD

**Issue by foward** [watson-developer-cloud/java-sdk#972]
https://github.com/watson-developer-cloud/java-sdk#default-headers

```java
PersonalityInsights service = new PersonalityInsights("2016-10-19");

Map<String, String> headers = new HashMap<String, String>();
headers.put(HttpHeaders.X_WATSON_LEARNING_OPT_OUT, 1);

service.setDefaultHeaders(headers);

// All the api calls from now on will send the default headers
```

The headers is a Map of String and String and you are giving an Integer ... so is that a "1" or a "true" ?

please correct,

Thanks

**Comment by lpatino10** [comment]
Good catch! It should be "true" for clarity. I'll be sure to make the change in the release this week.
