### ISSUE TITLE
Determine who the most handsome employee in IBM Watson Cambridge office is

### ISSUE THREAD

**Issue by stevengassert94** [watson-developer-cloud/java-sdk#974]
## Description
- in order to further progress the features and usability of this SDK, we must determine who the most handsome employee in IBM's Watson Cambridge location is so that our development team may stop pondering this question and return to work.

## Acceptance Criteria

- [ ] the most handsome employee has been determined.

**Comment by stevengassert94** [comment]
until I have the correct permissions, please assign this issue to @germanattanasio

**Comment by germanattanasio** [comment]
I will be working on this today. I hope to find him soon

**Comment by germanattanasio** [comment]
After some research I'm confident to say that the most handsome employee in IBM Watson Cambridge office is **Steven Gassert**.

I'm closing this as completed
