### ISSUE TITLE
Issues with WebSockets and custom language models

### ISSUE THREAD

**Issue by lpatino10** [watson-developer-cloud/java-sdk#987]
Two different issues have been found while using the `recognizeUsingWebSocket()` method on a custom language model in `v6.6.0` of the SDK.

In one instance, the `onTranscription()` method is never hit and the WebSocket connection times out, even though the audio file being tested was ~15 seconds long with no pauses.

In the other, the WebSocket connection disconnects and closes immediately, but works fine when the language model ID is not supplied.

**Comment by lpatino10** [comment]
After investigating more, it seems that the second case (immediate closing) was invalid and was just user-error on my part 🙂 

I still need to figure out how to reproduce the first issue.

**Comment by germanattanasio** [comment]
It looks like `customization_id` is being used even that it was deprecated. See https://github.com/watson-developer-cloud/java-sdk/blob/master/speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/websocket/SpeechToTextWebSocketListener.java#L58

![image](https://user-images.githubusercontent.com/313157/48719400-69393980-ebeb-11e8-9bf8-ba070c8015f7.png)
https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/curl.html?curl#websocket_methods

**Comment by lpatino10** [comment]
Closing as it looks like this was just user-error on my part.
