### ISSUE TITLE
WatsonSTT- Converting the byte code from Python to InputStream gets slow response

### ISSUE THREAD

**Issue by lavanya-lnt** [watson-developer-cloud/java-sdk#991]
We receive 1024 CHUNK from Python to Android. In Android we append in one Array and convert it to InputStream. We send this InputStream to STT service from which we receive a slow response. Please find the code snippet below:

```java
byte[] b = new byte[1024];
byte[] destinationArray = new byte[1024];
try {
    if (inStream != null) {
        inStream.read(b);
        String audioData = new String(b);
        while (!audioData.contains(AppConstants.PKT_FOOTER)) {
            destinationArray = Utility.concatenateByteArrays(destinationArray, b);
            b = new byte[1024];
            inStream.read(b);
            audioData = new String(b);
            Log.d(TAG, "Destination value: " + destinationArray.length);
        }
        InputStream myInputStream = new ByteArrayInputStream(destinationArray);
        translateSpeechToText(myInputStream);
    }
} catch (IOException e) {
    Log.e(TAG, Log.getStackTraceString(e));
}
```

- Android-sdk version 0.4.3
- java-sdk version 6.7.0

**Comment by germanattanasio** [comment]
@lavanya-lnt can you provide the steps to reproduce the problem? Maybe even a docker image we can use here.

**Comment by lavanya-lnt** [comment]
Steps: We are transferring the audio stream from Python using the following code
stream = p.open(format=FORMAT, channels=CHANNELS, rate=RATE, input=True, frames_per_buffer=CHUNK)
    print("* recording")
    c.send("STR")
    for i in range(0, int(RATE / CHUNK * RECORD_SECONDS)):
            data = stream.read(CHUNK)
            c.send(data)   # Sending audio Stream to client
    c.send("STP")
    print("* done recording")
    print "response =  ",
    Receive_Text()  # function call to Receive text

This will be received in Android application using the above shared code. 
byte[] b = new byte[1024];
byte[] destinationArray = new byte[1024];
try {
    if (inStream != null) {
        inStream.read(b);
        String audioData = new String(b);
        while (!audioData.contains(AppConstants.PKT_FOOTER)) {
            destinationArray = Utility.concatenateByteArrays(destinationArray, b);
            b = new byte[1024];
            inStream.read(b);
            audioData = new String(b);
            Log.d(TAG, "Destination value: " + destinationArray.length);
        }
        InputStream myInputStream = new ByteArrayInputStream(destinationArray);
        translateSpeechToText(myInputStream);
    }
} catch (IOException e) {
    Log.e(TAG, Log.getStackTraceString(e));
}

Android application will pass the stream to Watson STT using below code
speechService = new SpeechToText();
speechService.setUsernameAndPassword("USERNAME", "PASSWORD ");
speechService.setEndPoint("STT_URL");
speechService.recognizeUsingWebSocket(getRecognizeOptions(inputStream), new MicrophoneRecognizeDelegate());

We receive late response from STT. We connect android application and Python using socket.

**Comment by germanattanasio** [comment]
Can you write `myInputStream` into a file and reproduce it correctly? 
What type of audio are you saving, mp3, wav?

When you say "We receive late response from STT", what's `late`? 1 second? 10 seconds? 1 month? 1 year? 1 decade?

From the Python code, I can't see the `CHANNELS` or `FORMAT`. 

I need to understand what you are trying to send to the server and how you are using the SDK in order to help you.

**Comment by germanattanasio** [comment]
This issue has no reproducible steps. Please re-open this issue if it still occurs.
Check the CONTRIBUTING.md for an example.
