### ISSUE TITLE
IBM Watson Text to speech taking 2-4 seconds.

### ISSUE THREAD

**Issue by yashpatel001** [watson-developer-cloud/java-sdk#998]
IBM Watson TTS Service taking 2-4 second 

Expectation: Response time should be 1 second

```java
TextToSpeech textToSpeech = new TextToSpeech();
textToSpeech.setUsernameAndPassword("{username}", "{password}");

try {
  SynthesizeOptions synthesizeOptions =
    new SynthesizeOptions.Builder()
      .text("Hello world")
      .accept("audio/wav")
      .voice("en-US_AllisonVoice")
      .build();

  InputStream inputStream =
    textToSpeech.synthesize(synthesizeOptions).execute();
  InputStream in = WaveUtils.reWriteWaveHeader(inputStream);

  OutputStream out = new FileOutputStream("hello_world.wav");
  byte[] buffer = new byte[1024];
  int length;
  while ((length = in.read(buffer)) > 0) {
    out.write(buffer, 0, length);
  }

  out.close();
  in.close();
  inputStream.close();
} catch (IOException e) {
  e.printStackTrace();
}
```

compile 'com.ibm.watson.developer_cloud:java-sdk:6.8.0'
TTS version 6.8.0
android sdk 0.4.3

Requirement:  Like STT Service i want TTS Also using websocket or any other method to get less response time like 1 seconds.

**Comment by lpatino10** [comment]
Hey @yashpatel001. Unfortunately, we currently don't have SDK for using the `synthesize()` method with WebSockets.

That being said, I just tried your code snippet and got the resulting file in under a second consistently. Are you still seeing this delay? If so, it might've been a temporary slowness with the service. Also, if you're actually making this call in a larger app as opposed to just the provided snippet, it's possible that something else in the project is causing delays.

Let me know, because for now I can't reproduce the problem.

**Comment by yashpatel001** [comment]
Thanks @lpatino10 when TTS Will come using websocket anything update will come or not soon??

**Comment by lpatino10** [comment]
There are no current plans on implementing WebSocket support for TTS in the SDK. It's been talked about briefly but not prioritized.

**Comment by yashpatel001** [comment]
@lpatino10 Thanks,
So we cant achieve TTS Response time within a 1 second??

**Comment by lpatino10** [comment]
As far as I know, you should generally be able to get that response time unless you're trying to convert a really large piece of text. Like I said originally, I tested the code snippet you posted locally and it was synthesized almost immediately.

If you are working with larger blocks of text, it's possible you could do something like breaking the text up and asynchronously synthesizing the smaller pieces, but that's all project-specific.

**Comment by germanattanasio** [comment]
Duplicate to #987.

We need to add WS to Text to Speech

**Comment by yashpatel001** [comment]
@germanattanasio Thank you
so your team will develop WS Text to speech right?
